<?php
/**
 * Adnotacje
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * Adnotacje Class Doc Comment
 *
 * @category Class
 * @description Inne adnotacje na fakturze
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Adnotacje implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Adnotacje';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'p_16' => 'int',
        'p_17' => 'int',
        'p_18' => 'int',
        'p_18_a' => 'int',
        'zwolnienie' => '\KsefApi\Model\Zwolnienie',
        'nowe_srodki_transportu' => '\KsefApi\Model\NoweSrodkiTransportu',
        'p_23' => 'int',
        'p_marzy' => '\KsefApi\Model\PMarzy'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'p_16' => 'int32',
        'p_17' => 'int32',
        'p_18' => 'int32',
        'p_18_a' => 'int32',
        'zwolnienie' => null,
        'nowe_srodki_transportu' => null,
        'p_23' => 'int32',
        'p_marzy' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'p_16' => false,
        'p_17' => false,
        'p_18' => false,
        'p_18_a' => false,
        'zwolnienie' => false,
        'nowe_srodki_transportu' => false,
        'p_23' => false,
        'p_marzy' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'p_16' => 'P_16',
        'p_17' => 'P_17',
        'p_18' => 'P_18',
        'p_18_a' => 'P_18A',
        'zwolnienie' => 'Zwolnienie',
        'nowe_srodki_transportu' => 'NoweSrodkiTransportu',
        'p_23' => 'P_23',
        'p_marzy' => 'PMarzy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'p_16' => 'setP16',
        'p_17' => 'setP17',
        'p_18' => 'setP18',
        'p_18_a' => 'setP18A',
        'zwolnienie' => 'setZwolnienie',
        'nowe_srodki_transportu' => 'setNoweSrodkiTransportu',
        'p_23' => 'setP23',
        'p_marzy' => 'setPMarzy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'p_16' => 'getP16',
        'p_17' => 'getP17',
        'p_18' => 'getP18',
        'p_18_a' => 'getP18A',
        'zwolnienie' => 'getZwolnienie',
        'nowe_srodki_transportu' => 'getNoweSrodkiTransportu',
        'p_23' => 'getP23',
        'p_marzy' => 'getPMarzy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('p_16', $data ?? [], null);
        $this->setIfExists('p_17', $data ?? [], null);
        $this->setIfExists('p_18', $data ?? [], null);
        $this->setIfExists('p_18_a', $data ?? [], null);
        $this->setIfExists('zwolnienie', $data ?? [], null);
        $this->setIfExists('nowe_srodki_transportu', $data ?? [], null);
        $this->setIfExists('p_23', $data ?? [], null);
        $this->setIfExists('p_marzy', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['p_16']) && ($this->container['p_16'] > 2)) {
            $invalidProperties[] = "invalid value for 'p_16', must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['p_16']) && ($this->container['p_16'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_16', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_17']) && ($this->container['p_17'] > 2)) {
            $invalidProperties[] = "invalid value for 'p_17', must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['p_17']) && ($this->container['p_17'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_17', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_18']) && ($this->container['p_18'] > 2)) {
            $invalidProperties[] = "invalid value for 'p_18', must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['p_18']) && ($this->container['p_18'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_18', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_18_a']) && ($this->container['p_18_a'] > 2)) {
            $invalidProperties[] = "invalid value for 'p_18_a', must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['p_18_a']) && ($this->container['p_18_a'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_18_a', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_23']) && ($this->container['p_23'] > 2)) {
            $invalidProperties[] = "invalid value for 'p_23', must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['p_23']) && ($this->container['p_23'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_23', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets p_16
     *
     * @return int|null
     */
    public function getP16()
    {
        return $this->container['p_16'];
    }

    /**
     * Sets p_16
     *
     * @param int|null $p_16 Podwójne pole wyboru
     *
     * @return self
     */
    public function setP16($p_16)
    {
        if (is_null($p_16)) {
            throw new \InvalidArgumentException('non-nullable p_16 cannot be null');
        }

        if (($p_16 > 2)) {
            throw new \InvalidArgumentException('invalid value for $p_16 when calling Adnotacje., must be smaller than or equal to 2.');
        }
        if (($p_16 < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_16 when calling Adnotacje., must be bigger than or equal to 1.');
        }

        $this->container['p_16'] = $p_16;

        return $this;
    }

    /**
     * Gets p_17
     *
     * @return int|null
     */
    public function getP17()
    {
        return $this->container['p_17'];
    }

    /**
     * Sets p_17
     *
     * @param int|null $p_17 Podwójne pole wyboru
     *
     * @return self
     */
    public function setP17($p_17)
    {
        if (is_null($p_17)) {
            throw new \InvalidArgumentException('non-nullable p_17 cannot be null');
        }

        if (($p_17 > 2)) {
            throw new \InvalidArgumentException('invalid value for $p_17 when calling Adnotacje., must be smaller than or equal to 2.');
        }
        if (($p_17 < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_17 when calling Adnotacje., must be bigger than or equal to 1.');
        }

        $this->container['p_17'] = $p_17;

        return $this;
    }

    /**
     * Gets p_18
     *
     * @return int|null
     */
    public function getP18()
    {
        return $this->container['p_18'];
    }

    /**
     * Sets p_18
     *
     * @param int|null $p_18 Podwójne pole wyboru
     *
     * @return self
     */
    public function setP18($p_18)
    {
        if (is_null($p_18)) {
            throw new \InvalidArgumentException('non-nullable p_18 cannot be null');
        }

        if (($p_18 > 2)) {
            throw new \InvalidArgumentException('invalid value for $p_18 when calling Adnotacje., must be smaller than or equal to 2.');
        }
        if (($p_18 < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_18 when calling Adnotacje., must be bigger than or equal to 1.');
        }

        $this->container['p_18'] = $p_18;

        return $this;
    }

    /**
     * Gets p_18_a
     *
     * @return int|null
     */
    public function getP18A()
    {
        return $this->container['p_18_a'];
    }

    /**
     * Sets p_18_a
     *
     * @param int|null $p_18_a Podwójne pole wyboru
     *
     * @return self
     */
    public function setP18A($p_18_a)
    {
        if (is_null($p_18_a)) {
            throw new \InvalidArgumentException('non-nullable p_18_a cannot be null');
        }

        if (($p_18_a > 2)) {
            throw new \InvalidArgumentException('invalid value for $p_18_a when calling Adnotacje., must be smaller than or equal to 2.');
        }
        if (($p_18_a < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_18_a when calling Adnotacje., must be bigger than or equal to 1.');
        }

        $this->container['p_18_a'] = $p_18_a;

        return $this;
    }

    /**
     * Gets zwolnienie
     *
     * @return \KsefApi\Model\Zwolnienie|null
     */
    public function getZwolnienie()
    {
        return $this->container['zwolnienie'];
    }

    /**
     * Sets zwolnienie
     *
     * @param \KsefApi\Model\Zwolnienie|null $zwolnienie zwolnienie
     *
     * @return self
     */
    public function setZwolnienie($zwolnienie)
    {
        if (is_null($zwolnienie)) {
            throw new \InvalidArgumentException('non-nullable zwolnienie cannot be null');
        }
        $this->container['zwolnienie'] = $zwolnienie;

        return $this;
    }

    /**
     * Gets nowe_srodki_transportu
     *
     * @return \KsefApi\Model\NoweSrodkiTransportu|null
     */
    public function getNoweSrodkiTransportu()
    {
        return $this->container['nowe_srodki_transportu'];
    }

    /**
     * Sets nowe_srodki_transportu
     *
     * @param \KsefApi\Model\NoweSrodkiTransportu|null $nowe_srodki_transportu nowe_srodki_transportu
     *
     * @return self
     */
    public function setNoweSrodkiTransportu($nowe_srodki_transportu)
    {
        if (is_null($nowe_srodki_transportu)) {
            throw new \InvalidArgumentException('non-nullable nowe_srodki_transportu cannot be null');
        }
        $this->container['nowe_srodki_transportu'] = $nowe_srodki_transportu;

        return $this;
    }

    /**
     * Gets p_23
     *
     * @return int|null
     */
    public function getP23()
    {
        return $this->container['p_23'];
    }

    /**
     * Sets p_23
     *
     * @param int|null $p_23 Podwójne pole wyboru
     *
     * @return self
     */
    public function setP23($p_23)
    {
        if (is_null($p_23)) {
            throw new \InvalidArgumentException('non-nullable p_23 cannot be null');
        }

        if (($p_23 > 2)) {
            throw new \InvalidArgumentException('invalid value for $p_23 when calling Adnotacje., must be smaller than or equal to 2.');
        }
        if (($p_23 < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_23 when calling Adnotacje., must be bigger than or equal to 1.');
        }

        $this->container['p_23'] = $p_23;

        return $this;
    }

    /**
     * Gets p_marzy
     *
     * @return \KsefApi\Model\PMarzy|null
     */
    public function getPMarzy()
    {
        return $this->container['p_marzy'];
    }

    /**
     * Sets p_marzy
     *
     * @param \KsefApi\Model\PMarzy|null $p_marzy p_marzy
     *
     * @return self
     */
    public function setPMarzy($p_marzy)
    {
        if (is_null($p_marzy)) {
            throw new \InvalidArgumentException('non-nullable p_marzy cannot be null');
        }
        $this->container['p_marzy'] = $p_marzy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


