<?php
/**
 * Fa
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * Fa Class Doc Comment
 *
 * @category Class
 * @description Na podstawie art. 106a - 106q ustawy. Pola dotyczące wartości sprzedaży i podatku wypełnia się w walucie, w której wystawiono fakturę, z wyjątkiem pól dotyczących podatku przeliczonego zgodnie z przepisami Działu VI w związku z art. 106e ust. 11 ustawy. W przypadku wystawienia faktury korygującej, wypełnia się wszystkie pola wg stanu po korekcie, a pola dotyczące podstaw opodatkowania, podatku oraz należności ogółem wypełnia się poprzez różnicę
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Fa implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Fa';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kod_waluty' => '\KsefApi\Model\TKodWaluty',
        'p_1' => '\DateTime',
        'p_1_m' => 'string',
        'p_2' => 'string',
        'wz' => 'string[]',
        'p_13_1' => 'float',
        'p_14_1' => 'float',
        'p_14_1_w' => 'float',
        'p_13_2' => 'float',
        'p_14_2' => 'float',
        'p_14_2_w' => 'float',
        'p_13_3' => 'float',
        'p_14_3' => 'float',
        'p_14_3_w' => 'float',
        'p_13_4' => 'float',
        'p_14_4' => 'float',
        'p_14_4_w' => 'float',
        'p_13_5' => 'float',
        'p_14_5' => 'float',
        'p_13_6_1' => 'float',
        'p_13_6_2' => 'float',
        'p_13_6_3' => 'float',
        'p_13_7' => 'float',
        'p_13_8' => 'float',
        'p_13_9' => 'float',
        'p_13_10' => 'float',
        'p_13_11' => 'float',
        'p_15' => 'float',
        'kurs_waluty_z' => 'float',
        'adnotacje' => '\KsefApi\Model\Adnotacje',
        'rodzaj_faktury' => '\KsefApi\Model\TRodzajFaktury',
        'przyczyna_korekty' => 'string',
        'typ_korekty' => '\KsefApi\Model\TTypKorekty',
        'dane_fa_korygowanej' => '\KsefApi\Model\DaneFaKorygowanej[]',
        'okres_fa_korygowanej' => 'string',
        'nr_fa_korygowany' => 'string',
        'podmiot1_k' => '\KsefApi\Model\Podmiot1K',
        'podmiot2_k' => '\KsefApi\Model\Podmiot2K[]',
        'p_15_zk' => 'float',
        'kurs_waluty_zk' => 'float',
        'zaliczka_czesciowa' => '\KsefApi\Model\ZaliczkaCzesciowa[]',
        'fp' => 'int',
        'tp' => 'int',
        'dodatkowy_opis' => '\KsefApi\Model\TKluczWartosc[]',
        'faktura_zaliczkowa' => '\KsefApi\Model\FakturaZaliczkowa[]',
        'zwrot_akcyzy' => 'int',
        'fa_wiersz' => '\KsefApi\Model\FaWiersz[]',
        'rozliczenie' => '\KsefApi\Model\Rozliczenie',
        'platnosc' => '\KsefApi\Model\Platnosc',
        'warunki_transakcji' => '\KsefApi\Model\WarunkiTransakcji',
        'zamowienie' => '\KsefApi\Model\Zamowienie',
        'p_6' => '\DateTime',
        'p_6_od' => '\DateTime',
        'p_6_do' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kod_waluty' => null,
        'p_1' => 'date',
        'p_1_m' => null,
        'p_2' => null,
        'wz' => null,
        'p_13_1' => 'double',
        'p_14_1' => 'double',
        'p_14_1_w' => 'double',
        'p_13_2' => 'double',
        'p_14_2' => 'double',
        'p_14_2_w' => 'double',
        'p_13_3' => 'double',
        'p_14_3' => 'double',
        'p_14_3_w' => 'double',
        'p_13_4' => 'double',
        'p_14_4' => 'double',
        'p_14_4_w' => 'double',
        'p_13_5' => 'double',
        'p_14_5' => 'double',
        'p_13_6_1' => 'double',
        'p_13_6_2' => 'double',
        'p_13_6_3' => 'double',
        'p_13_7' => 'double',
        'p_13_8' => 'double',
        'p_13_9' => 'double',
        'p_13_10' => 'double',
        'p_13_11' => 'double',
        'p_15' => 'double',
        'kurs_waluty_z' => 'double',
        'adnotacje' => null,
        'rodzaj_faktury' => null,
        'przyczyna_korekty' => null,
        'typ_korekty' => null,
        'dane_fa_korygowanej' => null,
        'okres_fa_korygowanej' => null,
        'nr_fa_korygowany' => null,
        'podmiot1_k' => null,
        'podmiot2_k' => null,
        'p_15_zk' => 'double',
        'kurs_waluty_zk' => 'double',
        'zaliczka_czesciowa' => null,
        'fp' => 'int32',
        'tp' => 'int32',
        'dodatkowy_opis' => null,
        'faktura_zaliczkowa' => null,
        'zwrot_akcyzy' => 'int32',
        'fa_wiersz' => null,
        'rozliczenie' => null,
        'platnosc' => null,
        'warunki_transakcji' => null,
        'zamowienie' => null,
        'p_6' => 'date',
        'p_6_od' => 'date',
        'p_6_do' => 'date'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kod_waluty' => false,
        'p_1' => false,
        'p_1_m' => false,
        'p_2' => false,
        'wz' => false,
        'p_13_1' => false,
        'p_14_1' => false,
        'p_14_1_w' => false,
        'p_13_2' => false,
        'p_14_2' => false,
        'p_14_2_w' => false,
        'p_13_3' => false,
        'p_14_3' => false,
        'p_14_3_w' => false,
        'p_13_4' => false,
        'p_14_4' => false,
        'p_14_4_w' => false,
        'p_13_5' => false,
        'p_14_5' => false,
        'p_13_6_1' => false,
        'p_13_6_2' => false,
        'p_13_6_3' => false,
        'p_13_7' => false,
        'p_13_8' => false,
        'p_13_9' => false,
        'p_13_10' => false,
        'p_13_11' => false,
        'p_15' => false,
        'kurs_waluty_z' => false,
        'adnotacje' => false,
        'rodzaj_faktury' => false,
        'przyczyna_korekty' => false,
        'typ_korekty' => false,
        'dane_fa_korygowanej' => false,
        'okres_fa_korygowanej' => false,
        'nr_fa_korygowany' => false,
        'podmiot1_k' => false,
        'podmiot2_k' => false,
        'p_15_zk' => false,
        'kurs_waluty_zk' => false,
        'zaliczka_czesciowa' => false,
        'fp' => false,
        'tp' => false,
        'dodatkowy_opis' => false,
        'faktura_zaliczkowa' => false,
        'zwrot_akcyzy' => false,
        'fa_wiersz' => false,
        'rozliczenie' => false,
        'platnosc' => false,
        'warunki_transakcji' => false,
        'zamowienie' => false,
        'p_6' => false,
        'p_6_od' => false,
        'p_6_do' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kod_waluty' => 'KodWaluty',
        'p_1' => 'P_1',
        'p_1_m' => 'P_1M',
        'p_2' => 'P_2',
        'wz' => 'WZ',
        'p_13_1' => 'P_13_1',
        'p_14_1' => 'P_14_1',
        'p_14_1_w' => 'P_14_1W',
        'p_13_2' => 'P_13_2',
        'p_14_2' => 'P_14_2',
        'p_14_2_w' => 'P_14_2W',
        'p_13_3' => 'P_13_3',
        'p_14_3' => 'P_14_3',
        'p_14_3_w' => 'P_14_3W',
        'p_13_4' => 'P_13_4',
        'p_14_4' => 'P_14_4',
        'p_14_4_w' => 'P_14_4W',
        'p_13_5' => 'P_13_5',
        'p_14_5' => 'P_14_5',
        'p_13_6_1' => 'P_13_6_1',
        'p_13_6_2' => 'P_13_6_2',
        'p_13_6_3' => 'P_13_6_3',
        'p_13_7' => 'P_13_7',
        'p_13_8' => 'P_13_8',
        'p_13_9' => 'P_13_9',
        'p_13_10' => 'P_13_10',
        'p_13_11' => 'P_13_11',
        'p_15' => 'P_15',
        'kurs_waluty_z' => 'KursWalutyZ',
        'adnotacje' => 'Adnotacje',
        'rodzaj_faktury' => 'RodzajFaktury',
        'przyczyna_korekty' => 'PrzyczynaKorekty',
        'typ_korekty' => 'TypKorekty',
        'dane_fa_korygowanej' => 'DaneFaKorygowanej',
        'okres_fa_korygowanej' => 'OkresFaKorygowanej',
        'nr_fa_korygowany' => 'NrFaKorygowany',
        'podmiot1_k' => 'Podmiot1K',
        'podmiot2_k' => 'Podmiot2K',
        'p_15_zk' => 'P_15ZK',
        'kurs_waluty_zk' => 'KursWalutyZK',
        'zaliczka_czesciowa' => 'ZaliczkaCzesciowa',
        'fp' => 'FP',
        'tp' => 'TP',
        'dodatkowy_opis' => 'DodatkowyOpis',
        'faktura_zaliczkowa' => 'FakturaZaliczkowa',
        'zwrot_akcyzy' => 'ZwrotAkcyzy',
        'fa_wiersz' => 'FaWiersz',
        'rozliczenie' => 'Rozliczenie',
        'platnosc' => 'Platnosc',
        'warunki_transakcji' => 'WarunkiTransakcji',
        'zamowienie' => 'Zamowienie',
        'p_6' => 'P_6',
        'p_6_od' => 'P_6_Od',
        'p_6_do' => 'P_6_Do'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kod_waluty' => 'setKodWaluty',
        'p_1' => 'setP1',
        'p_1_m' => 'setP1M',
        'p_2' => 'setP2',
        'wz' => 'setWz',
        'p_13_1' => 'setP131',
        'p_14_1' => 'setP141',
        'p_14_1_w' => 'setP141W',
        'p_13_2' => 'setP132',
        'p_14_2' => 'setP142',
        'p_14_2_w' => 'setP142W',
        'p_13_3' => 'setP133',
        'p_14_3' => 'setP143',
        'p_14_3_w' => 'setP143W',
        'p_13_4' => 'setP134',
        'p_14_4' => 'setP144',
        'p_14_4_w' => 'setP144W',
        'p_13_5' => 'setP135',
        'p_14_5' => 'setP145',
        'p_13_6_1' => 'setP1361',
        'p_13_6_2' => 'setP1362',
        'p_13_6_3' => 'setP1363',
        'p_13_7' => 'setP137',
        'p_13_8' => 'setP138',
        'p_13_9' => 'setP139',
        'p_13_10' => 'setP1310',
        'p_13_11' => 'setP1311',
        'p_15' => 'setP15',
        'kurs_waluty_z' => 'setKursWalutyZ',
        'adnotacje' => 'setAdnotacje',
        'rodzaj_faktury' => 'setRodzajFaktury',
        'przyczyna_korekty' => 'setPrzyczynaKorekty',
        'typ_korekty' => 'setTypKorekty',
        'dane_fa_korygowanej' => 'setDaneFaKorygowanej',
        'okres_fa_korygowanej' => 'setOkresFaKorygowanej',
        'nr_fa_korygowany' => 'setNrFaKorygowany',
        'podmiot1_k' => 'setPodmiot1K',
        'podmiot2_k' => 'setPodmiot2K',
        'p_15_zk' => 'setP15Zk',
        'kurs_waluty_zk' => 'setKursWalutyZk',
        'zaliczka_czesciowa' => 'setZaliczkaCzesciowa',
        'fp' => 'setFp',
        'tp' => 'setTp',
        'dodatkowy_opis' => 'setDodatkowyOpis',
        'faktura_zaliczkowa' => 'setFakturaZaliczkowa',
        'zwrot_akcyzy' => 'setZwrotAkcyzy',
        'fa_wiersz' => 'setFaWiersz',
        'rozliczenie' => 'setRozliczenie',
        'platnosc' => 'setPlatnosc',
        'warunki_transakcji' => 'setWarunkiTransakcji',
        'zamowienie' => 'setZamowienie',
        'p_6' => 'setP6',
        'p_6_od' => 'setP6Od',
        'p_6_do' => 'setP6Do'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kod_waluty' => 'getKodWaluty',
        'p_1' => 'getP1',
        'p_1_m' => 'getP1M',
        'p_2' => 'getP2',
        'wz' => 'getWz',
        'p_13_1' => 'getP131',
        'p_14_1' => 'getP141',
        'p_14_1_w' => 'getP141W',
        'p_13_2' => 'getP132',
        'p_14_2' => 'getP142',
        'p_14_2_w' => 'getP142W',
        'p_13_3' => 'getP133',
        'p_14_3' => 'getP143',
        'p_14_3_w' => 'getP143W',
        'p_13_4' => 'getP134',
        'p_14_4' => 'getP144',
        'p_14_4_w' => 'getP144W',
        'p_13_5' => 'getP135',
        'p_14_5' => 'getP145',
        'p_13_6_1' => 'getP1361',
        'p_13_6_2' => 'getP1362',
        'p_13_6_3' => 'getP1363',
        'p_13_7' => 'getP137',
        'p_13_8' => 'getP138',
        'p_13_9' => 'getP139',
        'p_13_10' => 'getP1310',
        'p_13_11' => 'getP1311',
        'p_15' => 'getP15',
        'kurs_waluty_z' => 'getKursWalutyZ',
        'adnotacje' => 'getAdnotacje',
        'rodzaj_faktury' => 'getRodzajFaktury',
        'przyczyna_korekty' => 'getPrzyczynaKorekty',
        'typ_korekty' => 'getTypKorekty',
        'dane_fa_korygowanej' => 'getDaneFaKorygowanej',
        'okres_fa_korygowanej' => 'getOkresFaKorygowanej',
        'nr_fa_korygowany' => 'getNrFaKorygowany',
        'podmiot1_k' => 'getPodmiot1K',
        'podmiot2_k' => 'getPodmiot2K',
        'p_15_zk' => 'getP15Zk',
        'kurs_waluty_zk' => 'getKursWalutyZk',
        'zaliczka_czesciowa' => 'getZaliczkaCzesciowa',
        'fp' => 'getFp',
        'tp' => 'getTp',
        'dodatkowy_opis' => 'getDodatkowyOpis',
        'faktura_zaliczkowa' => 'getFakturaZaliczkowa',
        'zwrot_akcyzy' => 'getZwrotAkcyzy',
        'fa_wiersz' => 'getFaWiersz',
        'rozliczenie' => 'getRozliczenie',
        'platnosc' => 'getPlatnosc',
        'warunki_transakcji' => 'getWarunkiTransakcji',
        'zamowienie' => 'getZamowienie',
        'p_6' => 'getP6',
        'p_6_od' => 'getP6Od',
        'p_6_do' => 'getP6Do'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('kod_waluty', $data ?? [], null);
        $this->setIfExists('p_1', $data ?? [], null);
        $this->setIfExists('p_1_m', $data ?? [], null);
        $this->setIfExists('p_2', $data ?? [], null);
        $this->setIfExists('wz', $data ?? [], null);
        $this->setIfExists('p_13_1', $data ?? [], null);
        $this->setIfExists('p_14_1', $data ?? [], null);
        $this->setIfExists('p_14_1_w', $data ?? [], null);
        $this->setIfExists('p_13_2', $data ?? [], null);
        $this->setIfExists('p_14_2', $data ?? [], null);
        $this->setIfExists('p_14_2_w', $data ?? [], null);
        $this->setIfExists('p_13_3', $data ?? [], null);
        $this->setIfExists('p_14_3', $data ?? [], null);
        $this->setIfExists('p_14_3_w', $data ?? [], null);
        $this->setIfExists('p_13_4', $data ?? [], null);
        $this->setIfExists('p_14_4', $data ?? [], null);
        $this->setIfExists('p_14_4_w', $data ?? [], null);
        $this->setIfExists('p_13_5', $data ?? [], null);
        $this->setIfExists('p_14_5', $data ?? [], null);
        $this->setIfExists('p_13_6_1', $data ?? [], null);
        $this->setIfExists('p_13_6_2', $data ?? [], null);
        $this->setIfExists('p_13_6_3', $data ?? [], null);
        $this->setIfExists('p_13_7', $data ?? [], null);
        $this->setIfExists('p_13_8', $data ?? [], null);
        $this->setIfExists('p_13_9', $data ?? [], null);
        $this->setIfExists('p_13_10', $data ?? [], null);
        $this->setIfExists('p_13_11', $data ?? [], null);
        $this->setIfExists('p_15', $data ?? [], null);
        $this->setIfExists('kurs_waluty_z', $data ?? [], null);
        $this->setIfExists('adnotacje', $data ?? [], null);
        $this->setIfExists('rodzaj_faktury', $data ?? [], null);
        $this->setIfExists('przyczyna_korekty', $data ?? [], null);
        $this->setIfExists('typ_korekty', $data ?? [], null);
        $this->setIfExists('dane_fa_korygowanej', $data ?? [], null);
        $this->setIfExists('okres_fa_korygowanej', $data ?? [], null);
        $this->setIfExists('nr_fa_korygowany', $data ?? [], null);
        $this->setIfExists('podmiot1_k', $data ?? [], null);
        $this->setIfExists('podmiot2_k', $data ?? [], null);
        $this->setIfExists('p_15_zk', $data ?? [], null);
        $this->setIfExists('kurs_waluty_zk', $data ?? [], null);
        $this->setIfExists('zaliczka_czesciowa', $data ?? [], null);
        $this->setIfExists('fp', $data ?? [], null);
        $this->setIfExists('tp', $data ?? [], null);
        $this->setIfExists('dodatkowy_opis', $data ?? [], null);
        $this->setIfExists('faktura_zaliczkowa', $data ?? [], null);
        $this->setIfExists('zwrot_akcyzy', $data ?? [], null);
        $this->setIfExists('fa_wiersz', $data ?? [], null);
        $this->setIfExists('rozliczenie', $data ?? [], null);
        $this->setIfExists('platnosc', $data ?? [], null);
        $this->setIfExists('warunki_transakcji', $data ?? [], null);
        $this->setIfExists('zamowienie', $data ?? [], null);
        $this->setIfExists('p_6', $data ?? [], null);
        $this->setIfExists('p_6_od', $data ?? [], null);
        $this->setIfExists('p_6_do', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['p_1_m']) && (mb_strlen($this->container['p_1_m']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_1_m', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_1_m']) && (mb_strlen($this->container['p_1_m']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_1_m', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_2']) && (mb_strlen($this->container['p_2']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_2', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_2']) && (mb_strlen($this->container['p_2']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_2', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['wz']) && (count($this->container['wz']) > 1000)) {
            $invalidProperties[] = "invalid value for 'wz', number of items must be less than or equal to 1000.";
        }

        if (!is_null($this->container['przyczyna_korekty']) && (mb_strlen($this->container['przyczyna_korekty']) > 256)) {
            $invalidProperties[] = "invalid value for 'przyczyna_korekty', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['przyczyna_korekty']) && (mb_strlen($this->container['przyczyna_korekty']) < 1)) {
            $invalidProperties[] = "invalid value for 'przyczyna_korekty', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['okres_fa_korygowanej']) && (mb_strlen($this->container['okres_fa_korygowanej']) > 256)) {
            $invalidProperties[] = "invalid value for 'okres_fa_korygowanej', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['okres_fa_korygowanej']) && (mb_strlen($this->container['okres_fa_korygowanej']) < 1)) {
            $invalidProperties[] = "invalid value for 'okres_fa_korygowanej', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['nr_fa_korygowany']) && (mb_strlen($this->container['nr_fa_korygowany']) > 256)) {
            $invalidProperties[] = "invalid value for 'nr_fa_korygowany', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['nr_fa_korygowany']) && (mb_strlen($this->container['nr_fa_korygowany']) < 1)) {
            $invalidProperties[] = "invalid value for 'nr_fa_korygowany', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['podmiot2_k']) && (count($this->container['podmiot2_k']) > 101)) {
            $invalidProperties[] = "invalid value for 'podmiot2_k', number of items must be less than or equal to 101.";
        }

        if (!is_null($this->container['zaliczka_czesciowa']) && (count($this->container['zaliczka_czesciowa']) > 31)) {
            $invalidProperties[] = "invalid value for 'zaliczka_czesciowa', number of items must be less than or equal to 31.";
        }

        if (!is_null($this->container['fp']) && ($this->container['fp'] > 1)) {
            $invalidProperties[] = "invalid value for 'fp', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['fp']) && ($this->container['fp'] < 1)) {
            $invalidProperties[] = "invalid value for 'fp', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['tp']) && ($this->container['tp'] > 1)) {
            $invalidProperties[] = "invalid value for 'tp', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['tp']) && ($this->container['tp'] < 1)) {
            $invalidProperties[] = "invalid value for 'tp', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['dodatkowy_opis']) && (count($this->container['dodatkowy_opis']) > 10000)) {
            $invalidProperties[] = "invalid value for 'dodatkowy_opis', number of items must be less than or equal to 10000.";
        }

        if (!is_null($this->container['faktura_zaliczkowa']) && (count($this->container['faktura_zaliczkowa']) > 100)) {
            $invalidProperties[] = "invalid value for 'faktura_zaliczkowa', number of items must be less than or equal to 100.";
        }

        if (!is_null($this->container['zwrot_akcyzy']) && ($this->container['zwrot_akcyzy'] > 1)) {
            $invalidProperties[] = "invalid value for 'zwrot_akcyzy', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['zwrot_akcyzy']) && ($this->container['zwrot_akcyzy'] < 1)) {
            $invalidProperties[] = "invalid value for 'zwrot_akcyzy', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['fa_wiersz']) && (count($this->container['fa_wiersz']) > 10000)) {
            $invalidProperties[] = "invalid value for 'fa_wiersz', number of items must be less than or equal to 10000.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kod_waluty
     *
     * @return \KsefApi\Model\TKodWaluty|null
     */
    public function getKodWaluty()
    {
        return $this->container['kod_waluty'];
    }

    /**
     * Sets kod_waluty
     *
     * @param \KsefApi\Model\TKodWaluty|null $kod_waluty kod_waluty
     *
     * @return self
     */
    public function setKodWaluty($kod_waluty)
    {
        if (is_null($kod_waluty)) {
            throw new \InvalidArgumentException('non-nullable kod_waluty cannot be null');
        }
        $this->container['kod_waluty'] = $kod_waluty;

        return $this;
    }

    /**
     * Gets p_1
     *
     * @return \DateTime|null
     */
    public function getP1()
    {
        return $this->container['p_1'];
    }

    /**
     * Sets p_1
     *
     * @param \DateTime|null $p_1 Data zdarzenia w okresie od 2006-01-01 do 2050-01-01
     *
     * @return self
     */
    public function setP1($p_1)
    {
        if (is_null($p_1)) {
            throw new \InvalidArgumentException('non-nullable p_1 cannot be null');
        }
        $this->container['p_1'] = $p_1;

        return $this;
    }

    /**
     * Gets p_1_m
     *
     * @return string|null
     */
    public function getP1M()
    {
        return $this->container['p_1_m'];
    }

    /**
     * Sets p_1_m
     *
     * @param string|null $p_1_m Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP1M($p_1_m)
    {
        if (is_null($p_1_m)) {
            throw new \InvalidArgumentException('non-nullable p_1_m cannot be null');
        }
        if ((mb_strlen($p_1_m) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_1_m when calling Fa., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_1_m) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_1_m when calling Fa., must be bigger than or equal to 1.');
        }

        $this->container['p_1_m'] = $p_1_m;

        return $this;
    }

    /**
     * Gets p_2
     *
     * @return string|null
     */
    public function getP2()
    {
        return $this->container['p_2'];
    }

    /**
     * Sets p_2
     *
     * @param string|null $p_2 Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP2($p_2)
    {
        if (is_null($p_2)) {
            throw new \InvalidArgumentException('non-nullable p_2 cannot be null');
        }
        if ((mb_strlen($p_2) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_2 when calling Fa., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_2) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_2 when calling Fa., must be bigger than or equal to 1.');
        }

        $this->container['p_2'] = $p_2;

        return $this;
    }

    /**
     * Gets wz
     *
     * @return string[]|null
     */
    public function getWz()
    {
        return $this->container['wz'];
    }

    /**
     * Sets wz
     *
     * @param string[]|null $wz wz
     *
     * @return self
     */
    public function setWz($wz)
    {
        if (is_null($wz)) {
            throw new \InvalidArgumentException('non-nullable wz cannot be null');
        }

        if ((count($wz) > 1000)) {
            throw new \InvalidArgumentException('invalid value for $wz when calling Fa., number of items must be less than or equal to 1000.');
        }
        $this->container['wz'] = $wz;

        return $this;
    }

    /**
     * Gets p_13_1
     *
     * @return float|null
     */
    public function getP131()
    {
        return $this->container['p_13_1'];
    }

    /**
     * Sets p_13_1
     *
     * @param float|null $p_13_1 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP131($p_13_1)
    {
        if (is_null($p_13_1)) {
            throw new \InvalidArgumentException('non-nullable p_13_1 cannot be null');
        }
        $this->container['p_13_1'] = $p_13_1;

        return $this;
    }

    /**
     * Gets p_14_1
     *
     * @return float|null
     */
    public function getP141()
    {
        return $this->container['p_14_1'];
    }

    /**
     * Sets p_14_1
     *
     * @param float|null $p_14_1 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP141($p_14_1)
    {
        if (is_null($p_14_1)) {
            throw new \InvalidArgumentException('non-nullable p_14_1 cannot be null');
        }
        $this->container['p_14_1'] = $p_14_1;

        return $this;
    }

    /**
     * Gets p_14_1_w
     *
     * @return float|null
     */
    public function getP141W()
    {
        return $this->container['p_14_1_w'];
    }

    /**
     * Sets p_14_1_w
     *
     * @param float|null $p_14_1_w Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP141W($p_14_1_w)
    {
        if (is_null($p_14_1_w)) {
            throw new \InvalidArgumentException('non-nullable p_14_1_w cannot be null');
        }
        $this->container['p_14_1_w'] = $p_14_1_w;

        return $this;
    }

    /**
     * Gets p_13_2
     *
     * @return float|null
     */
    public function getP132()
    {
        return $this->container['p_13_2'];
    }

    /**
     * Sets p_13_2
     *
     * @param float|null $p_13_2 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP132($p_13_2)
    {
        if (is_null($p_13_2)) {
            throw new \InvalidArgumentException('non-nullable p_13_2 cannot be null');
        }
        $this->container['p_13_2'] = $p_13_2;

        return $this;
    }

    /**
     * Gets p_14_2
     *
     * @return float|null
     */
    public function getP142()
    {
        return $this->container['p_14_2'];
    }

    /**
     * Sets p_14_2
     *
     * @param float|null $p_14_2 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP142($p_14_2)
    {
        if (is_null($p_14_2)) {
            throw new \InvalidArgumentException('non-nullable p_14_2 cannot be null');
        }
        $this->container['p_14_2'] = $p_14_2;

        return $this;
    }

    /**
     * Gets p_14_2_w
     *
     * @return float|null
     */
    public function getP142W()
    {
        return $this->container['p_14_2_w'];
    }

    /**
     * Sets p_14_2_w
     *
     * @param float|null $p_14_2_w Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP142W($p_14_2_w)
    {
        if (is_null($p_14_2_w)) {
            throw new \InvalidArgumentException('non-nullable p_14_2_w cannot be null');
        }
        $this->container['p_14_2_w'] = $p_14_2_w;

        return $this;
    }

    /**
     * Gets p_13_3
     *
     * @return float|null
     */
    public function getP133()
    {
        return $this->container['p_13_3'];
    }

    /**
     * Sets p_13_3
     *
     * @param float|null $p_13_3 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP133($p_13_3)
    {
        if (is_null($p_13_3)) {
            throw new \InvalidArgumentException('non-nullable p_13_3 cannot be null');
        }
        $this->container['p_13_3'] = $p_13_3;

        return $this;
    }

    /**
     * Gets p_14_3
     *
     * @return float|null
     */
    public function getP143()
    {
        return $this->container['p_14_3'];
    }

    /**
     * Sets p_14_3
     *
     * @param float|null $p_14_3 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP143($p_14_3)
    {
        if (is_null($p_14_3)) {
            throw new \InvalidArgumentException('non-nullable p_14_3 cannot be null');
        }
        $this->container['p_14_3'] = $p_14_3;

        return $this;
    }

    /**
     * Gets p_14_3_w
     *
     * @return float|null
     */
    public function getP143W()
    {
        return $this->container['p_14_3_w'];
    }

    /**
     * Sets p_14_3_w
     *
     * @param float|null $p_14_3_w Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP143W($p_14_3_w)
    {
        if (is_null($p_14_3_w)) {
            throw new \InvalidArgumentException('non-nullable p_14_3_w cannot be null');
        }
        $this->container['p_14_3_w'] = $p_14_3_w;

        return $this;
    }

    /**
     * Gets p_13_4
     *
     * @return float|null
     */
    public function getP134()
    {
        return $this->container['p_13_4'];
    }

    /**
     * Sets p_13_4
     *
     * @param float|null $p_13_4 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP134($p_13_4)
    {
        if (is_null($p_13_4)) {
            throw new \InvalidArgumentException('non-nullable p_13_4 cannot be null');
        }
        $this->container['p_13_4'] = $p_13_4;

        return $this;
    }

    /**
     * Gets p_14_4
     *
     * @return float|null
     */
    public function getP144()
    {
        return $this->container['p_14_4'];
    }

    /**
     * Sets p_14_4
     *
     * @param float|null $p_14_4 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP144($p_14_4)
    {
        if (is_null($p_14_4)) {
            throw new \InvalidArgumentException('non-nullable p_14_4 cannot be null');
        }
        $this->container['p_14_4'] = $p_14_4;

        return $this;
    }

    /**
     * Gets p_14_4_w
     *
     * @return float|null
     */
    public function getP144W()
    {
        return $this->container['p_14_4_w'];
    }

    /**
     * Sets p_14_4_w
     *
     * @param float|null $p_14_4_w Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP144W($p_14_4_w)
    {
        if (is_null($p_14_4_w)) {
            throw new \InvalidArgumentException('non-nullable p_14_4_w cannot be null');
        }
        $this->container['p_14_4_w'] = $p_14_4_w;

        return $this;
    }

    /**
     * Gets p_13_5
     *
     * @return float|null
     */
    public function getP135()
    {
        return $this->container['p_13_5'];
    }

    /**
     * Sets p_13_5
     *
     * @param float|null $p_13_5 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP135($p_13_5)
    {
        if (is_null($p_13_5)) {
            throw new \InvalidArgumentException('non-nullable p_13_5 cannot be null');
        }
        $this->container['p_13_5'] = $p_13_5;

        return $this;
    }

    /**
     * Gets p_14_5
     *
     * @return float|null
     */
    public function getP145()
    {
        return $this->container['p_14_5'];
    }

    /**
     * Sets p_14_5
     *
     * @param float|null $p_14_5 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP145($p_14_5)
    {
        if (is_null($p_14_5)) {
            throw new \InvalidArgumentException('non-nullable p_14_5 cannot be null');
        }
        $this->container['p_14_5'] = $p_14_5;

        return $this;
    }

    /**
     * Gets p_13_6_1
     *
     * @return float|null
     */
    public function getP1361()
    {
        return $this->container['p_13_6_1'];
    }

    /**
     * Sets p_13_6_1
     *
     * @param float|null $p_13_6_1 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP1361($p_13_6_1)
    {
        if (is_null($p_13_6_1)) {
            throw new \InvalidArgumentException('non-nullable p_13_6_1 cannot be null');
        }
        $this->container['p_13_6_1'] = $p_13_6_1;

        return $this;
    }

    /**
     * Gets p_13_6_2
     *
     * @return float|null
     */
    public function getP1362()
    {
        return $this->container['p_13_6_2'];
    }

    /**
     * Sets p_13_6_2
     *
     * @param float|null $p_13_6_2 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP1362($p_13_6_2)
    {
        if (is_null($p_13_6_2)) {
            throw new \InvalidArgumentException('non-nullable p_13_6_2 cannot be null');
        }
        $this->container['p_13_6_2'] = $p_13_6_2;

        return $this;
    }

    /**
     * Gets p_13_6_3
     *
     * @return float|null
     */
    public function getP1363()
    {
        return $this->container['p_13_6_3'];
    }

    /**
     * Sets p_13_6_3
     *
     * @param float|null $p_13_6_3 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP1363($p_13_6_3)
    {
        if (is_null($p_13_6_3)) {
            throw new \InvalidArgumentException('non-nullable p_13_6_3 cannot be null');
        }
        $this->container['p_13_6_3'] = $p_13_6_3;

        return $this;
    }

    /**
     * Gets p_13_7
     *
     * @return float|null
     */
    public function getP137()
    {
        return $this->container['p_13_7'];
    }

    /**
     * Sets p_13_7
     *
     * @param float|null $p_13_7 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP137($p_13_7)
    {
        if (is_null($p_13_7)) {
            throw new \InvalidArgumentException('non-nullable p_13_7 cannot be null');
        }
        $this->container['p_13_7'] = $p_13_7;

        return $this;
    }

    /**
     * Gets p_13_8
     *
     * @return float|null
     */
    public function getP138()
    {
        return $this->container['p_13_8'];
    }

    /**
     * Sets p_13_8
     *
     * @param float|null $p_13_8 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP138($p_13_8)
    {
        if (is_null($p_13_8)) {
            throw new \InvalidArgumentException('non-nullable p_13_8 cannot be null');
        }
        $this->container['p_13_8'] = $p_13_8;

        return $this;
    }

    /**
     * Gets p_13_9
     *
     * @return float|null
     */
    public function getP139()
    {
        return $this->container['p_13_9'];
    }

    /**
     * Sets p_13_9
     *
     * @param float|null $p_13_9 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP139($p_13_9)
    {
        if (is_null($p_13_9)) {
            throw new \InvalidArgumentException('non-nullable p_13_9 cannot be null');
        }
        $this->container['p_13_9'] = $p_13_9;

        return $this;
    }

    /**
     * Gets p_13_10
     *
     * @return float|null
     */
    public function getP1310()
    {
        return $this->container['p_13_10'];
    }

    /**
     * Sets p_13_10
     *
     * @param float|null $p_13_10 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP1310($p_13_10)
    {
        if (is_null($p_13_10)) {
            throw new \InvalidArgumentException('non-nullable p_13_10 cannot be null');
        }
        $this->container['p_13_10'] = $p_13_10;

        return $this;
    }

    /**
     * Gets p_13_11
     *
     * @return float|null
     */
    public function getP1311()
    {
        return $this->container['p_13_11'];
    }

    /**
     * Sets p_13_11
     *
     * @param float|null $p_13_11 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP1311($p_13_11)
    {
        if (is_null($p_13_11)) {
            throw new \InvalidArgumentException('non-nullable p_13_11 cannot be null');
        }
        $this->container['p_13_11'] = $p_13_11;

        return $this;
    }

    /**
     * Gets p_15
     *
     * @return float|null
     */
    public function getP15()
    {
        return $this->container['p_15'];
    }

    /**
     * Sets p_15
     *
     * @param float|null $p_15 Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP15($p_15)
    {
        if (is_null($p_15)) {
            throw new \InvalidArgumentException('non-nullable p_15 cannot be null');
        }
        $this->container['p_15'] = $p_15;

        return $this;
    }

    /**
     * Gets kurs_waluty_z
     *
     * @return float|null
     */
    public function getKursWalutyZ()
    {
        return $this->container['kurs_waluty_z'];
    }

    /**
     * Sets kurs_waluty_z
     *
     * @param float|null $kurs_waluty_z Typ wykorzystywany do określenia ilości. Wartość numeryczna 22 znaki max, w tym 6 po przecinku
     *
     * @return self
     */
    public function setKursWalutyZ($kurs_waluty_z)
    {
        if (is_null($kurs_waluty_z)) {
            throw new \InvalidArgumentException('non-nullable kurs_waluty_z cannot be null');
        }
        $this->container['kurs_waluty_z'] = $kurs_waluty_z;

        return $this;
    }

    /**
     * Gets adnotacje
     *
     * @return \KsefApi\Model\Adnotacje|null
     */
    public function getAdnotacje()
    {
        return $this->container['adnotacje'];
    }

    /**
     * Sets adnotacje
     *
     * @param \KsefApi\Model\Adnotacje|null $adnotacje adnotacje
     *
     * @return self
     */
    public function setAdnotacje($adnotacje)
    {
        if (is_null($adnotacje)) {
            throw new \InvalidArgumentException('non-nullable adnotacje cannot be null');
        }
        $this->container['adnotacje'] = $adnotacje;

        return $this;
    }

    /**
     * Gets rodzaj_faktury
     *
     * @return \KsefApi\Model\TRodzajFaktury|null
     */
    public function getRodzajFaktury()
    {
        return $this->container['rodzaj_faktury'];
    }

    /**
     * Sets rodzaj_faktury
     *
     * @param \KsefApi\Model\TRodzajFaktury|null $rodzaj_faktury rodzaj_faktury
     *
     * @return self
     */
    public function setRodzajFaktury($rodzaj_faktury)
    {
        if (is_null($rodzaj_faktury)) {
            throw new \InvalidArgumentException('non-nullable rodzaj_faktury cannot be null');
        }
        $this->container['rodzaj_faktury'] = $rodzaj_faktury;

        return $this;
    }

    /**
     * Gets przyczyna_korekty
     *
     * @return string|null
     */
    public function getPrzyczynaKorekty()
    {
        return $this->container['przyczyna_korekty'];
    }

    /**
     * Sets przyczyna_korekty
     *
     * @param string|null $przyczyna_korekty Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setPrzyczynaKorekty($przyczyna_korekty)
    {
        if (is_null($przyczyna_korekty)) {
            throw new \InvalidArgumentException('non-nullable przyczyna_korekty cannot be null');
        }
        if ((mb_strlen($przyczyna_korekty) > 256)) {
            throw new \InvalidArgumentException('invalid length for $przyczyna_korekty when calling Fa., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($przyczyna_korekty) < 1)) {
            throw new \InvalidArgumentException('invalid length for $przyczyna_korekty when calling Fa., must be bigger than or equal to 1.');
        }

        $this->container['przyczyna_korekty'] = $przyczyna_korekty;

        return $this;
    }

    /**
     * Gets typ_korekty
     *
     * @return \KsefApi\Model\TTypKorekty|null
     */
    public function getTypKorekty()
    {
        return $this->container['typ_korekty'];
    }

    /**
     * Sets typ_korekty
     *
     * @param \KsefApi\Model\TTypKorekty|null $typ_korekty typ_korekty
     *
     * @return self
     */
    public function setTypKorekty($typ_korekty)
    {
        if (is_null($typ_korekty)) {
            throw new \InvalidArgumentException('non-nullable typ_korekty cannot be null');
        }
        $this->container['typ_korekty'] = $typ_korekty;

        return $this;
    }

    /**
     * Gets dane_fa_korygowanej
     *
     * @return \KsefApi\Model\DaneFaKorygowanej[]|null
     */
    public function getDaneFaKorygowanej()
    {
        return $this->container['dane_fa_korygowanej'];
    }

    /**
     * Sets dane_fa_korygowanej
     *
     * @param \KsefApi\Model\DaneFaKorygowanej[]|null $dane_fa_korygowanej dane_fa_korygowanej
     *
     * @return self
     */
    public function setDaneFaKorygowanej($dane_fa_korygowanej)
    {
        if (is_null($dane_fa_korygowanej)) {
            throw new \InvalidArgumentException('non-nullable dane_fa_korygowanej cannot be null');
        }
        $this->container['dane_fa_korygowanej'] = $dane_fa_korygowanej;

        return $this;
    }

    /**
     * Gets okres_fa_korygowanej
     *
     * @return string|null
     */
    public function getOkresFaKorygowanej()
    {
        return $this->container['okres_fa_korygowanej'];
    }

    /**
     * Sets okres_fa_korygowanej
     *
     * @param string|null $okres_fa_korygowanej Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setOkresFaKorygowanej($okres_fa_korygowanej)
    {
        if (is_null($okres_fa_korygowanej)) {
            throw new \InvalidArgumentException('non-nullable okres_fa_korygowanej cannot be null');
        }
        if ((mb_strlen($okres_fa_korygowanej) > 256)) {
            throw new \InvalidArgumentException('invalid length for $okres_fa_korygowanej when calling Fa., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($okres_fa_korygowanej) < 1)) {
            throw new \InvalidArgumentException('invalid length for $okres_fa_korygowanej when calling Fa., must be bigger than or equal to 1.');
        }

        $this->container['okres_fa_korygowanej'] = $okres_fa_korygowanej;

        return $this;
    }

    /**
     * Gets nr_fa_korygowany
     *
     * @return string|null
     */
    public function getNrFaKorygowany()
    {
        return $this->container['nr_fa_korygowany'];
    }

    /**
     * Sets nr_fa_korygowany
     *
     * @param string|null $nr_fa_korygowany Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setNrFaKorygowany($nr_fa_korygowany)
    {
        if (is_null($nr_fa_korygowany)) {
            throw new \InvalidArgumentException('non-nullable nr_fa_korygowany cannot be null');
        }
        if ((mb_strlen($nr_fa_korygowany) > 256)) {
            throw new \InvalidArgumentException('invalid length for $nr_fa_korygowany when calling Fa., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($nr_fa_korygowany) < 1)) {
            throw new \InvalidArgumentException('invalid length for $nr_fa_korygowany when calling Fa., must be bigger than or equal to 1.');
        }

        $this->container['nr_fa_korygowany'] = $nr_fa_korygowany;

        return $this;
    }

    /**
     * Gets podmiot1_k
     *
     * @return \KsefApi\Model\Podmiot1K|null
     */
    public function getPodmiot1K()
    {
        return $this->container['podmiot1_k'];
    }

    /**
     * Sets podmiot1_k
     *
     * @param \KsefApi\Model\Podmiot1K|null $podmiot1_k podmiot1_k
     *
     * @return self
     */
    public function setPodmiot1K($podmiot1_k)
    {
        if (is_null($podmiot1_k)) {
            throw new \InvalidArgumentException('non-nullable podmiot1_k cannot be null');
        }
        $this->container['podmiot1_k'] = $podmiot1_k;

        return $this;
    }

    /**
     * Gets podmiot2_k
     *
     * @return \KsefApi\Model\Podmiot2K[]|null
     */
    public function getPodmiot2K()
    {
        return $this->container['podmiot2_k'];
    }

    /**
     * Sets podmiot2_k
     *
     * @param \KsefApi\Model\Podmiot2K[]|null $podmiot2_k podmiot2_k
     *
     * @return self
     */
    public function setPodmiot2K($podmiot2_k)
    {
        if (is_null($podmiot2_k)) {
            throw new \InvalidArgumentException('non-nullable podmiot2_k cannot be null');
        }

        if ((count($podmiot2_k) > 101)) {
            throw new \InvalidArgumentException('invalid value for $podmiot2_k when calling Fa., number of items must be less than or equal to 101.');
        }
        $this->container['podmiot2_k'] = $podmiot2_k;

        return $this;
    }

    /**
     * Gets p_15_zk
     *
     * @return float|null
     */
    public function getP15Zk()
    {
        return $this->container['p_15_zk'];
    }

    /**
     * Sets p_15_zk
     *
     * @param float|null $p_15_zk Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP15Zk($p_15_zk)
    {
        if (is_null($p_15_zk)) {
            throw new \InvalidArgumentException('non-nullable p_15_zk cannot be null');
        }
        $this->container['p_15_zk'] = $p_15_zk;

        return $this;
    }

    /**
     * Gets kurs_waluty_zk
     *
     * @return float|null
     */
    public function getKursWalutyZk()
    {
        return $this->container['kurs_waluty_zk'];
    }

    /**
     * Sets kurs_waluty_zk
     *
     * @param float|null $kurs_waluty_zk Typ wykorzystywany do określenia ilości. Wartość numeryczna 22 znaki max, w tym 6 po przecinku
     *
     * @return self
     */
    public function setKursWalutyZk($kurs_waluty_zk)
    {
        if (is_null($kurs_waluty_zk)) {
            throw new \InvalidArgumentException('non-nullable kurs_waluty_zk cannot be null');
        }
        $this->container['kurs_waluty_zk'] = $kurs_waluty_zk;

        return $this;
    }

    /**
     * Gets zaliczka_czesciowa
     *
     * @return \KsefApi\Model\ZaliczkaCzesciowa[]|null
     */
    public function getZaliczkaCzesciowa()
    {
        return $this->container['zaliczka_czesciowa'];
    }

    /**
     * Sets zaliczka_czesciowa
     *
     * @param \KsefApi\Model\ZaliczkaCzesciowa[]|null $zaliczka_czesciowa zaliczka_czesciowa
     *
     * @return self
     */
    public function setZaliczkaCzesciowa($zaliczka_czesciowa)
    {
        if (is_null($zaliczka_czesciowa)) {
            throw new \InvalidArgumentException('non-nullable zaliczka_czesciowa cannot be null');
        }

        if ((count($zaliczka_czesciowa) > 31)) {
            throw new \InvalidArgumentException('invalid value for $zaliczka_czesciowa when calling Fa., number of items must be less than or equal to 31.');
        }
        $this->container['zaliczka_czesciowa'] = $zaliczka_czesciowa;

        return $this;
    }

    /**
     * Gets fp
     *
     * @return int|null
     */
    public function getFp()
    {
        return $this->container['fp'];
    }

    /**
     * Sets fp
     *
     * @param int|null $fp Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setFp($fp)
    {
        if (is_null($fp)) {
            throw new \InvalidArgumentException('non-nullable fp cannot be null');
        }

        if (($fp > 1)) {
            throw new \InvalidArgumentException('invalid value for $fp when calling Fa., must be smaller than or equal to 1.');
        }
        if (($fp < 1)) {
            throw new \InvalidArgumentException('invalid value for $fp when calling Fa., must be bigger than or equal to 1.');
        }

        $this->container['fp'] = $fp;

        return $this;
    }

    /**
     * Gets tp
     *
     * @return int|null
     */
    public function getTp()
    {
        return $this->container['tp'];
    }

    /**
     * Sets tp
     *
     * @param int|null $tp Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setTp($tp)
    {
        if (is_null($tp)) {
            throw new \InvalidArgumentException('non-nullable tp cannot be null');
        }

        if (($tp > 1)) {
            throw new \InvalidArgumentException('invalid value for $tp when calling Fa., must be smaller than or equal to 1.');
        }
        if (($tp < 1)) {
            throw new \InvalidArgumentException('invalid value for $tp when calling Fa., must be bigger than or equal to 1.');
        }

        $this->container['tp'] = $tp;

        return $this;
    }

    /**
     * Gets dodatkowy_opis
     *
     * @return \KsefApi\Model\TKluczWartosc[]|null
     */
    public function getDodatkowyOpis()
    {
        return $this->container['dodatkowy_opis'];
    }

    /**
     * Sets dodatkowy_opis
     *
     * @param \KsefApi\Model\TKluczWartosc[]|null $dodatkowy_opis dodatkowy_opis
     *
     * @return self
     */
    public function setDodatkowyOpis($dodatkowy_opis)
    {
        if (is_null($dodatkowy_opis)) {
            throw new \InvalidArgumentException('non-nullable dodatkowy_opis cannot be null');
        }

        if ((count($dodatkowy_opis) > 10000)) {
            throw new \InvalidArgumentException('invalid value for $dodatkowy_opis when calling Fa., number of items must be less than or equal to 10000.');
        }
        $this->container['dodatkowy_opis'] = $dodatkowy_opis;

        return $this;
    }

    /**
     * Gets faktura_zaliczkowa
     *
     * @return \KsefApi\Model\FakturaZaliczkowa[]|null
     */
    public function getFakturaZaliczkowa()
    {
        return $this->container['faktura_zaliczkowa'];
    }

    /**
     * Sets faktura_zaliczkowa
     *
     * @param \KsefApi\Model\FakturaZaliczkowa[]|null $faktura_zaliczkowa faktura_zaliczkowa
     *
     * @return self
     */
    public function setFakturaZaliczkowa($faktura_zaliczkowa)
    {
        if (is_null($faktura_zaliczkowa)) {
            throw new \InvalidArgumentException('non-nullable faktura_zaliczkowa cannot be null');
        }

        if ((count($faktura_zaliczkowa) > 100)) {
            throw new \InvalidArgumentException('invalid value for $faktura_zaliczkowa when calling Fa., number of items must be less than or equal to 100.');
        }
        $this->container['faktura_zaliczkowa'] = $faktura_zaliczkowa;

        return $this;
    }

    /**
     * Gets zwrot_akcyzy
     *
     * @return int|null
     */
    public function getZwrotAkcyzy()
    {
        return $this->container['zwrot_akcyzy'];
    }

    /**
     * Sets zwrot_akcyzy
     *
     * @param int|null $zwrot_akcyzy Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setZwrotAkcyzy($zwrot_akcyzy)
    {
        if (is_null($zwrot_akcyzy)) {
            throw new \InvalidArgumentException('non-nullable zwrot_akcyzy cannot be null');
        }

        if (($zwrot_akcyzy > 1)) {
            throw new \InvalidArgumentException('invalid value for $zwrot_akcyzy when calling Fa., must be smaller than or equal to 1.');
        }
        if (($zwrot_akcyzy < 1)) {
            throw new \InvalidArgumentException('invalid value for $zwrot_akcyzy when calling Fa., must be bigger than or equal to 1.');
        }

        $this->container['zwrot_akcyzy'] = $zwrot_akcyzy;

        return $this;
    }

    /**
     * Gets fa_wiersz
     *
     * @return \KsefApi\Model\FaWiersz[]|null
     */
    public function getFaWiersz()
    {
        return $this->container['fa_wiersz'];
    }

    /**
     * Sets fa_wiersz
     *
     * @param \KsefApi\Model\FaWiersz[]|null $fa_wiersz fa_wiersz
     *
     * @return self
     */
    public function setFaWiersz($fa_wiersz)
    {
        if (is_null($fa_wiersz)) {
            throw new \InvalidArgumentException('non-nullable fa_wiersz cannot be null');
        }

        if ((count($fa_wiersz) > 10000)) {
            throw new \InvalidArgumentException('invalid value for $fa_wiersz when calling Fa., number of items must be less than or equal to 10000.');
        }
        $this->container['fa_wiersz'] = $fa_wiersz;

        return $this;
    }

    /**
     * Gets rozliczenie
     *
     * @return \KsefApi\Model\Rozliczenie|null
     */
    public function getRozliczenie()
    {
        return $this->container['rozliczenie'];
    }

    /**
     * Sets rozliczenie
     *
     * @param \KsefApi\Model\Rozliczenie|null $rozliczenie rozliczenie
     *
     * @return self
     */
    public function setRozliczenie($rozliczenie)
    {
        if (is_null($rozliczenie)) {
            throw new \InvalidArgumentException('non-nullable rozliczenie cannot be null');
        }
        $this->container['rozliczenie'] = $rozliczenie;

        return $this;
    }

    /**
     * Gets platnosc
     *
     * @return \KsefApi\Model\Platnosc|null
     */
    public function getPlatnosc()
    {
        return $this->container['platnosc'];
    }

    /**
     * Sets platnosc
     *
     * @param \KsefApi\Model\Platnosc|null $platnosc platnosc
     *
     * @return self
     */
    public function setPlatnosc($platnosc)
    {
        if (is_null($platnosc)) {
            throw new \InvalidArgumentException('non-nullable platnosc cannot be null');
        }
        $this->container['platnosc'] = $platnosc;

        return $this;
    }

    /**
     * Gets warunki_transakcji
     *
     * @return \KsefApi\Model\WarunkiTransakcji|null
     */
    public function getWarunkiTransakcji()
    {
        return $this->container['warunki_transakcji'];
    }

    /**
     * Sets warunki_transakcji
     *
     * @param \KsefApi\Model\WarunkiTransakcji|null $warunki_transakcji warunki_transakcji
     *
     * @return self
     */
    public function setWarunkiTransakcji($warunki_transakcji)
    {
        if (is_null($warunki_transakcji)) {
            throw new \InvalidArgumentException('non-nullable warunki_transakcji cannot be null');
        }
        $this->container['warunki_transakcji'] = $warunki_transakcji;

        return $this;
    }

    /**
     * Gets zamowienie
     *
     * @return \KsefApi\Model\Zamowienie|null
     */
    public function getZamowienie()
    {
        return $this->container['zamowienie'];
    }

    /**
     * Sets zamowienie
     *
     * @param \KsefApi\Model\Zamowienie|null $zamowienie zamowienie
     *
     * @return self
     */
    public function setZamowienie($zamowienie)
    {
        if (is_null($zamowienie)) {
            throw new \InvalidArgumentException('non-nullable zamowienie cannot be null');
        }
        $this->container['zamowienie'] = $zamowienie;

        return $this;
    }

    /**
     * Gets p_6
     *
     * @return \DateTime|null
     */
    public function getP6()
    {
        return $this->container['p_6'];
    }

    /**
     * Sets p_6
     *
     * @param \DateTime|null $p_6 Data zdarzenia w okresie od 2006-01-01 do 2050-01-01
     *
     * @return self
     */
    public function setP6($p_6)
    {
        if (is_null($p_6)) {
            throw new \InvalidArgumentException('non-nullable p_6 cannot be null');
        }
        $this->container['p_6'] = $p_6;

        return $this;
    }

    /**
     * Gets p_6_od
     *
     * @return \DateTime|null
     */
    public function getP6Od()
    {
        return $this->container['p_6_od'];
    }

    /**
     * Sets p_6_od
     *
     * @param \DateTime|null $p_6_od Data zdarzenia w okresie od 2006-01-01 do 2050-01-01
     *
     * @return self
     */
    public function setP6Od($p_6_od)
    {
        if (is_null($p_6_od)) {
            throw new \InvalidArgumentException('non-nullable p_6_od cannot be null');
        }
        $this->container['p_6_od'] = $p_6_od;

        return $this;
    }

    /**
     * Gets p_6_do
     *
     * @return \DateTime|null
     */
    public function getP6Do()
    {
        return $this->container['p_6_do'];
    }

    /**
     * Sets p_6_do
     *
     * @param \DateTime|null $p_6_do Data zdarzenia w okresie od 2006-01-01 do 2050-01-01
     *
     * @return self
     */
    public function setP6Do($p_6_do)
    {
        if (is_null($p_6_do)) {
            throw new \InvalidArgumentException('non-nullable p_6_do cannot be null');
        }
        $this->container['p_6_do'] = $p_6_do;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


