<?php
/**
 * Faktura
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * Faktura Class Doc Comment
 *
 * @category Class
 * @description Faktura VAT
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Faktura implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Faktura';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'naglowek' => '\KsefApi\Model\TNaglowek',
        'podmiot1' => '\KsefApi\Model\Podmiot1',
        'podmiot2' => '\KsefApi\Model\Podmiot2',
        'podmiot3' => '\KsefApi\Model\Podmiot3[]',
        'podmiot_upowazniony' => '\KsefApi\Model\PodmiotUpowazniony',
        'fa' => '\KsefApi\Model\Fa',
        'stopka' => '\KsefApi\Model\Stopka',
        'zalacznik' => '\KsefApi\Model\BlokDanych[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'naglowek' => null,
        'podmiot1' => null,
        'podmiot2' => null,
        'podmiot3' => null,
        'podmiot_upowazniony' => null,
        'fa' => null,
        'stopka' => null,
        'zalacznik' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'naglowek' => false,
        'podmiot1' => false,
        'podmiot2' => false,
        'podmiot3' => false,
        'podmiot_upowazniony' => false,
        'fa' => false,
        'stopka' => false,
        'zalacznik' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'naglowek' => 'Naglowek',
        'podmiot1' => 'Podmiot1',
        'podmiot2' => 'Podmiot2',
        'podmiot3' => 'Podmiot3',
        'podmiot_upowazniony' => 'PodmiotUpowazniony',
        'fa' => 'Fa',
        'stopka' => 'Stopka',
        'zalacznik' => 'Zalacznik'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'naglowek' => 'setNaglowek',
        'podmiot1' => 'setPodmiot1',
        'podmiot2' => 'setPodmiot2',
        'podmiot3' => 'setPodmiot3',
        'podmiot_upowazniony' => 'setPodmiotUpowazniony',
        'fa' => 'setFa',
        'stopka' => 'setStopka',
        'zalacznik' => 'setZalacznik'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'naglowek' => 'getNaglowek',
        'podmiot1' => 'getPodmiot1',
        'podmiot2' => 'getPodmiot2',
        'podmiot3' => 'getPodmiot3',
        'podmiot_upowazniony' => 'getPodmiotUpowazniony',
        'fa' => 'getFa',
        'stopka' => 'getStopka',
        'zalacznik' => 'getZalacznik'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('naglowek', $data ?? [], null);
        $this->setIfExists('podmiot1', $data ?? [], null);
        $this->setIfExists('podmiot2', $data ?? [], null);
        $this->setIfExists('podmiot3', $data ?? [], null);
        $this->setIfExists('podmiot_upowazniony', $data ?? [], null);
        $this->setIfExists('fa', $data ?? [], null);
        $this->setIfExists('stopka', $data ?? [], null);
        $this->setIfExists('zalacznik', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['podmiot3']) && (count($this->container['podmiot3']) > 100)) {
            $invalidProperties[] = "invalid value for 'podmiot3', number of items must be less than or equal to 100.";
        }

        if (!is_null($this->container['zalacznik']) && (count($this->container['zalacznik']) > 1000)) {
            $invalidProperties[] = "invalid value for 'zalacznik', number of items must be less than or equal to 1000.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets naglowek
     *
     * @return \KsefApi\Model\TNaglowek|null
     */
    public function getNaglowek()
    {
        return $this->container['naglowek'];
    }

    /**
     * Sets naglowek
     *
     * @param \KsefApi\Model\TNaglowek|null $naglowek naglowek
     *
     * @return self
     */
    public function setNaglowek($naglowek)
    {
        if (is_null($naglowek)) {
            throw new \InvalidArgumentException('non-nullable naglowek cannot be null');
        }
        $this->container['naglowek'] = $naglowek;

        return $this;
    }

    /**
     * Gets podmiot1
     *
     * @return \KsefApi\Model\Podmiot1|null
     */
    public function getPodmiot1()
    {
        return $this->container['podmiot1'];
    }

    /**
     * Sets podmiot1
     *
     * @param \KsefApi\Model\Podmiot1|null $podmiot1 podmiot1
     *
     * @return self
     */
    public function setPodmiot1($podmiot1)
    {
        if (is_null($podmiot1)) {
            throw new \InvalidArgumentException('non-nullable podmiot1 cannot be null');
        }
        $this->container['podmiot1'] = $podmiot1;

        return $this;
    }

    /**
     * Gets podmiot2
     *
     * @return \KsefApi\Model\Podmiot2|null
     */
    public function getPodmiot2()
    {
        return $this->container['podmiot2'];
    }

    /**
     * Sets podmiot2
     *
     * @param \KsefApi\Model\Podmiot2|null $podmiot2 podmiot2
     *
     * @return self
     */
    public function setPodmiot2($podmiot2)
    {
        if (is_null($podmiot2)) {
            throw new \InvalidArgumentException('non-nullable podmiot2 cannot be null');
        }
        $this->container['podmiot2'] = $podmiot2;

        return $this;
    }

    /**
     * Gets podmiot3
     *
     * @return \KsefApi\Model\Podmiot3[]|null
     */
    public function getPodmiot3()
    {
        return $this->container['podmiot3'];
    }

    /**
     * Sets podmiot3
     *
     * @param \KsefApi\Model\Podmiot3[]|null $podmiot3 podmiot3
     *
     * @return self
     */
    public function setPodmiot3($podmiot3)
    {
        if (is_null($podmiot3)) {
            throw new \InvalidArgumentException('non-nullable podmiot3 cannot be null');
        }

        if ((count($podmiot3) > 100)) {
            throw new \InvalidArgumentException('invalid value for $podmiot3 when calling Faktura., number of items must be less than or equal to 100.');
        }
        $this->container['podmiot3'] = $podmiot3;

        return $this;
    }

    /**
     * Gets podmiot_upowazniony
     *
     * @return \KsefApi\Model\PodmiotUpowazniony|null
     */
    public function getPodmiotUpowazniony()
    {
        return $this->container['podmiot_upowazniony'];
    }

    /**
     * Sets podmiot_upowazniony
     *
     * @param \KsefApi\Model\PodmiotUpowazniony|null $podmiot_upowazniony podmiot_upowazniony
     *
     * @return self
     */
    public function setPodmiotUpowazniony($podmiot_upowazniony)
    {
        if (is_null($podmiot_upowazniony)) {
            throw new \InvalidArgumentException('non-nullable podmiot_upowazniony cannot be null');
        }
        $this->container['podmiot_upowazniony'] = $podmiot_upowazniony;

        return $this;
    }

    /**
     * Gets fa
     *
     * @return \KsefApi\Model\Fa|null
     */
    public function getFa()
    {
        return $this->container['fa'];
    }

    /**
     * Sets fa
     *
     * @param \KsefApi\Model\Fa|null $fa fa
     *
     * @return self
     */
    public function setFa($fa)
    {
        if (is_null($fa)) {
            throw new \InvalidArgumentException('non-nullable fa cannot be null');
        }
        $this->container['fa'] = $fa;

        return $this;
    }

    /**
     * Gets stopka
     *
     * @return \KsefApi\Model\Stopka|null
     */
    public function getStopka()
    {
        return $this->container['stopka'];
    }

    /**
     * Sets stopka
     *
     * @param \KsefApi\Model\Stopka|null $stopka stopka
     *
     * @return self
     */
    public function setStopka($stopka)
    {
        if (is_null($stopka)) {
            throw new \InvalidArgumentException('non-nullable stopka cannot be null');
        }
        $this->container['stopka'] = $stopka;

        return $this;
    }

    /**
     * Gets zalacznik
     *
     * @return \KsefApi\Model\BlokDanych[]|null
     */
    public function getZalacznik()
    {
        return $this->container['zalacznik'];
    }

    /**
     * Sets zalacznik
     *
     * @param \KsefApi\Model\BlokDanych[]|null $zalacznik zalacznik
     *
     * @return self
     */
    public function setZalacznik($zalacznik)
    {
        if (is_null($zalacznik)) {
            throw new \InvalidArgumentException('non-nullable zalacznik cannot be null');
        }

        if ((count($zalacznik) > 1000)) {
            throw new \InvalidArgumentException('invalid value for $zalacznik when calling Faktura., number of items must be less than or equal to 1000.');
        }
        $this->container['zalacznik'] = $zalacznik;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


