<?php
/**
 * NoweSrodkiTransportu
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * NoweSrodkiTransportu Class Doc Comment
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoweSrodkiTransportu implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoweSrodkiTransportu';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'p_22' => 'int',
        'p_42_5' => 'int',
        'nowy_srodek_transportu' => '\KsefApi\Model\NowySrodekTransportu[]',
        'p_22_n' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'p_22' => 'int32',
        'p_42_5' => 'int32',
        'nowy_srodek_transportu' => null,
        'p_22_n' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'p_22' => false,
        'p_42_5' => false,
        'nowy_srodek_transportu' => false,
        'p_22_n' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'p_22' => 'P_22',
        'p_42_5' => 'P_42_5',
        'nowy_srodek_transportu' => 'NowySrodekTransportu',
        'p_22_n' => 'P_22N'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'p_22' => 'setP22',
        'p_42_5' => 'setP425',
        'nowy_srodek_transportu' => 'setNowySrodekTransportu',
        'p_22_n' => 'setP22N'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'p_22' => 'getP22',
        'p_42_5' => 'getP425',
        'nowy_srodek_transportu' => 'getNowySrodekTransportu',
        'p_22_n' => 'getP22N'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('p_22', $data ?? [], null);
        $this->setIfExists('p_42_5', $data ?? [], null);
        $this->setIfExists('nowy_srodek_transportu', $data ?? [], null);
        $this->setIfExists('p_22_n', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['p_22']) && ($this->container['p_22'] > 1)) {
            $invalidProperties[] = "invalid value for 'p_22', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['p_22']) && ($this->container['p_22'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_22', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_42_5']) && ($this->container['p_42_5'] > 2)) {
            $invalidProperties[] = "invalid value for 'p_42_5', must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['p_42_5']) && ($this->container['p_42_5'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_42_5', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['nowy_srodek_transportu']) && (count($this->container['nowy_srodek_transportu']) > 10000)) {
            $invalidProperties[] = "invalid value for 'nowy_srodek_transportu', number of items must be less than or equal to 10000.";
        }

        if (!is_null($this->container['p_22_n']) && ($this->container['p_22_n'] > 1)) {
            $invalidProperties[] = "invalid value for 'p_22_n', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['p_22_n']) && ($this->container['p_22_n'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_22_n', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets p_22
     *
     * @return int|null
     */
    public function getP22()
    {
        return $this->container['p_22'];
    }

    /**
     * Sets p_22
     *
     * @param int|null $p_22 Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setP22($p_22)
    {
        if (is_null($p_22)) {
            throw new \InvalidArgumentException('non-nullable p_22 cannot be null');
        }

        if (($p_22 > 1)) {
            throw new \InvalidArgumentException('invalid value for $p_22 when calling NoweSrodkiTransportu., must be smaller than or equal to 1.');
        }
        if (($p_22 < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_22 when calling NoweSrodkiTransportu., must be bigger than or equal to 1.');
        }

        $this->container['p_22'] = $p_22;

        return $this;
    }

    /**
     * Gets p_42_5
     *
     * @return int|null
     */
    public function getP425()
    {
        return $this->container['p_42_5'];
    }

    /**
     * Sets p_42_5
     *
     * @param int|null $p_42_5 Podwójne pole wyboru
     *
     * @return self
     */
    public function setP425($p_42_5)
    {
        if (is_null($p_42_5)) {
            throw new \InvalidArgumentException('non-nullable p_42_5 cannot be null');
        }

        if (($p_42_5 > 2)) {
            throw new \InvalidArgumentException('invalid value for $p_42_5 when calling NoweSrodkiTransportu., must be smaller than or equal to 2.');
        }
        if (($p_42_5 < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_42_5 when calling NoweSrodkiTransportu., must be bigger than or equal to 1.');
        }

        $this->container['p_42_5'] = $p_42_5;

        return $this;
    }

    /**
     * Gets nowy_srodek_transportu
     *
     * @return \KsefApi\Model\NowySrodekTransportu[]|null
     */
    public function getNowySrodekTransportu()
    {
        return $this->container['nowy_srodek_transportu'];
    }

    /**
     * Sets nowy_srodek_transportu
     *
     * @param \KsefApi\Model\NowySrodekTransportu[]|null $nowy_srodek_transportu nowy_srodek_transportu
     *
     * @return self
     */
    public function setNowySrodekTransportu($nowy_srodek_transportu)
    {
        if (is_null($nowy_srodek_transportu)) {
            throw new \InvalidArgumentException('non-nullable nowy_srodek_transportu cannot be null');
        }

        if ((count($nowy_srodek_transportu) > 10000)) {
            throw new \InvalidArgumentException('invalid value for $nowy_srodek_transportu when calling NoweSrodkiTransportu., number of items must be less than or equal to 10000.');
        }
        $this->container['nowy_srodek_transportu'] = $nowy_srodek_transportu;

        return $this;
    }

    /**
     * Gets p_22_n
     *
     * @return int|null
     */
    public function getP22N()
    {
        return $this->container['p_22_n'];
    }

    /**
     * Sets p_22_n
     *
     * @param int|null $p_22_n Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setP22N($p_22_n)
    {
        if (is_null($p_22_n)) {
            throw new \InvalidArgumentException('non-nullable p_22_n cannot be null');
        }

        if (($p_22_n > 1)) {
            throw new \InvalidArgumentException('invalid value for $p_22_n when calling NoweSrodkiTransportu., must be smaller than or equal to 1.');
        }
        if (($p_22_n < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_22_n when calling NoweSrodkiTransportu., must be bigger than or equal to 1.');
        }

        $this->container['p_22_n'] = $p_22_n;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


