<?php
/**
 * NowySrodekTransportuB
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * NowySrodekTransportuB Class Doc Comment
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NowySrodekTransportuB implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NowySrodekTransportuB';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'p_22_b' => 'string',
        'p_22_b1' => 'string',
        'p_22_b2' => 'string',
        'p_22_b3' => 'string',
        'p_22_b4' => 'string',
        'p_22_bt' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'p_22_b' => null,
        'p_22_b1' => null,
        'p_22_b2' => null,
        'p_22_b3' => null,
        'p_22_b4' => null,
        'p_22_bt' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'p_22_b' => false,
        'p_22_b1' => false,
        'p_22_b2' => false,
        'p_22_b3' => false,
        'p_22_b4' => false,
        'p_22_bt' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'p_22_b' => 'P_22B',
        'p_22_b1' => 'P_22B1',
        'p_22_b2' => 'P_22B2',
        'p_22_b3' => 'P_22B3',
        'p_22_b4' => 'P_22B4',
        'p_22_bt' => 'P_22BT'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'p_22_b' => 'setP22B',
        'p_22_b1' => 'setP22B1',
        'p_22_b2' => 'setP22B2',
        'p_22_b3' => 'setP22B3',
        'p_22_b4' => 'setP22B4',
        'p_22_bt' => 'setP22Bt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'p_22_b' => 'getP22B',
        'p_22_b1' => 'getP22B1',
        'p_22_b2' => 'getP22B2',
        'p_22_b3' => 'getP22B3',
        'p_22_b4' => 'getP22B4',
        'p_22_bt' => 'getP22Bt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('p_22_b', $data ?? [], null);
        $this->setIfExists('p_22_b1', $data ?? [], null);
        $this->setIfExists('p_22_b2', $data ?? [], null);
        $this->setIfExists('p_22_b3', $data ?? [], null);
        $this->setIfExists('p_22_b4', $data ?? [], null);
        $this->setIfExists('p_22_bt', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['p_22_b']) && (mb_strlen($this->container['p_22_b']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_22_b', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_22_b']) && (mb_strlen($this->container['p_22_b']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_22_b', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_22_b1']) && (mb_strlen($this->container['p_22_b1']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_22_b1', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_22_b1']) && (mb_strlen($this->container['p_22_b1']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_22_b1', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_22_b2']) && (mb_strlen($this->container['p_22_b2']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_22_b2', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_22_b2']) && (mb_strlen($this->container['p_22_b2']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_22_b2', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_22_b3']) && (mb_strlen($this->container['p_22_b3']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_22_b3', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_22_b3']) && (mb_strlen($this->container['p_22_b3']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_22_b3', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_22_b4']) && (mb_strlen($this->container['p_22_b4']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_22_b4', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_22_b4']) && (mb_strlen($this->container['p_22_b4']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_22_b4', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_22_bt']) && (mb_strlen($this->container['p_22_bt']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_22_bt', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_22_bt']) && (mb_strlen($this->container['p_22_bt']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_22_bt', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets p_22_b
     *
     * @return string|null
     */
    public function getP22B()
    {
        return $this->container['p_22_b'];
    }

    /**
     * Sets p_22_b
     *
     * @param string|null $p_22_b Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP22B($p_22_b)
    {
        if (is_null($p_22_b)) {
            throw new \InvalidArgumentException('non-nullable p_22_b cannot be null');
        }
        if ((mb_strlen($p_22_b) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b when calling NowySrodekTransportuB., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_22_b) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b when calling NowySrodekTransportuB., must be bigger than or equal to 1.');
        }

        $this->container['p_22_b'] = $p_22_b;

        return $this;
    }

    /**
     * Gets p_22_b1
     *
     * @return string|null
     */
    public function getP22B1()
    {
        return $this->container['p_22_b1'];
    }

    /**
     * Sets p_22_b1
     *
     * @param string|null $p_22_b1 Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP22B1($p_22_b1)
    {
        if (is_null($p_22_b1)) {
            throw new \InvalidArgumentException('non-nullable p_22_b1 cannot be null');
        }
        if ((mb_strlen($p_22_b1) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b1 when calling NowySrodekTransportuB., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_22_b1) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b1 when calling NowySrodekTransportuB., must be bigger than or equal to 1.');
        }

        $this->container['p_22_b1'] = $p_22_b1;

        return $this;
    }

    /**
     * Gets p_22_b2
     *
     * @return string|null
     */
    public function getP22B2()
    {
        return $this->container['p_22_b2'];
    }

    /**
     * Sets p_22_b2
     *
     * @param string|null $p_22_b2 Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP22B2($p_22_b2)
    {
        if (is_null($p_22_b2)) {
            throw new \InvalidArgumentException('non-nullable p_22_b2 cannot be null');
        }
        if ((mb_strlen($p_22_b2) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b2 when calling NowySrodekTransportuB., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_22_b2) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b2 when calling NowySrodekTransportuB., must be bigger than or equal to 1.');
        }

        $this->container['p_22_b2'] = $p_22_b2;

        return $this;
    }

    /**
     * Gets p_22_b3
     *
     * @return string|null
     */
    public function getP22B3()
    {
        return $this->container['p_22_b3'];
    }

    /**
     * Sets p_22_b3
     *
     * @param string|null $p_22_b3 Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP22B3($p_22_b3)
    {
        if (is_null($p_22_b3)) {
            throw new \InvalidArgumentException('non-nullable p_22_b3 cannot be null');
        }
        if ((mb_strlen($p_22_b3) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b3 when calling NowySrodekTransportuB., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_22_b3) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b3 when calling NowySrodekTransportuB., must be bigger than or equal to 1.');
        }

        $this->container['p_22_b3'] = $p_22_b3;

        return $this;
    }

    /**
     * Gets p_22_b4
     *
     * @return string|null
     */
    public function getP22B4()
    {
        return $this->container['p_22_b4'];
    }

    /**
     * Sets p_22_b4
     *
     * @param string|null $p_22_b4 Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP22B4($p_22_b4)
    {
        if (is_null($p_22_b4)) {
            throw new \InvalidArgumentException('non-nullable p_22_b4 cannot be null');
        }
        if ((mb_strlen($p_22_b4) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b4 when calling NowySrodekTransportuB., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_22_b4) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_22_b4 when calling NowySrodekTransportuB., must be bigger than or equal to 1.');
        }

        $this->container['p_22_b4'] = $p_22_b4;

        return $this;
    }

    /**
     * Gets p_22_bt
     *
     * @return string|null
     */
    public function getP22Bt()
    {
        return $this->container['p_22_bt'];
    }

    /**
     * Sets p_22_bt
     *
     * @param string|null $p_22_bt Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP22Bt($p_22_bt)
    {
        if (is_null($p_22_bt)) {
            throw new \InvalidArgumentException('non-nullable p_22_bt cannot be null');
        }
        if ((mb_strlen($p_22_bt) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_22_bt when calling NowySrodekTransportuB., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_22_bt) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_22_bt when calling NowySrodekTransportuB., must be bigger than or equal to 1.');
        }

        $this->container['p_22_bt'] = $p_22_bt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


