<?php
/**
 * Platnosc
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * Platnosc Class Doc Comment
 *
 * @category Class
 * @description Warunki płatności
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Platnosc implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Platnosc';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'zaplacono' => 'int',
        'data_zaplaty' => '\DateTime',
        'znacznik_zaplaty_czesciowej' => 'int',
        'zaplata_czesciowa' => '\KsefApi\Model\ZaplataCzesciowa[]',
        'termin_platnosci' => '\KsefApi\Model\TerminPlatnosci[]',
        'forma_platnosci' => '\KsefApi\Model\TFormaPlatnosci',
        'platnosc_inna' => 'int',
        'opis_platnosci' => 'string',
        'rachunek_bankowy' => '\KsefApi\Model\TRachunekBankowy[]',
        'rachunek_bankowy_faktora' => '\KsefApi\Model\TRachunekBankowy[]',
        'skonto' => '\KsefApi\Model\Skonto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'zaplacono' => 'int32',
        'data_zaplaty' => 'date',
        'znacznik_zaplaty_czesciowej' => 'int32',
        'zaplata_czesciowa' => null,
        'termin_platnosci' => null,
        'forma_platnosci' => null,
        'platnosc_inna' => 'int32',
        'opis_platnosci' => null,
        'rachunek_bankowy' => null,
        'rachunek_bankowy_faktora' => null,
        'skonto' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'zaplacono' => false,
        'data_zaplaty' => false,
        'znacznik_zaplaty_czesciowej' => false,
        'zaplata_czesciowa' => false,
        'termin_platnosci' => false,
        'forma_platnosci' => false,
        'platnosc_inna' => false,
        'opis_platnosci' => false,
        'rachunek_bankowy' => false,
        'rachunek_bankowy_faktora' => false,
        'skonto' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'zaplacono' => 'Zaplacono',
        'data_zaplaty' => 'DataZaplaty',
        'znacznik_zaplaty_czesciowej' => 'ZnacznikZaplatyCzesciowej',
        'zaplata_czesciowa' => 'ZaplataCzesciowa',
        'termin_platnosci' => 'TerminPlatnosci',
        'forma_platnosci' => 'FormaPlatnosci',
        'platnosc_inna' => 'PlatnoscInna',
        'opis_platnosci' => 'OpisPlatnosci',
        'rachunek_bankowy' => 'RachunekBankowy',
        'rachunek_bankowy_faktora' => 'RachunekBankowyFaktora',
        'skonto' => 'Skonto'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'zaplacono' => 'setZaplacono',
        'data_zaplaty' => 'setDataZaplaty',
        'znacznik_zaplaty_czesciowej' => 'setZnacznikZaplatyCzesciowej',
        'zaplata_czesciowa' => 'setZaplataCzesciowa',
        'termin_platnosci' => 'setTerminPlatnosci',
        'forma_platnosci' => 'setFormaPlatnosci',
        'platnosc_inna' => 'setPlatnoscInna',
        'opis_platnosci' => 'setOpisPlatnosci',
        'rachunek_bankowy' => 'setRachunekBankowy',
        'rachunek_bankowy_faktora' => 'setRachunekBankowyFaktora',
        'skonto' => 'setSkonto'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'zaplacono' => 'getZaplacono',
        'data_zaplaty' => 'getDataZaplaty',
        'znacznik_zaplaty_czesciowej' => 'getZnacznikZaplatyCzesciowej',
        'zaplata_czesciowa' => 'getZaplataCzesciowa',
        'termin_platnosci' => 'getTerminPlatnosci',
        'forma_platnosci' => 'getFormaPlatnosci',
        'platnosc_inna' => 'getPlatnoscInna',
        'opis_platnosci' => 'getOpisPlatnosci',
        'rachunek_bankowy' => 'getRachunekBankowy',
        'rachunek_bankowy_faktora' => 'getRachunekBankowyFaktora',
        'skonto' => 'getSkonto'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('zaplacono', $data ?? [], null);
        $this->setIfExists('data_zaplaty', $data ?? [], null);
        $this->setIfExists('znacznik_zaplaty_czesciowej', $data ?? [], null);
        $this->setIfExists('zaplata_czesciowa', $data ?? [], null);
        $this->setIfExists('termin_platnosci', $data ?? [], null);
        $this->setIfExists('forma_platnosci', $data ?? [], null);
        $this->setIfExists('platnosc_inna', $data ?? [], null);
        $this->setIfExists('opis_platnosci', $data ?? [], null);
        $this->setIfExists('rachunek_bankowy', $data ?? [], null);
        $this->setIfExists('rachunek_bankowy_faktora', $data ?? [], null);
        $this->setIfExists('skonto', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['zaplacono']) && ($this->container['zaplacono'] > 1)) {
            $invalidProperties[] = "invalid value for 'zaplacono', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['zaplacono']) && ($this->container['zaplacono'] < 1)) {
            $invalidProperties[] = "invalid value for 'zaplacono', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['znacznik_zaplaty_czesciowej']) && ($this->container['znacznik_zaplaty_czesciowej'] > 1)) {
            $invalidProperties[] = "invalid value for 'znacznik_zaplaty_czesciowej', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['znacznik_zaplaty_czesciowej']) && ($this->container['znacznik_zaplaty_czesciowej'] < 1)) {
            $invalidProperties[] = "invalid value for 'znacznik_zaplaty_czesciowej', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['zaplata_czesciowa']) && (count($this->container['zaplata_czesciowa']) > 100)) {
            $invalidProperties[] = "invalid value for 'zaplata_czesciowa', number of items must be less than or equal to 100.";
        }

        if (!is_null($this->container['termin_platnosci']) && (count($this->container['termin_platnosci']) > 100)) {
            $invalidProperties[] = "invalid value for 'termin_platnosci', number of items must be less than or equal to 100.";
        }

        if (!is_null($this->container['platnosc_inna']) && ($this->container['platnosc_inna'] > 1)) {
            $invalidProperties[] = "invalid value for 'platnosc_inna', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['platnosc_inna']) && ($this->container['platnosc_inna'] < 1)) {
            $invalidProperties[] = "invalid value for 'platnosc_inna', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['opis_platnosci']) && (mb_strlen($this->container['opis_platnosci']) > 256)) {
            $invalidProperties[] = "invalid value for 'opis_platnosci', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['opis_platnosci']) && (mb_strlen($this->container['opis_platnosci']) < 1)) {
            $invalidProperties[] = "invalid value for 'opis_platnosci', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['rachunek_bankowy']) && (count($this->container['rachunek_bankowy']) > 100)) {
            $invalidProperties[] = "invalid value for 'rachunek_bankowy', number of items must be less than or equal to 100.";
        }

        if (!is_null($this->container['rachunek_bankowy_faktora']) && (count($this->container['rachunek_bankowy_faktora']) > 20)) {
            $invalidProperties[] = "invalid value for 'rachunek_bankowy_faktora', number of items must be less than or equal to 20.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets zaplacono
     *
     * @return int|null
     */
    public function getZaplacono()
    {
        return $this->container['zaplacono'];
    }

    /**
     * Sets zaplacono
     *
     * @param int|null $zaplacono Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setZaplacono($zaplacono)
    {
        if (is_null($zaplacono)) {
            throw new \InvalidArgumentException('non-nullable zaplacono cannot be null');
        }

        if (($zaplacono > 1)) {
            throw new \InvalidArgumentException('invalid value for $zaplacono when calling Platnosc., must be smaller than or equal to 1.');
        }
        if (($zaplacono < 1)) {
            throw new \InvalidArgumentException('invalid value for $zaplacono when calling Platnosc., must be bigger than or equal to 1.');
        }

        $this->container['zaplacono'] = $zaplacono;

        return $this;
    }

    /**
     * Gets data_zaplaty
     *
     * @return \DateTime|null
     */
    public function getDataZaplaty()
    {
        return $this->container['data_zaplaty'];
    }

    /**
     * Sets data_zaplaty
     *
     * @param \DateTime|null $data_zaplaty Data zdarzenia w okresie od 2016-07-01 do 2050-01-01
     *
     * @return self
     */
    public function setDataZaplaty($data_zaplaty)
    {
        if (is_null($data_zaplaty)) {
            throw new \InvalidArgumentException('non-nullable data_zaplaty cannot be null');
        }
        $this->container['data_zaplaty'] = $data_zaplaty;

        return $this;
    }

    /**
     * Gets znacznik_zaplaty_czesciowej
     *
     * @return int|null
     */
    public function getZnacznikZaplatyCzesciowej()
    {
        return $this->container['znacznik_zaplaty_czesciowej'];
    }

    /**
     * Sets znacznik_zaplaty_czesciowej
     *
     * @param int|null $znacznik_zaplaty_czesciowej Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setZnacznikZaplatyCzesciowej($znacznik_zaplaty_czesciowej)
    {
        if (is_null($znacznik_zaplaty_czesciowej)) {
            throw new \InvalidArgumentException('non-nullable znacznik_zaplaty_czesciowej cannot be null');
        }

        if (($znacznik_zaplaty_czesciowej > 1)) {
            throw new \InvalidArgumentException('invalid value for $znacznik_zaplaty_czesciowej when calling Platnosc., must be smaller than or equal to 1.');
        }
        if (($znacznik_zaplaty_czesciowej < 1)) {
            throw new \InvalidArgumentException('invalid value for $znacznik_zaplaty_czesciowej when calling Platnosc., must be bigger than or equal to 1.');
        }

        $this->container['znacznik_zaplaty_czesciowej'] = $znacznik_zaplaty_czesciowej;

        return $this;
    }

    /**
     * Gets zaplata_czesciowa
     *
     * @return \KsefApi\Model\ZaplataCzesciowa[]|null
     */
    public function getZaplataCzesciowa()
    {
        return $this->container['zaplata_czesciowa'];
    }

    /**
     * Sets zaplata_czesciowa
     *
     * @param \KsefApi\Model\ZaplataCzesciowa[]|null $zaplata_czesciowa zaplata_czesciowa
     *
     * @return self
     */
    public function setZaplataCzesciowa($zaplata_czesciowa)
    {
        if (is_null($zaplata_czesciowa)) {
            throw new \InvalidArgumentException('non-nullable zaplata_czesciowa cannot be null');
        }

        if ((count($zaplata_czesciowa) > 100)) {
            throw new \InvalidArgumentException('invalid value for $zaplata_czesciowa when calling Platnosc., number of items must be less than or equal to 100.');
        }
        $this->container['zaplata_czesciowa'] = $zaplata_czesciowa;

        return $this;
    }

    /**
     * Gets termin_platnosci
     *
     * @return \KsefApi\Model\TerminPlatnosci[]|null
     */
    public function getTerminPlatnosci()
    {
        return $this->container['termin_platnosci'];
    }

    /**
     * Sets termin_platnosci
     *
     * @param \KsefApi\Model\TerminPlatnosci[]|null $termin_platnosci termin_platnosci
     *
     * @return self
     */
    public function setTerminPlatnosci($termin_platnosci)
    {
        if (is_null($termin_platnosci)) {
            throw new \InvalidArgumentException('non-nullable termin_platnosci cannot be null');
        }

        if ((count($termin_platnosci) > 100)) {
            throw new \InvalidArgumentException('invalid value for $termin_platnosci when calling Platnosc., number of items must be less than or equal to 100.');
        }
        $this->container['termin_platnosci'] = $termin_platnosci;

        return $this;
    }

    /**
     * Gets forma_platnosci
     *
     * @return \KsefApi\Model\TFormaPlatnosci|null
     */
    public function getFormaPlatnosci()
    {
        return $this->container['forma_platnosci'];
    }

    /**
     * Sets forma_platnosci
     *
     * @param \KsefApi\Model\TFormaPlatnosci|null $forma_platnosci forma_platnosci
     *
     * @return self
     */
    public function setFormaPlatnosci($forma_platnosci)
    {
        if (is_null($forma_platnosci)) {
            throw new \InvalidArgumentException('non-nullable forma_platnosci cannot be null');
        }
        $this->container['forma_platnosci'] = $forma_platnosci;

        return $this;
    }

    /**
     * Gets platnosc_inna
     *
     * @return int|null
     */
    public function getPlatnoscInna()
    {
        return $this->container['platnosc_inna'];
    }

    /**
     * Sets platnosc_inna
     *
     * @param int|null $platnosc_inna Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setPlatnoscInna($platnosc_inna)
    {
        if (is_null($platnosc_inna)) {
            throw new \InvalidArgumentException('non-nullable platnosc_inna cannot be null');
        }

        if (($platnosc_inna > 1)) {
            throw new \InvalidArgumentException('invalid value for $platnosc_inna when calling Platnosc., must be smaller than or equal to 1.');
        }
        if (($platnosc_inna < 1)) {
            throw new \InvalidArgumentException('invalid value for $platnosc_inna when calling Platnosc., must be bigger than or equal to 1.');
        }

        $this->container['platnosc_inna'] = $platnosc_inna;

        return $this;
    }

    /**
     * Gets opis_platnosci
     *
     * @return string|null
     */
    public function getOpisPlatnosci()
    {
        return $this->container['opis_platnosci'];
    }

    /**
     * Sets opis_platnosci
     *
     * @param string|null $opis_platnosci Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setOpisPlatnosci($opis_platnosci)
    {
        if (is_null($opis_platnosci)) {
            throw new \InvalidArgumentException('non-nullable opis_platnosci cannot be null');
        }
        if ((mb_strlen($opis_platnosci) > 256)) {
            throw new \InvalidArgumentException('invalid length for $opis_platnosci when calling Platnosc., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($opis_platnosci) < 1)) {
            throw new \InvalidArgumentException('invalid length for $opis_platnosci when calling Platnosc., must be bigger than or equal to 1.');
        }

        $this->container['opis_platnosci'] = $opis_platnosci;

        return $this;
    }

    /**
     * Gets rachunek_bankowy
     *
     * @return \KsefApi\Model\TRachunekBankowy[]|null
     */
    public function getRachunekBankowy()
    {
        return $this->container['rachunek_bankowy'];
    }

    /**
     * Sets rachunek_bankowy
     *
     * @param \KsefApi\Model\TRachunekBankowy[]|null $rachunek_bankowy rachunek_bankowy
     *
     * @return self
     */
    public function setRachunekBankowy($rachunek_bankowy)
    {
        if (is_null($rachunek_bankowy)) {
            throw new \InvalidArgumentException('non-nullable rachunek_bankowy cannot be null');
        }

        if ((count($rachunek_bankowy) > 100)) {
            throw new \InvalidArgumentException('invalid value for $rachunek_bankowy when calling Platnosc., number of items must be less than or equal to 100.');
        }
        $this->container['rachunek_bankowy'] = $rachunek_bankowy;

        return $this;
    }

    /**
     * Gets rachunek_bankowy_faktora
     *
     * @return \KsefApi\Model\TRachunekBankowy[]|null
     */
    public function getRachunekBankowyFaktora()
    {
        return $this->container['rachunek_bankowy_faktora'];
    }

    /**
     * Sets rachunek_bankowy_faktora
     *
     * @param \KsefApi\Model\TRachunekBankowy[]|null $rachunek_bankowy_faktora rachunek_bankowy_faktora
     *
     * @return self
     */
    public function setRachunekBankowyFaktora($rachunek_bankowy_faktora)
    {
        if (is_null($rachunek_bankowy_faktora)) {
            throw new \InvalidArgumentException('non-nullable rachunek_bankowy_faktora cannot be null');
        }

        if ((count($rachunek_bankowy_faktora) > 20)) {
            throw new \InvalidArgumentException('invalid value for $rachunek_bankowy_faktora when calling Platnosc., number of items must be less than or equal to 20.');
        }
        $this->container['rachunek_bankowy_faktora'] = $rachunek_bankowy_faktora;

        return $this;
    }

    /**
     * Gets skonto
     *
     * @return \KsefApi\Model\Skonto|null
     */
    public function getSkonto()
    {
        return $this->container['skonto'];
    }

    /**
     * Sets skonto
     *
     * @param \KsefApi\Model\Skonto|null $skonto skonto
     *
     * @return self
     */
    public function setSkonto($skonto)
    {
        if (is_null($skonto)) {
            throw new \InvalidArgumentException('non-nullable skonto cannot be null');
        }
        $this->container['skonto'] = $skonto;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


