<?php
/**
 * Podmiot1
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * Podmiot1 Class Doc Comment
 *
 * @category Class
 * @description Dane podatnika. Imię i nazwisko lub nazwa sprzedawcy towarów lub usług
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Podmiot1 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Podmiot1';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'prefiks_podatnika' => '\KsefApi\Model\TKodyKrajowUE',
        'nr_eori' => 'string',
        'dane_identyfikacyjne' => '\KsefApi\Model\TPodmiot1',
        'adres' => '\KsefApi\Model\TAdres',
        'adres_koresp' => '\KsefApi\Model\TAdres',
        'dane_kontaktowe' => '\KsefApi\Model\DaneKontaktowe[]',
        'status_info_podatnika' => '\KsefApi\Model\TStatusInfoPodatnika'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'prefiks_podatnika' => null,
        'nr_eori' => null,
        'dane_identyfikacyjne' => null,
        'adres' => null,
        'adres_koresp' => null,
        'dane_kontaktowe' => null,
        'status_info_podatnika' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'prefiks_podatnika' => false,
        'nr_eori' => false,
        'dane_identyfikacyjne' => false,
        'adres' => false,
        'adres_koresp' => false,
        'dane_kontaktowe' => false,
        'status_info_podatnika' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'prefiks_podatnika' => 'PrefiksPodatnika',
        'nr_eori' => 'NrEORI',
        'dane_identyfikacyjne' => 'DaneIdentyfikacyjne',
        'adres' => 'Adres',
        'adres_koresp' => 'AdresKoresp',
        'dane_kontaktowe' => 'DaneKontaktowe',
        'status_info_podatnika' => 'StatusInfoPodatnika'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'prefiks_podatnika' => 'setPrefiksPodatnika',
        'nr_eori' => 'setNrEori',
        'dane_identyfikacyjne' => 'setDaneIdentyfikacyjne',
        'adres' => 'setAdres',
        'adres_koresp' => 'setAdresKoresp',
        'dane_kontaktowe' => 'setDaneKontaktowe',
        'status_info_podatnika' => 'setStatusInfoPodatnika'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'prefiks_podatnika' => 'getPrefiksPodatnika',
        'nr_eori' => 'getNrEori',
        'dane_identyfikacyjne' => 'getDaneIdentyfikacyjne',
        'adres' => 'getAdres',
        'adres_koresp' => 'getAdresKoresp',
        'dane_kontaktowe' => 'getDaneKontaktowe',
        'status_info_podatnika' => 'getStatusInfoPodatnika'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('prefiks_podatnika', $data ?? [], null);
        $this->setIfExists('nr_eori', $data ?? [], null);
        $this->setIfExists('dane_identyfikacyjne', $data ?? [], null);
        $this->setIfExists('adres', $data ?? [], null);
        $this->setIfExists('adres_koresp', $data ?? [], null);
        $this->setIfExists('dane_kontaktowe', $data ?? [], null);
        $this->setIfExists('status_info_podatnika', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['nr_eori']) && (mb_strlen($this->container['nr_eori']) > 256)) {
            $invalidProperties[] = "invalid value for 'nr_eori', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['nr_eori']) && (mb_strlen($this->container['nr_eori']) < 1)) {
            $invalidProperties[] = "invalid value for 'nr_eori', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['dane_kontaktowe']) && (count($this->container['dane_kontaktowe']) > 3)) {
            $invalidProperties[] = "invalid value for 'dane_kontaktowe', number of items must be less than or equal to 3.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets prefiks_podatnika
     *
     * @return \KsefApi\Model\TKodyKrajowUE|null
     */
    public function getPrefiksPodatnika()
    {
        return $this->container['prefiks_podatnika'];
    }

    /**
     * Sets prefiks_podatnika
     *
     * @param \KsefApi\Model\TKodyKrajowUE|null $prefiks_podatnika prefiks_podatnika
     *
     * @return self
     */
    public function setPrefiksPodatnika($prefiks_podatnika)
    {
        if (is_null($prefiks_podatnika)) {
            throw new \InvalidArgumentException('non-nullable prefiks_podatnika cannot be null');
        }
        $this->container['prefiks_podatnika'] = $prefiks_podatnika;

        return $this;
    }

    /**
     * Gets nr_eori
     *
     * @return string|null
     */
    public function getNrEori()
    {
        return $this->container['nr_eori'];
    }

    /**
     * Sets nr_eori
     *
     * @param string|null $nr_eori Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setNrEori($nr_eori)
    {
        if (is_null($nr_eori)) {
            throw new \InvalidArgumentException('non-nullable nr_eori cannot be null');
        }
        if ((mb_strlen($nr_eori) > 256)) {
            throw new \InvalidArgumentException('invalid length for $nr_eori when calling Podmiot1., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($nr_eori) < 1)) {
            throw new \InvalidArgumentException('invalid length for $nr_eori when calling Podmiot1., must be bigger than or equal to 1.');
        }

        $this->container['nr_eori'] = $nr_eori;

        return $this;
    }

    /**
     * Gets dane_identyfikacyjne
     *
     * @return \KsefApi\Model\TPodmiot1|null
     */
    public function getDaneIdentyfikacyjne()
    {
        return $this->container['dane_identyfikacyjne'];
    }

    /**
     * Sets dane_identyfikacyjne
     *
     * @param \KsefApi\Model\TPodmiot1|null $dane_identyfikacyjne dane_identyfikacyjne
     *
     * @return self
     */
    public function setDaneIdentyfikacyjne($dane_identyfikacyjne)
    {
        if (is_null($dane_identyfikacyjne)) {
            throw new \InvalidArgumentException('non-nullable dane_identyfikacyjne cannot be null');
        }
        $this->container['dane_identyfikacyjne'] = $dane_identyfikacyjne;

        return $this;
    }

    /**
     * Gets adres
     *
     * @return \KsefApi\Model\TAdres|null
     */
    public function getAdres()
    {
        return $this->container['adres'];
    }

    /**
     * Sets adres
     *
     * @param \KsefApi\Model\TAdres|null $adres adres
     *
     * @return self
     */
    public function setAdres($adres)
    {
        if (is_null($adres)) {
            throw new \InvalidArgumentException('non-nullable adres cannot be null');
        }
        $this->container['adres'] = $adres;

        return $this;
    }

    /**
     * Gets adres_koresp
     *
     * @return \KsefApi\Model\TAdres|null
     */
    public function getAdresKoresp()
    {
        return $this->container['adres_koresp'];
    }

    /**
     * Sets adres_koresp
     *
     * @param \KsefApi\Model\TAdres|null $adres_koresp adres_koresp
     *
     * @return self
     */
    public function setAdresKoresp($adres_koresp)
    {
        if (is_null($adres_koresp)) {
            throw new \InvalidArgumentException('non-nullable adres_koresp cannot be null');
        }
        $this->container['adres_koresp'] = $adres_koresp;

        return $this;
    }

    /**
     * Gets dane_kontaktowe
     *
     * @return \KsefApi\Model\DaneKontaktowe[]|null
     */
    public function getDaneKontaktowe()
    {
        return $this->container['dane_kontaktowe'];
    }

    /**
     * Sets dane_kontaktowe
     *
     * @param \KsefApi\Model\DaneKontaktowe[]|null $dane_kontaktowe dane_kontaktowe
     *
     * @return self
     */
    public function setDaneKontaktowe($dane_kontaktowe)
    {
        if (is_null($dane_kontaktowe)) {
            throw new \InvalidArgumentException('non-nullable dane_kontaktowe cannot be null');
        }

        if ((count($dane_kontaktowe) > 3)) {
            throw new \InvalidArgumentException('invalid value for $dane_kontaktowe when calling Podmiot1., number of items must be less than or equal to 3.');
        }
        $this->container['dane_kontaktowe'] = $dane_kontaktowe;

        return $this;
    }

    /**
     * Gets status_info_podatnika
     *
     * @return \KsefApi\Model\TStatusInfoPodatnika|null
     */
    public function getStatusInfoPodatnika()
    {
        return $this->container['status_info_podatnika'];
    }

    /**
     * Sets status_info_podatnika
     *
     * @param \KsefApi\Model\TStatusInfoPodatnika|null $status_info_podatnika status_info_podatnika
     *
     * @return self
     */
    public function setStatusInfoPodatnika($status_info_podatnika)
    {
        if (is_null($status_info_podatnika)) {
            throw new \InvalidArgumentException('non-nullable status_info_podatnika cannot be null');
        }
        $this->container['status_info_podatnika'] = $status_info_podatnika;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


