<?php
/**
 * Rejestry
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * Rejestry Class Doc Comment
 *
 * @category Class
 * @description Numery podmiotu lub grupy podmiotów w innych rejestrach i bazach danych
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Rejestry implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Rejestry';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'pelna_nazwa' => 'string',
        'krs' => 'string',
        'regon' => 'string',
        'bdo' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'pelna_nazwa' => null,
        'krs' => null,
        'regon' => null,
        'bdo' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'pelna_nazwa' => false,
        'krs' => false,
        'regon' => false,
        'bdo' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'pelna_nazwa' => 'PelnaNazwa',
        'krs' => 'KRS',
        'regon' => 'REGON',
        'bdo' => 'BDO'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'pelna_nazwa' => 'setPelnaNazwa',
        'krs' => 'setKrs',
        'regon' => 'setRegon',
        'bdo' => 'setBdo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'pelna_nazwa' => 'getPelnaNazwa',
        'krs' => 'getKrs',
        'regon' => 'getRegon',
        'bdo' => 'getBdo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('pelna_nazwa', $data ?? [], null);
        $this->setIfExists('krs', $data ?? [], null);
        $this->setIfExists('regon', $data ?? [], null);
        $this->setIfExists('bdo', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['pelna_nazwa']) && (mb_strlen($this->container['pelna_nazwa']) > 256)) {
            $invalidProperties[] = "invalid value for 'pelna_nazwa', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['pelna_nazwa']) && (mb_strlen($this->container['pelna_nazwa']) < 1)) {
            $invalidProperties[] = "invalid value for 'pelna_nazwa', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['krs']) && !preg_match("/^\\d{10}$/", $this->container['krs'])) {
            $invalidProperties[] = "invalid value for 'krs', must be conform to the pattern /^\\d{10}$/.";
        }

        if (!is_null($this->container['regon']) && !preg_match("/^\\d{9}|\\d{14}$/", $this->container['regon'])) {
            $invalidProperties[] = "invalid value for 'regon', must be conform to the pattern /^\\d{9}|\\d{14}$/.";
        }

        if (!is_null($this->container['bdo']) && (mb_strlen($this->container['bdo']) > 9)) {
            $invalidProperties[] = "invalid value for 'bdo', the character length must be smaller than or equal to 9.";
        }

        if (!is_null($this->container['bdo']) && (mb_strlen($this->container['bdo']) < 1)) {
            $invalidProperties[] = "invalid value for 'bdo', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets pelna_nazwa
     *
     * @return string|null
     */
    public function getPelnaNazwa()
    {
        return $this->container['pelna_nazwa'];
    }

    /**
     * Sets pelna_nazwa
     *
     * @param string|null $pelna_nazwa Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setPelnaNazwa($pelna_nazwa)
    {
        if (is_null($pelna_nazwa)) {
            throw new \InvalidArgumentException('non-nullable pelna_nazwa cannot be null');
        }
        if ((mb_strlen($pelna_nazwa) > 256)) {
            throw new \InvalidArgumentException('invalid length for $pelna_nazwa when calling Rejestry., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($pelna_nazwa) < 1)) {
            throw new \InvalidArgumentException('invalid length for $pelna_nazwa when calling Rejestry., must be bigger than or equal to 1.');
        }

        $this->container['pelna_nazwa'] = $pelna_nazwa;

        return $this;
    }

    /**
     * Gets krs
     *
     * @return string|null
     */
    public function getKrs()
    {
        return $this->container['krs'];
    }

    /**
     * Sets krs
     *
     * @param string|null $krs Numer Krajowego Rejestru Sądowego
     *
     * @return self
     */
    public function setKrs($krs)
    {
        if (is_null($krs)) {
            throw new \InvalidArgumentException('non-nullable krs cannot be null');
        }

        if ((!preg_match("/^\\d{10}$/", ObjectSerializer::toString($krs)))) {
            throw new \InvalidArgumentException("invalid value for \$krs when calling Rejestry., must conform to the pattern /^\\d{10}$/.");
        }

        $this->container['krs'] = $krs;

        return $this;
    }

    /**
     * Gets regon
     *
     * @return string|null
     */
    public function getRegon()
    {
        return $this->container['regon'];
    }

    /**
     * Sets regon
     *
     * @param string|null $regon Numer REGON
     *
     * @return self
     */
    public function setRegon($regon)
    {
        if (is_null($regon)) {
            throw new \InvalidArgumentException('non-nullable regon cannot be null');
        }

        if ((!preg_match("/^\\d{9}|\\d{14}$/", ObjectSerializer::toString($regon)))) {
            throw new \InvalidArgumentException("invalid value for \$regon when calling Rejestry., must conform to the pattern /^\\d{9}|\\d{14}$/.");
        }

        $this->container['regon'] = $regon;

        return $this;
    }

    /**
     * Gets bdo
     *
     * @return string|null
     */
    public function getBdo()
    {
        return $this->container['bdo'];
    }

    /**
     * Sets bdo
     *
     * @param string|null $bdo Numer w Bazie Danych o Odpadach
     *
     * @return self
     */
    public function setBdo($bdo)
    {
        if (is_null($bdo)) {
            throw new \InvalidArgumentException('non-nullable bdo cannot be null');
        }
        if ((mb_strlen($bdo) > 9)) {
            throw new \InvalidArgumentException('invalid length for $bdo when calling Rejestry., must be smaller than or equal to 9.');
        }
        if ((mb_strlen($bdo) < 1)) {
            throw new \InvalidArgumentException('invalid length for $bdo when calling Rejestry., must be bigger than or equal to 1.');
        }

        $this->container['bdo'] = $bdo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


