<?php
/**
 * TAdres
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * TAdres Class Doc Comment
 *
 * @category Class
 * @description Informacje opisujące adres
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TAdres implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TAdres';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kod_kraju' => '\KsefApi\Model\TKodKraju',
        'adres_l1' => 'string',
        'adres_l2' => 'string',
        'gln' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kod_kraju' => null,
        'adres_l1' => null,
        'adres_l2' => null,
        'gln' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kod_kraju' => false,
        'adres_l1' => false,
        'adres_l2' => false,
        'gln' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kod_kraju' => 'KodKraju',
        'adres_l1' => 'AdresL1',
        'adres_l2' => 'AdresL2',
        'gln' => 'GLN'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kod_kraju' => 'setKodKraju',
        'adres_l1' => 'setAdresL1',
        'adres_l2' => 'setAdresL2',
        'gln' => 'setGln'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kod_kraju' => 'getKodKraju',
        'adres_l1' => 'getAdresL1',
        'adres_l2' => 'getAdresL2',
        'gln' => 'getGln'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('kod_kraju', $data ?? [], null);
        $this->setIfExists('adres_l1', $data ?? [], null);
        $this->setIfExists('adres_l2', $data ?? [], null);
        $this->setIfExists('gln', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['adres_l1']) && (mb_strlen($this->container['adres_l1']) > 512)) {
            $invalidProperties[] = "invalid value for 'adres_l1', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['adres_l1']) && (mb_strlen($this->container['adres_l1']) < 1)) {
            $invalidProperties[] = "invalid value for 'adres_l1', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['adres_l2']) && (mb_strlen($this->container['adres_l2']) > 512)) {
            $invalidProperties[] = "invalid value for 'adres_l2', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['adres_l2']) && (mb_strlen($this->container['adres_l2']) < 1)) {
            $invalidProperties[] = "invalid value for 'adres_l2', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['gln']) && (mb_strlen($this->container['gln']) > 13)) {
            $invalidProperties[] = "invalid value for 'gln', the character length must be smaller than or equal to 13.";
        }

        if (!is_null($this->container['gln']) && (mb_strlen($this->container['gln']) < 1)) {
            $invalidProperties[] = "invalid value for 'gln', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kod_kraju
     *
     * @return \KsefApi\Model\TKodKraju|null
     */
    public function getKodKraju()
    {
        return $this->container['kod_kraju'];
    }

    /**
     * Sets kod_kraju
     *
     * @param \KsefApi\Model\TKodKraju|null $kod_kraju kod_kraju
     *
     * @return self
     */
    public function setKodKraju($kod_kraju)
    {
        if (is_null($kod_kraju)) {
            throw new \InvalidArgumentException('non-nullable kod_kraju cannot be null');
        }
        $this->container['kod_kraju'] = $kod_kraju;

        return $this;
    }

    /**
     * Gets adres_l1
     *
     * @return string|null
     */
    public function getAdresL1()
    {
        return $this->container['adres_l1'];
    }

    /**
     * Sets adres_l1
     *
     * @param string|null $adres_l1 Typ znakowy ograniczony do 512 znaków
     *
     * @return self
     */
    public function setAdresL1($adres_l1)
    {
        if (is_null($adres_l1)) {
            throw new \InvalidArgumentException('non-nullable adres_l1 cannot be null');
        }
        if ((mb_strlen($adres_l1) > 512)) {
            throw new \InvalidArgumentException('invalid length for $adres_l1 when calling TAdres., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($adres_l1) < 1)) {
            throw new \InvalidArgumentException('invalid length for $adres_l1 when calling TAdres., must be bigger than or equal to 1.');
        }

        $this->container['adres_l1'] = $adres_l1;

        return $this;
    }

    /**
     * Gets adres_l2
     *
     * @return string|null
     */
    public function getAdresL2()
    {
        return $this->container['adres_l2'];
    }

    /**
     * Sets adres_l2
     *
     * @param string|null $adres_l2 Typ znakowy ograniczony do 512 znaków
     *
     * @return self
     */
    public function setAdresL2($adres_l2)
    {
        if (is_null($adres_l2)) {
            throw new \InvalidArgumentException('non-nullable adres_l2 cannot be null');
        }
        if ((mb_strlen($adres_l2) > 512)) {
            throw new \InvalidArgumentException('invalid length for $adres_l2 when calling TAdres., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($adres_l2) < 1)) {
            throw new \InvalidArgumentException('invalid length for $adres_l2 when calling TAdres., must be bigger than or equal to 1.');
        }

        $this->container['adres_l2'] = $adres_l2;

        return $this;
    }

    /**
     * Gets gln
     *
     * @return string|null
     */
    public function getGln()
    {
        return $this->container['gln'];
    }

    /**
     * Sets gln
     *
     * @param string|null $gln Typ Globalnego Numeru Lokalizacyjnego
     *
     * @return self
     */
    public function setGln($gln)
    {
        if (is_null($gln)) {
            throw new \InvalidArgumentException('non-nullable gln cannot be null');
        }
        if ((mb_strlen($gln) > 13)) {
            throw new \InvalidArgumentException('invalid length for $gln when calling TAdres., must be smaller than or equal to 13.');
        }
        if ((mb_strlen($gln) < 1)) {
            throw new \InvalidArgumentException('invalid length for $gln when calling TAdres., must be bigger than or equal to 1.');
        }

        $this->container['gln'] = $gln;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


