<?php
/**
 * TKodKraju
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;
use \KsefApi\ObjectSerializer;

/**
 * TKodKraju Class Doc Comment
 *
 * @category Class
 * @description Słownik kodów krajów
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TKodKraju
{
    /**
     * Possible values of this enum
     */
    public const AF = 'AF';

    public const AX = 'AX';

    public const AL = 'AL';

    public const DZ = 'DZ';

    public const AD = 'AD';

    public const AO = 'AO';

    public const AI = 'AI';

    public const AQ = 'AQ';

    public const AG = 'AG';

    public const AN = 'AN';

    public const SA = 'SA';

    public const AR = 'AR';

    public const AM = 'AM';

    public const AW = 'AW';

    public const AU = 'AU';

    public const AT = 'AT';

    public const AZ = 'AZ';

    public const BS = 'BS';

    public const BH = 'BH';

    public const BD = 'BD';

    public const BB = 'BB';

    public const BE = 'BE';

    public const BZ = 'BZ';

    public const BJ = 'BJ';

    public const BM = 'BM';

    public const BT = 'BT';

    public const BY = 'BY';

    public const BO = 'BO';

    public const BQ = 'BQ';

    public const BA = 'BA';

    public const BW = 'BW';

    public const BR = 'BR';

    public const BN = 'BN';

    public const IO = 'IO';

    public const BG = 'BG';

    public const BF = 'BF';

    public const BI = 'BI';

    public const XC = 'XC';

    public const CL = 'CL';

    public const CN = 'CN';

    public const HR = 'HR';

    public const CW = 'CW';

    public const CY = 'CY';

    public const TD = 'TD';

    public const ME = 'ME';

    public const DK = 'DK';

    public const DM = 'DM';

    public const _DO = 'DO';

    public const DJ = 'DJ';

    public const EG = 'EG';

    public const EC = 'EC';

    public const ER = 'ER';

    public const EE = 'EE';

    public const ET = 'ET';

    public const FK = 'FK';

    public const FJ = 'FJ';

    public const PH = 'PH';

    public const FI = 'FI';

    public const FR = 'FR';

    public const TF = 'TF';

    public const GA = 'GA';

    public const GM = 'GM';

    public const GH = 'GH';

    public const GI = 'GI';

    public const GR = 'GR';

    public const GD = 'GD';

    public const GL = 'GL';

    public const GE = 'GE';

    public const GU = 'GU';

    public const GG = 'GG';

    public const GY = 'GY';

    public const GF = 'GF';

    public const GP = 'GP';

    public const GT = 'GT';

    public const GN = 'GN';

    public const GQ = 'GQ';

    public const GW = 'GW';

    public const HT = 'HT';

    public const ES = 'ES';

    public const HN = 'HN';

    public const HK = 'HK';

    public const IN = 'IN';

    public const ID = 'ID';

    public const IQ = 'IQ';

    public const IR = 'IR';

    public const IE = 'IE';

    public const IS = 'IS';

    public const IL = 'IL';

    public const JM = 'JM';

    public const JP = 'JP';

    public const YE = 'YE';

    public const JE = 'JE';

    public const JO = 'JO';

    public const KY = 'KY';

    public const KH = 'KH';

    public const CM = 'CM';

    public const CA = 'CA';

    public const QA = 'QA';

    public const KZ = 'KZ';

    public const KE = 'KE';

    public const KG = 'KG';

    public const KI = 'KI';

    public const CO = 'CO';

    public const KM = 'KM';

    public const CG = 'CG';

    public const CD = 'CD';

    public const KP = 'KP';

    public const XK = 'XK';

    public const CR = 'CR';

    public const CU = 'CU';

    public const KW = 'KW';

    public const LA = 'LA';

    public const LS = 'LS';

    public const LB = 'LB';

    public const LR = 'LR';

    public const LY = 'LY';

    public const LI = 'LI';

    public const LT = 'LT';

    public const LV = 'LV';

    public const LU = 'LU';

    public const MK = 'MK';

    public const MG = 'MG';

    public const YT = 'YT';

    public const MO = 'MO';

    public const MW = 'MW';

    public const MV = 'MV';

    public const MY = 'MY';

    public const ML = 'ML';

    public const MT = 'MT';

    public const MP = 'MP';

    public const MA = 'MA';

    public const MQ = 'MQ';

    public const MR = 'MR';

    public const MU = 'MU';

    public const MX = 'MX';

    public const XL = 'XL';

    public const FM = 'FM';

    public const UM = 'UM';

    public const MD = 'MD';

    public const MC = 'MC';

    public const MN = 'MN';

    public const MS = 'MS';

    public const MZ = 'MZ';

    public const MM = 'MM';

    public const NA = 'NA';

    public const NR = 'NR';

    public const NP = 'NP';

    public const NL = 'NL';

    public const DE = 'DE';

    public const NE = 'NE';

    public const NG = 'NG';

    public const NI = 'NI';

    public const NU = 'NU';

    public const NF = 'NF';

    public const FALSE = 'false';

    public const NC = 'NC';

    public const NZ = 'NZ';

    public const PS = 'PS';

    public const OM = 'OM';

    public const PK = 'PK';

    public const PW = 'PW';

    public const PA = 'PA';

    public const PG = 'PG';

    public const PY = 'PY';

    public const PE = 'PE';

    public const PN = 'PN';

    public const PF = 'PF';

    public const PL = 'PL';

    public const GS = 'GS';

    public const PT = 'PT';

    public const PR = 'PR';

    public const CF = 'CF';

    public const CZ = 'CZ';

    public const KR = 'KR';

    public const ZA = 'ZA';

    public const RE = 'RE';

    public const RU = 'RU';

    public const RO = 'RO';

    public const RW = 'RW';

    public const EH = 'EH';

    public const BL = 'BL';

    public const KN = 'KN';

    public const LC = 'LC';

    public const MF = 'MF';

    public const VC = 'VC';

    public const SV = 'SV';

    public const WS = 'WS';

    public const _AS = 'AS';

    public const SM = 'SM';

    public const SN = 'SN';

    public const RS = 'RS';

    public const SC = 'SC';

    public const SL = 'SL';

    public const SG = 'SG';

    public const SK = 'SK';

    public const SI = 'SI';

    public const SO = 'SO';

    public const LK = 'LK';

    public const PM = 'PM';

    public const US = 'US';

    public const SZ = 'SZ';

    public const SD = 'SD';

    public const SS = 'SS';

    public const SR = 'SR';

    public const SJ = 'SJ';

    public const SH = 'SH';

    public const SY = 'SY';

    public const CH = 'CH';

    public const SE = 'SE';

    public const TJ = 'TJ';

    public const TH = 'TH';

    public const TW = 'TW';

    public const TZ = 'TZ';

    public const TG = 'TG';

    public const TK = 'TK';

    public const TO = 'TO';

    public const TT = 'TT';

    public const TN = 'TN';

    public const TR = 'TR';

    public const TM = 'TM';

    public const TV = 'TV';

    public const UG = 'UG';

    public const UA = 'UA';

    public const UY = 'UY';

    public const UZ = 'UZ';

    public const VU = 'VU';

    public const WF = 'WF';

    public const VA = 'VA';

    public const HU = 'HU';

    public const VE = 'VE';

    public const GB = 'GB';

    public const VN = 'VN';

    public const IT = 'IT';

    public const TL = 'TL';

    public const CI = 'CI';

    public const BV = 'BV';

    public const CX = 'CX';

    public const IM = 'IM';

    public const SX = 'SX';

    public const CK = 'CK';

    public const VI = 'VI';

    public const VG = 'VG';

    public const HM = 'HM';

    public const CC = 'CC';

    public const MH = 'MH';

    public const FO = 'FO';

    public const SB = 'SB';

    public const ST = 'ST';

    public const TC = 'TC';

    public const ZM = 'ZM';

    public const CV = 'CV';

    public const ZW = 'ZW';

    public const AE = 'AE';

    public const XI = 'XI';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AF,
            self::AX,
            self::AL,
            self::DZ,
            self::AD,
            self::AO,
            self::AI,
            self::AQ,
            self::AG,
            self::AN,
            self::SA,
            self::AR,
            self::AM,
            self::AW,
            self::AU,
            self::AT,
            self::AZ,
            self::BS,
            self::BH,
            self::BD,
            self::BB,
            self::BE,
            self::BZ,
            self::BJ,
            self::BM,
            self::BT,
            self::BY,
            self::BO,
            self::BQ,
            self::BA,
            self::BW,
            self::BR,
            self::BN,
            self::IO,
            self::BG,
            self::BF,
            self::BI,
            self::XC,
            self::CL,
            self::CN,
            self::HR,
            self::CW,
            self::CY,
            self::TD,
            self::ME,
            self::DK,
            self::DM,
            self::_DO,
            self::DJ,
            self::EG,
            self::EC,
            self::ER,
            self::EE,
            self::ET,
            self::FK,
            self::FJ,
            self::PH,
            self::FI,
            self::FR,
            self::TF,
            self::GA,
            self::GM,
            self::GH,
            self::GI,
            self::GR,
            self::GD,
            self::GL,
            self::GE,
            self::GU,
            self::GG,
            self::GY,
            self::GF,
            self::GP,
            self::GT,
            self::GN,
            self::GQ,
            self::GW,
            self::HT,
            self::ES,
            self::HN,
            self::HK,
            self::IN,
            self::ID,
            self::IQ,
            self::IR,
            self::IE,
            self::IS,
            self::IL,
            self::JM,
            self::JP,
            self::YE,
            self::JE,
            self::JO,
            self::KY,
            self::KH,
            self::CM,
            self::CA,
            self::QA,
            self::KZ,
            self::KE,
            self::KG,
            self::KI,
            self::CO,
            self::KM,
            self::CG,
            self::CD,
            self::KP,
            self::XK,
            self::CR,
            self::CU,
            self::KW,
            self::LA,
            self::LS,
            self::LB,
            self::LR,
            self::LY,
            self::LI,
            self::LT,
            self::LV,
            self::LU,
            self::MK,
            self::MG,
            self::YT,
            self::MO,
            self::MW,
            self::MV,
            self::MY,
            self::ML,
            self::MT,
            self::MP,
            self::MA,
            self::MQ,
            self::MR,
            self::MU,
            self::MX,
            self::XL,
            self::FM,
            self::UM,
            self::MD,
            self::MC,
            self::MN,
            self::MS,
            self::MZ,
            self::MM,
            self::NA,
            self::NR,
            self::NP,
            self::NL,
            self::DE,
            self::NE,
            self::NG,
            self::NI,
            self::NU,
            self::NF,
            self::FALSE,
            self::NC,
            self::NZ,
            self::PS,
            self::OM,
            self::PK,
            self::PW,
            self::PA,
            self::PG,
            self::PY,
            self::PE,
            self::PN,
            self::PF,
            self::PL,
            self::GS,
            self::PT,
            self::PR,
            self::CF,
            self::CZ,
            self::KR,
            self::ZA,
            self::RE,
            self::RU,
            self::RO,
            self::RW,
            self::EH,
            self::BL,
            self::KN,
            self::LC,
            self::MF,
            self::VC,
            self::SV,
            self::WS,
            self::_AS,
            self::SM,
            self::SN,
            self::RS,
            self::SC,
            self::SL,
            self::SG,
            self::SK,
            self::SI,
            self::SO,
            self::LK,
            self::PM,
            self::US,
            self::SZ,
            self::SD,
            self::SS,
            self::SR,
            self::SJ,
            self::SH,
            self::SY,
            self::CH,
            self::SE,
            self::TJ,
            self::TH,
            self::TW,
            self::TZ,
            self::TG,
            self::TK,
            self::TO,
            self::TT,
            self::TN,
            self::TR,
            self::TM,
            self::TV,
            self::UG,
            self::UA,
            self::UY,
            self::UZ,
            self::VU,
            self::WF,
            self::VA,
            self::HU,
            self::VE,
            self::GB,
            self::VN,
            self::IT,
            self::TL,
            self::CI,
            self::BV,
            self::CX,
            self::IM,
            self::SX,
            self::CK,
            self::VI,
            self::VG,
            self::HM,
            self::CC,
            self::MH,
            self::FO,
            self::SB,
            self::ST,
            self::TC,
            self::ZM,
            self::CV,
            self::ZW,
            self::AE,
            self::XI
        ];
    }
}


