<?php
/**
 * TKodFormularza
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * TKodFormularza Class Doc Comment
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TKodFormularza implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TKodFormularza';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kod_formularza' => 'string',
        'kod_systemowy' => 'string',
        'wersja_schemy' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kod_formularza' => null,
        'kod_systemowy' => null,
        'wersja_schemy' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kod_formularza' => false,
        'kod_systemowy' => false,
        'wersja_schemy' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kod_formularza' => 'kodFormularza',
        'kod_systemowy' => 'kodSystemowy',
        'wersja_schemy' => 'wersjaSchemy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kod_formularza' => 'setKodFormularza',
        'kod_systemowy' => 'setKodSystemowy',
        'wersja_schemy' => 'setWersjaSchemy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kod_formularza' => 'getKodFormularza',
        'kod_systemowy' => 'getKodSystemowy',
        'wersja_schemy' => 'getWersjaSchemy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const KOD_FORMULARZA_FA = 'FA';
    public const KOD_SYSTEMOWY_FA_V2 = 'FA_V2';
    public const KOD_SYSTEMOWY_FA_V3 = 'FA_V3';
    public const WERSJA_SCHEMY__1_0_E = '1_0E';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKodFormularzaAllowableValues()
    {
        return [
            self::KOD_FORMULARZA_FA,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKodSystemowyAllowableValues()
    {
        return [
            self::KOD_SYSTEMOWY_FA_V2,
            self::KOD_SYSTEMOWY_FA_V3,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getWersjaSchemyAllowableValues()
    {
        return [
            self::WERSJA_SCHEMY__1_0_E,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('kod_formularza', $data ?? [], null);
        $this->setIfExists('kod_systemowy', $data ?? [], null);
        $this->setIfExists('wersja_schemy', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getKodFormularzaAllowableValues();
        if (!is_null($this->container['kod_formularza']) && !in_array($this->container['kod_formularza'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kod_formularza', must be one of '%s'",
                $this->container['kod_formularza'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getKodSystemowyAllowableValues();
        if (!is_null($this->container['kod_systemowy']) && !in_array($this->container['kod_systemowy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kod_systemowy', must be one of '%s'",
                $this->container['kod_systemowy'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getWersjaSchemyAllowableValues();
        if (!is_null($this->container['wersja_schemy']) && !in_array($this->container['wersja_schemy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'wersja_schemy', must be one of '%s'",
                $this->container['wersja_schemy'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kod_formularza
     *
     * @return string|null
     */
    public function getKodFormularza()
    {
        return $this->container['kod_formularza'];
    }

    /**
     * Sets kod_formularza
     *
     * @param string|null $kod_formularza kod_formularza
     *
     * @return self
     */
    public function setKodFormularza($kod_formularza)
    {
        if (is_null($kod_formularza)) {
            throw new \InvalidArgumentException('non-nullable kod_formularza cannot be null');
        }
        $allowedValues = $this->getKodFormularzaAllowableValues();
        if (!in_array($kod_formularza, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kod_formularza', must be one of '%s'",
                    $kod_formularza,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kod_formularza'] = $kod_formularza;

        return $this;
    }

    /**
     * Gets kod_systemowy
     *
     * @return string|null
     */
    public function getKodSystemowy()
    {
        return $this->container['kod_systemowy'];
    }

    /**
     * Sets kod_systemowy
     *
     * @param string|null $kod_systemowy kod_systemowy
     *
     * @return self
     */
    public function setKodSystemowy($kod_systemowy)
    {
        if (is_null($kod_systemowy)) {
            throw new \InvalidArgumentException('non-nullable kod_systemowy cannot be null');
        }
        $allowedValues = $this->getKodSystemowyAllowableValues();
        if (!in_array($kod_systemowy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kod_systemowy', must be one of '%s'",
                    $kod_systemowy,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kod_systemowy'] = $kod_systemowy;

        return $this;
    }

    /**
     * Gets wersja_schemy
     *
     * @return string|null
     */
    public function getWersjaSchemy()
    {
        return $this->container['wersja_schemy'];
    }

    /**
     * Sets wersja_schemy
     *
     * @param string|null $wersja_schemy wersja_schemy
     *
     * @return self
     */
    public function setWersjaSchemy($wersja_schemy)
    {
        if (is_null($wersja_schemy)) {
            throw new \InvalidArgumentException('non-nullable wersja_schemy cannot be null');
        }
        $allowedValues = $this->getWersjaSchemyAllowableValues();
        if (!in_array($wersja_schemy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'wersja_schemy', must be one of '%s'",
                    $wersja_schemy,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['wersja_schemy'] = $wersja_schemy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


