<?php
/**
 * TNaglowek
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * TNaglowek Class Doc Comment
 *
 * @category Class
 * @description Nagłówek
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TNaglowek implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TNaglowek';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kod_formularza' => '\KsefApi\Model\TKodFormularza',
        'wariant_formularza' => '\KsefApi\Model\WariantFormularza',
        'data_wytworzenia_fa' => '\DateTime',
        'system_info' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kod_formularza' => null,
        'wariant_formularza' => null,
        'data_wytworzenia_fa' => 'date-time',
        'system_info' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kod_formularza' => false,
        'wariant_formularza' => false,
        'data_wytworzenia_fa' => false,
        'system_info' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kod_formularza' => 'KodFormularza',
        'wariant_formularza' => 'WariantFormularza',
        'data_wytworzenia_fa' => 'DataWytworzeniaFa',
        'system_info' => 'SystemInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kod_formularza' => 'setKodFormularza',
        'wariant_formularza' => 'setWariantFormularza',
        'data_wytworzenia_fa' => 'setDataWytworzeniaFa',
        'system_info' => 'setSystemInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kod_formularza' => 'getKodFormularza',
        'wariant_formularza' => 'getWariantFormularza',
        'data_wytworzenia_fa' => 'getDataWytworzeniaFa',
        'system_info' => 'getSystemInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('kod_formularza', $data ?? [], null);
        $this->setIfExists('wariant_formularza', $data ?? [], null);
        $this->setIfExists('data_wytworzenia_fa', $data ?? [], null);
        $this->setIfExists('system_info', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['system_info']) && (mb_strlen($this->container['system_info']) > 256)) {
            $invalidProperties[] = "invalid value for 'system_info', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['system_info']) && (mb_strlen($this->container['system_info']) < 1)) {
            $invalidProperties[] = "invalid value for 'system_info', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kod_formularza
     *
     * @return \KsefApi\Model\TKodFormularza|null
     */
    public function getKodFormularza()
    {
        return $this->container['kod_formularza'];
    }

    /**
     * Sets kod_formularza
     *
     * @param \KsefApi\Model\TKodFormularza|null $kod_formularza kod_formularza
     *
     * @return self
     */
    public function setKodFormularza($kod_formularza)
    {
        if (is_null($kod_formularza)) {
            throw new \InvalidArgumentException('non-nullable kod_formularza cannot be null');
        }
        $this->container['kod_formularza'] = $kod_formularza;

        return $this;
    }

    /**
     * Gets wariant_formularza
     *
     * @return \KsefApi\Model\WariantFormularza|null
     */
    public function getWariantFormularza()
    {
        return $this->container['wariant_formularza'];
    }

    /**
     * Sets wariant_formularza
     *
     * @param \KsefApi\Model\WariantFormularza|null $wariant_formularza wariant_formularza
     *
     * @return self
     */
    public function setWariantFormularza($wariant_formularza)
    {
        if (is_null($wariant_formularza)) {
            throw new \InvalidArgumentException('non-nullable wariant_formularza cannot be null');
        }
        $this->container['wariant_formularza'] = $wariant_formularza;

        return $this;
    }

    /**
     * Gets data_wytworzenia_fa
     *
     * @return \DateTime|null
     */
    public function getDataWytworzeniaFa()
    {
        return $this->container['data_wytworzenia_fa'];
    }

    /**
     * Sets data_wytworzenia_fa
     *
     * @param \DateTime|null $data_wytworzenia_fa Data i czas wytworzenia faktury
     *
     * @return self
     */
    public function setDataWytworzeniaFa($data_wytworzenia_fa)
    {
        if (is_null($data_wytworzenia_fa)) {
            throw new \InvalidArgumentException('non-nullable data_wytworzenia_fa cannot be null');
        }
        $this->container['data_wytworzenia_fa'] = $data_wytworzenia_fa;

        return $this;
    }

    /**
     * Gets system_info
     *
     * @return string|null
     */
    public function getSystemInfo()
    {
        return $this->container['system_info'];
    }

    /**
     * Sets system_info
     *
     * @param string|null $system_info Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setSystemInfo($system_info)
    {
        if (is_null($system_info)) {
            throw new \InvalidArgumentException('non-nullable system_info cannot be null');
        }
        if ((mb_strlen($system_info) > 256)) {
            throw new \InvalidArgumentException('invalid length for $system_info when calling TNaglowek., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($system_info) < 1)) {
            throw new \InvalidArgumentException('invalid length for $system_info when calling TNaglowek., must be bigger than or equal to 1.');
        }

        $this->container['system_info'] = $system_info;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


