<?php
/**
 * TOznaczenieProcedury
 *
 * PHP version 5
 *
 * @category Class
 * @package  KsefApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KSeF API
 *
 * API do systemu KSeF
 *
 * OpenAPI spec version: 1.2.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KsefApi\Model;
use \KsefApi\ObjectSerializer;

/**
 * TOznaczenieProcedury Class Doc Comment
 *
 * @category Class
 * @description Oznaczenia dotyczące procedur dla faktur
 * @package  KsefApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TOznaczenieProcedury
{
    /**
     * Possible values of this enum
     */
    const WSTO_EE = 'WSTO_EE';
    const IED = 'IED';
    const TT_D = 'TT_D';
    const I_42 = 'I_42';
    const I_63 = 'I_63';
    const B_SPV = 'B_SPV';
    const B_SPV_DOSTAWA = 'B_SPV_DOSTAWA';
    const B_MPV_PROWIZJA = 'B_MPV_PROWIZJA';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WSTO_EE
            self::IED
            self::TT_D
            self::I_42
            self::I_63
            self::B_SPV
            self::B_SPV_DOSTAWA
            self::B_MPV_PROWIZJA
        ];
    }
}
