<?php
/**
 * TRachunekWlasnyBanku
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;
use \KsefApi\ObjectSerializer;

/**
 * TRachunekWlasnyBanku Class Doc Comment
 *
 * @category Class
 * @description Types of own accounts (1 - bank account or credit union account used to settle monetary receivables acquired by that bank or credit union, 2 - bank account or credit union account used by that bank or credit union to collect amounts due from the buyer/recipient for the supply of goods or services documented by an invoice and to transfer them in whole or in part to the supplier or service provider, 3 - bank account or credit union account maintained by that bank or credit union for its own operations, not a settlement account)
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TRachunekWlasnyBanku
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_1 = 1;

    public const NUMBER_2 = 2;

    public const NUMBER_3 = 3;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_1,
            self::NUMBER_2,
            self::NUMBER_3
        ];
    }
}


