<?php
/**
 * Transport
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * Transport Class Doc Comment
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Transport implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Transport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rodzaj_transportu' => '\KsefApi\Model\TRodzajTransportu',
        'transport_inny' => 'int',
        'opis_innego_transportu' => 'string',
        'przewoznik' => '\KsefApi\Model\Przewoznik',
        'nr_zlecenia_transportu' => 'string',
        'opis_ladunku' => '\KsefApi\Model\TLadunek',
        'ladunek_inny' => 'int',
        'opis_innego_ladunku' => 'string',
        'jednostka_opakowania' => 'string',
        'data_godz_rozp_transportu' => '\DateTime',
        'data_godz_zak_transportu' => '\DateTime',
        'wysylka_z' => '\KsefApi\Model\TAdres',
        'wysylka_przez' => '\KsefApi\Model\TAdres[]',
        'wysylka_do' => '\KsefApi\Model\TAdres'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rodzaj_transportu' => null,
        'transport_inny' => 'int32',
        'opis_innego_transportu' => null,
        'przewoznik' => null,
        'nr_zlecenia_transportu' => null,
        'opis_ladunku' => null,
        'ladunek_inny' => 'int32',
        'opis_innego_ladunku' => null,
        'jednostka_opakowania' => null,
        'data_godz_rozp_transportu' => 'date-time',
        'data_godz_zak_transportu' => 'date-time',
        'wysylka_z' => null,
        'wysylka_przez' => null,
        'wysylka_do' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rodzaj_transportu' => false,
        'transport_inny' => false,
        'opis_innego_transportu' => false,
        'przewoznik' => false,
        'nr_zlecenia_transportu' => false,
        'opis_ladunku' => false,
        'ladunek_inny' => false,
        'opis_innego_ladunku' => false,
        'jednostka_opakowania' => false,
        'data_godz_rozp_transportu' => false,
        'data_godz_zak_transportu' => false,
        'wysylka_z' => false,
        'wysylka_przez' => false,
        'wysylka_do' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rodzaj_transportu' => 'RodzajTransportu',
        'transport_inny' => 'TransportInny',
        'opis_innego_transportu' => 'OpisInnegoTransportu',
        'przewoznik' => 'Przewoznik',
        'nr_zlecenia_transportu' => 'NrZleceniaTransportu',
        'opis_ladunku' => 'OpisLadunku',
        'ladunek_inny' => 'LadunekInny',
        'opis_innego_ladunku' => 'OpisInnegoLadunku',
        'jednostka_opakowania' => 'JednostkaOpakowania',
        'data_godz_rozp_transportu' => 'DataGodzRozpTransportu',
        'data_godz_zak_transportu' => 'DataGodzZakTransportu',
        'wysylka_z' => 'WysylkaZ',
        'wysylka_przez' => 'WysylkaPrzez',
        'wysylka_do' => 'WysylkaDo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rodzaj_transportu' => 'setRodzajTransportu',
        'transport_inny' => 'setTransportInny',
        'opis_innego_transportu' => 'setOpisInnegoTransportu',
        'przewoznik' => 'setPrzewoznik',
        'nr_zlecenia_transportu' => 'setNrZleceniaTransportu',
        'opis_ladunku' => 'setOpisLadunku',
        'ladunek_inny' => 'setLadunekInny',
        'opis_innego_ladunku' => 'setOpisInnegoLadunku',
        'jednostka_opakowania' => 'setJednostkaOpakowania',
        'data_godz_rozp_transportu' => 'setDataGodzRozpTransportu',
        'data_godz_zak_transportu' => 'setDataGodzZakTransportu',
        'wysylka_z' => 'setWysylkaZ',
        'wysylka_przez' => 'setWysylkaPrzez',
        'wysylka_do' => 'setWysylkaDo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rodzaj_transportu' => 'getRodzajTransportu',
        'transport_inny' => 'getTransportInny',
        'opis_innego_transportu' => 'getOpisInnegoTransportu',
        'przewoznik' => 'getPrzewoznik',
        'nr_zlecenia_transportu' => 'getNrZleceniaTransportu',
        'opis_ladunku' => 'getOpisLadunku',
        'ladunek_inny' => 'getLadunekInny',
        'opis_innego_ladunku' => 'getOpisInnegoLadunku',
        'jednostka_opakowania' => 'getJednostkaOpakowania',
        'data_godz_rozp_transportu' => 'getDataGodzRozpTransportu',
        'data_godz_zak_transportu' => 'getDataGodzZakTransportu',
        'wysylka_z' => 'getWysylkaZ',
        'wysylka_przez' => 'getWysylkaPrzez',
        'wysylka_do' => 'getWysylkaDo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rodzaj_transportu', $data ?? [], null);
        $this->setIfExists('transport_inny', $data ?? [], null);
        $this->setIfExists('opis_innego_transportu', $data ?? [], null);
        $this->setIfExists('przewoznik', $data ?? [], null);
        $this->setIfExists('nr_zlecenia_transportu', $data ?? [], null);
        $this->setIfExists('opis_ladunku', $data ?? [], null);
        $this->setIfExists('ladunek_inny', $data ?? [], null);
        $this->setIfExists('opis_innego_ladunku', $data ?? [], null);
        $this->setIfExists('jednostka_opakowania', $data ?? [], null);
        $this->setIfExists('data_godz_rozp_transportu', $data ?? [], null);
        $this->setIfExists('data_godz_zak_transportu', $data ?? [], null);
        $this->setIfExists('wysylka_z', $data ?? [], null);
        $this->setIfExists('wysylka_przez', $data ?? [], null);
        $this->setIfExists('wysylka_do', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['transport_inny']) && ($this->container['transport_inny'] > 1)) {
            $invalidProperties[] = "invalid value for 'transport_inny', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['transport_inny']) && ($this->container['transport_inny'] < 1)) {
            $invalidProperties[] = "invalid value for 'transport_inny', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['opis_innego_transportu']) && (mb_strlen($this->container['opis_innego_transportu']) > 50)) {
            $invalidProperties[] = "invalid value for 'opis_innego_transportu', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['opis_innego_transportu']) && (mb_strlen($this->container['opis_innego_transportu']) < 1)) {
            $invalidProperties[] = "invalid value for 'opis_innego_transportu', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['nr_zlecenia_transportu']) && (mb_strlen($this->container['nr_zlecenia_transportu']) > 256)) {
            $invalidProperties[] = "invalid value for 'nr_zlecenia_transportu', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['nr_zlecenia_transportu']) && (mb_strlen($this->container['nr_zlecenia_transportu']) < 1)) {
            $invalidProperties[] = "invalid value for 'nr_zlecenia_transportu', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['ladunek_inny']) && ($this->container['ladunek_inny'] > 1)) {
            $invalidProperties[] = "invalid value for 'ladunek_inny', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['ladunek_inny']) && ($this->container['ladunek_inny'] < 1)) {
            $invalidProperties[] = "invalid value for 'ladunek_inny', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['opis_innego_ladunku']) && (mb_strlen($this->container['opis_innego_ladunku']) > 50)) {
            $invalidProperties[] = "invalid value for 'opis_innego_ladunku', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['opis_innego_ladunku']) && (mb_strlen($this->container['opis_innego_ladunku']) < 1)) {
            $invalidProperties[] = "invalid value for 'opis_innego_ladunku', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['jednostka_opakowania']) && (mb_strlen($this->container['jednostka_opakowania']) > 256)) {
            $invalidProperties[] = "invalid value for 'jednostka_opakowania', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['jednostka_opakowania']) && (mb_strlen($this->container['jednostka_opakowania']) < 1)) {
            $invalidProperties[] = "invalid value for 'jednostka_opakowania', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['wysylka_przez']) && (count($this->container['wysylka_przez']) > 20)) {
            $invalidProperties[] = "invalid value for 'wysylka_przez', number of items must be less than or equal to 20.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rodzaj_transportu
     *
     * @return \KsefApi\Model\TRodzajTransportu|null
     */
    public function getRodzajTransportu()
    {
        return $this->container['rodzaj_transportu'];
    }

    /**
     * Sets rodzaj_transportu
     *
     * @param \KsefApi\Model\TRodzajTransportu|null $rodzaj_transportu rodzaj_transportu
     *
     * @return self
     */
    public function setRodzajTransportu($rodzaj_transportu)
    {
        if (is_null($rodzaj_transportu)) {
            throw new \InvalidArgumentException('non-nullable rodzaj_transportu cannot be null');
        }
        $this->container['rodzaj_transportu'] = $rodzaj_transportu;

        return $this;
    }

    /**
     * Gets transport_inny
     *
     * @return int|null
     */
    public function getTransportInny()
    {
        return $this->container['transport_inny'];
    }

    /**
     * Sets transport_inny
     *
     * @param int|null $transport_inny Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setTransportInny($transport_inny)
    {
        if (is_null($transport_inny)) {
            throw new \InvalidArgumentException('non-nullable transport_inny cannot be null');
        }

        if (($transport_inny > 1)) {
            throw new \InvalidArgumentException('invalid value for $transport_inny when calling Transport., must be smaller than or equal to 1.');
        }
        if (($transport_inny < 1)) {
            throw new \InvalidArgumentException('invalid value for $transport_inny when calling Transport., must be bigger than or equal to 1.');
        }

        $this->container['transport_inny'] = $transport_inny;

        return $this;
    }

    /**
     * Gets opis_innego_transportu
     *
     * @return string|null
     */
    public function getOpisInnegoTransportu()
    {
        return $this->container['opis_innego_transportu'];
    }

    /**
     * Sets opis_innego_transportu
     *
     * @param string|null $opis_innego_transportu Typ znakowy ograniczony do 50 znaków
     *
     * @return self
     */
    public function setOpisInnegoTransportu($opis_innego_transportu)
    {
        if (is_null($opis_innego_transportu)) {
            throw new \InvalidArgumentException('non-nullable opis_innego_transportu cannot be null');
        }
        if ((mb_strlen($opis_innego_transportu) > 50)) {
            throw new \InvalidArgumentException('invalid length for $opis_innego_transportu when calling Transport., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($opis_innego_transportu) < 1)) {
            throw new \InvalidArgumentException('invalid length for $opis_innego_transportu when calling Transport., must be bigger than or equal to 1.');
        }

        $this->container['opis_innego_transportu'] = $opis_innego_transportu;

        return $this;
    }

    /**
     * Gets przewoznik
     *
     * @return \KsefApi\Model\Przewoznik|null
     */
    public function getPrzewoznik()
    {
        return $this->container['przewoznik'];
    }

    /**
     * Sets przewoznik
     *
     * @param \KsefApi\Model\Przewoznik|null $przewoznik przewoznik
     *
     * @return self
     */
    public function setPrzewoznik($przewoznik)
    {
        if (is_null($przewoznik)) {
            throw new \InvalidArgumentException('non-nullable przewoznik cannot be null');
        }
        $this->container['przewoznik'] = $przewoznik;

        return $this;
    }

    /**
     * Gets nr_zlecenia_transportu
     *
     * @return string|null
     */
    public function getNrZleceniaTransportu()
    {
        return $this->container['nr_zlecenia_transportu'];
    }

    /**
     * Sets nr_zlecenia_transportu
     *
     * @param string|null $nr_zlecenia_transportu Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setNrZleceniaTransportu($nr_zlecenia_transportu)
    {
        if (is_null($nr_zlecenia_transportu)) {
            throw new \InvalidArgumentException('non-nullable nr_zlecenia_transportu cannot be null');
        }
        if ((mb_strlen($nr_zlecenia_transportu) > 256)) {
            throw new \InvalidArgumentException('invalid length for $nr_zlecenia_transportu when calling Transport., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($nr_zlecenia_transportu) < 1)) {
            throw new \InvalidArgumentException('invalid length for $nr_zlecenia_transportu when calling Transport., must be bigger than or equal to 1.');
        }

        $this->container['nr_zlecenia_transportu'] = $nr_zlecenia_transportu;

        return $this;
    }

    /**
     * Gets opis_ladunku
     *
     * @return \KsefApi\Model\TLadunek|null
     */
    public function getOpisLadunku()
    {
        return $this->container['opis_ladunku'];
    }

    /**
     * Sets opis_ladunku
     *
     * @param \KsefApi\Model\TLadunek|null $opis_ladunku opis_ladunku
     *
     * @return self
     */
    public function setOpisLadunku($opis_ladunku)
    {
        if (is_null($opis_ladunku)) {
            throw new \InvalidArgumentException('non-nullable opis_ladunku cannot be null');
        }
        $this->container['opis_ladunku'] = $opis_ladunku;

        return $this;
    }

    /**
     * Gets ladunek_inny
     *
     * @return int|null
     */
    public function getLadunekInny()
    {
        return $this->container['ladunek_inny'];
    }

    /**
     * Sets ladunek_inny
     *
     * @param int|null $ladunek_inny Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setLadunekInny($ladunek_inny)
    {
        if (is_null($ladunek_inny)) {
            throw new \InvalidArgumentException('non-nullable ladunek_inny cannot be null');
        }

        if (($ladunek_inny > 1)) {
            throw new \InvalidArgumentException('invalid value for $ladunek_inny when calling Transport., must be smaller than or equal to 1.');
        }
        if (($ladunek_inny < 1)) {
            throw new \InvalidArgumentException('invalid value for $ladunek_inny when calling Transport., must be bigger than or equal to 1.');
        }

        $this->container['ladunek_inny'] = $ladunek_inny;

        return $this;
    }

    /**
     * Gets opis_innego_ladunku
     *
     * @return string|null
     */
    public function getOpisInnegoLadunku()
    {
        return $this->container['opis_innego_ladunku'];
    }

    /**
     * Sets opis_innego_ladunku
     *
     * @param string|null $opis_innego_ladunku Typ znakowy ograniczony do 50 znaków
     *
     * @return self
     */
    public function setOpisInnegoLadunku($opis_innego_ladunku)
    {
        if (is_null($opis_innego_ladunku)) {
            throw new \InvalidArgumentException('non-nullable opis_innego_ladunku cannot be null');
        }
        if ((mb_strlen($opis_innego_ladunku) > 50)) {
            throw new \InvalidArgumentException('invalid length for $opis_innego_ladunku when calling Transport., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($opis_innego_ladunku) < 1)) {
            throw new \InvalidArgumentException('invalid length for $opis_innego_ladunku when calling Transport., must be bigger than or equal to 1.');
        }

        $this->container['opis_innego_ladunku'] = $opis_innego_ladunku;

        return $this;
    }

    /**
     * Gets jednostka_opakowania
     *
     * @return string|null
     */
    public function getJednostkaOpakowania()
    {
        return $this->container['jednostka_opakowania'];
    }

    /**
     * Sets jednostka_opakowania
     *
     * @param string|null $jednostka_opakowania Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setJednostkaOpakowania($jednostka_opakowania)
    {
        if (is_null($jednostka_opakowania)) {
            throw new \InvalidArgumentException('non-nullable jednostka_opakowania cannot be null');
        }
        if ((mb_strlen($jednostka_opakowania) > 256)) {
            throw new \InvalidArgumentException('invalid length for $jednostka_opakowania when calling Transport., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($jednostka_opakowania) < 1)) {
            throw new \InvalidArgumentException('invalid length for $jednostka_opakowania when calling Transport., must be bigger than or equal to 1.');
        }

        $this->container['jednostka_opakowania'] = $jednostka_opakowania;

        return $this;
    }

    /**
     * Gets data_godz_rozp_transportu
     *
     * @return \DateTime|null
     */
    public function getDataGodzRozpTransportu()
    {
        return $this->container['data_godz_rozp_transportu'];
    }

    /**
     * Sets data_godz_rozp_transportu
     *
     * @param \DateTime|null $data_godz_rozp_transportu Data i czas zdarzenia w okresie od 01.10.2021T00:00:00Z do 01.01.2050T23:59:59Z
     *
     * @return self
     */
    public function setDataGodzRozpTransportu($data_godz_rozp_transportu)
    {
        if (is_null($data_godz_rozp_transportu)) {
            throw new \InvalidArgumentException('non-nullable data_godz_rozp_transportu cannot be null');
        }
        $this->container['data_godz_rozp_transportu'] = $data_godz_rozp_transportu;

        return $this;
    }

    /**
     * Gets data_godz_zak_transportu
     *
     * @return \DateTime|null
     */
    public function getDataGodzZakTransportu()
    {
        return $this->container['data_godz_zak_transportu'];
    }

    /**
     * Sets data_godz_zak_transportu
     *
     * @param \DateTime|null $data_godz_zak_transportu Data i czas zdarzenia w okresie od 01.10.2021T00:00:00Z do 01.01.2050T23:59:59Z
     *
     * @return self
     */
    public function setDataGodzZakTransportu($data_godz_zak_transportu)
    {
        if (is_null($data_godz_zak_transportu)) {
            throw new \InvalidArgumentException('non-nullable data_godz_zak_transportu cannot be null');
        }
        $this->container['data_godz_zak_transportu'] = $data_godz_zak_transportu;

        return $this;
    }

    /**
     * Gets wysylka_z
     *
     * @return \KsefApi\Model\TAdres|null
     */
    public function getWysylkaZ()
    {
        return $this->container['wysylka_z'];
    }

    /**
     * Sets wysylka_z
     *
     * @param \KsefApi\Model\TAdres|null $wysylka_z wysylka_z
     *
     * @return self
     */
    public function setWysylkaZ($wysylka_z)
    {
        if (is_null($wysylka_z)) {
            throw new \InvalidArgumentException('non-nullable wysylka_z cannot be null');
        }
        $this->container['wysylka_z'] = $wysylka_z;

        return $this;
    }

    /**
     * Gets wysylka_przez
     *
     * @return \KsefApi\Model\TAdres[]|null
     */
    public function getWysylkaPrzez()
    {
        return $this->container['wysylka_przez'];
    }

    /**
     * Sets wysylka_przez
     *
     * @param \KsefApi\Model\TAdres[]|null $wysylka_przez wysylka_przez
     *
     * @return self
     */
    public function setWysylkaPrzez($wysylka_przez)
    {
        if (is_null($wysylka_przez)) {
            throw new \InvalidArgumentException('non-nullable wysylka_przez cannot be null');
        }

        if ((count($wysylka_przez) > 20)) {
            throw new \InvalidArgumentException('invalid value for $wysylka_przez when calling Transport., number of items must be less than or equal to 20.');
        }
        $this->container['wysylka_przez'] = $wysylka_przez;

        return $this;
    }

    /**
     * Gets wysylka_do
     *
     * @return \KsefApi\Model\TAdres|null
     */
    public function getWysylkaDo()
    {
        return $this->container['wysylka_do'];
    }

    /**
     * Sets wysylka_do
     *
     * @param \KsefApi\Model\TAdres|null $wysylka_do wysylka_do
     *
     * @return self
     */
    public function setWysylkaDo($wysylka_do)
    {
        if (is_null($wysylka_do)) {
            throw new \InvalidArgumentException('non-nullable wysylka_do cannot be null');
        }
        $this->container['wysylka_do'] = $wysylka_do;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


