<?php
/**
 * TRolaPodmiotu3
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;
use \KsefApi\ObjectSerializer;

/**
 * TRolaPodmiotu3 Class Doc Comment
 *
 * @category Class
 * @description Role of the third-party entity (1 - factor - when the invoice includes factor data, 2 - recipient - when the invoice includes data of internal units/branches within the buyer that are not themselves buyers within the meaning of the Act, 3 - original entity - when the invoice includes data of an entity that, in relation to the taxpayer, has been acquired or transformed and provided the service or supplied the goods. Excluding cases referred to in Art. 106j(2)(3) of the Act where these data are shown in Podmiot1K, 4 - additional buyer - when the invoice includes data of subsequent buyers (other than the one listed in Podmiot2), 5 - invoice issuer - when the invoice includes data of the entity issuing the invoice on behalf of the taxpayer. Does not apply when the buyer issues the invoice, 6 - payer - when the invoice includes data of the entity settling the liability instead of the buyer, 7 - local government unit - issuer, 8 - local government unit - recipient, 9 - VAT group member - issuer, 10 - VAT group member - recipient
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TRolaPodmiotu3
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_1 = 1;

    public const NUMBER_2 = 2;

    public const NUMBER_3 = 3;

    public const NUMBER_4 = 4;

    public const NUMBER_5 = 5;

    public const NUMBER_6 = 6;

    public const NUMBER_7 = 7;

    public const NUMBER_8 = 8;

    public const NUMBER_9 = 9;

    public const NUMBER_10 = 10;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_1,
            self::NUMBER_2,
            self::NUMBER_3,
            self::NUMBER_4,
            self::NUMBER_5,
            self::NUMBER_6,
            self::NUMBER_7,
            self::NUMBER_8,
            self::NUMBER_9,
            self::NUMBER_10
        ];
    }
}


