<?php
/**
 * TStawkaPodatku
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;
use \KsefApi\ObjectSerializer;

/**
 * TStawkaPodatku Class Doc Comment
 *
 * @category Class
 * @description Stawka podatku
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TStawkaPodatku
{
    /**
     * Possible values of this enum
     */
    public const _23 = '23';

    public const _22 = '22';

    public const _8 = '8';

    public const _7 = '7';

    public const _5 = '5';

    public const _4 = '4';

    public const _3 = '3';

    public const _0 = '0';

    public const ZW = 'zw';

    public const OO = 'oo';

    public const NP = 'np';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_23,
            self::_22,
            self::_8,
            self::_7,
            self::_5,
            self::_4,
            self::_3,
            self::_0,
            self::ZW,
            self::OO,
            self::NP
        ];
    }
}


