<?php
/**
 * TTabela
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * TTabela Class Doc Comment
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TTabela implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TTabela';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'meta_dane' => '\KsefApi\Model\TKluczWartosc[]',
        'opis' => 'string',
        'naglowek' => '\KsefApi\Model\TKol[]',
        'wiersz' => 'array[]',
        'suma' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'meta_dane' => null,
        'opis' => null,
        'naglowek' => null,
        'wiersz' => null,
        'suma' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'meta_dane' => false,
        'opis' => false,
        'naglowek' => false,
        'wiersz' => false,
        'suma' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'meta_dane' => 'MetaDane',
        'opis' => 'Opis',
        'naglowek' => 'Naglowek',
        'wiersz' => 'Wiersz',
        'suma' => 'Suma'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'meta_dane' => 'setMetaDane',
        'opis' => 'setOpis',
        'naglowek' => 'setNaglowek',
        'wiersz' => 'setWiersz',
        'suma' => 'setSuma'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'meta_dane' => 'getMetaDane',
        'opis' => 'getOpis',
        'naglowek' => 'getNaglowek',
        'wiersz' => 'getWiersz',
        'suma' => 'getSuma'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('meta_dane', $data ?? [], null);
        $this->setIfExists('opis', $data ?? [], null);
        $this->setIfExists('naglowek', $data ?? [], null);
        $this->setIfExists('wiersz', $data ?? [], null);
        $this->setIfExists('suma', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['meta_dane']) && (count($this->container['meta_dane']) > 1000)) {
            $invalidProperties[] = "invalid value for 'meta_dane', number of items must be less than or equal to 1000.";
        }

        if (!is_null($this->container['opis']) && (mb_strlen($this->container['opis']) > 512)) {
            $invalidProperties[] = "invalid value for 'opis', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['opis']) && (mb_strlen($this->container['opis']) < 1)) {
            $invalidProperties[] = "invalid value for 'opis', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['naglowek']) && (count($this->container['naglowek']) > 20)) {
            $invalidProperties[] = "invalid value for 'naglowek', number of items must be less than or equal to 20.";
        }

        if (!is_null($this->container['wiersz']) && (count($this->container['wiersz']) > 1000)) {
            $invalidProperties[] = "invalid value for 'wiersz', number of items must be less than or equal to 1000.";
        }

        if (!is_null($this->container['suma']) && (count($this->container['suma']) > 20)) {
            $invalidProperties[] = "invalid value for 'suma', number of items must be less than or equal to 20.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets meta_dane
     *
     * @return \KsefApi\Model\TKluczWartosc[]|null
     */
    public function getMetaDane()
    {
        return $this->container['meta_dane'];
    }

    /**
     * Sets meta_dane
     *
     * @param \KsefApi\Model\TKluczWartosc[]|null $meta_dane meta_dane
     *
     * @return self
     */
    public function setMetaDane($meta_dane)
    {
        if (is_null($meta_dane)) {
            throw new \InvalidArgumentException('non-nullable meta_dane cannot be null');
        }

        if ((count($meta_dane) > 1000)) {
            throw new \InvalidArgumentException('invalid value for $meta_dane when calling TTabela., number of items must be less than or equal to 1000.');
        }
        $this->container['meta_dane'] = $meta_dane;

        return $this;
    }

    /**
     * Gets opis
     *
     * @return string|null
     */
    public function getOpis()
    {
        return $this->container['opis'];
    }

    /**
     * Sets opis
     *
     * @param string|null $opis Typ znakowy ograniczony do 512 znaków
     *
     * @return self
     */
    public function setOpis($opis)
    {
        if (is_null($opis)) {
            throw new \InvalidArgumentException('non-nullable opis cannot be null');
        }
        if ((mb_strlen($opis) > 512)) {
            throw new \InvalidArgumentException('invalid length for $opis when calling TTabela., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($opis) < 1)) {
            throw new \InvalidArgumentException('invalid length for $opis when calling TTabela., must be bigger than or equal to 1.');
        }

        $this->container['opis'] = $opis;

        return $this;
    }

    /**
     * Gets naglowek
     *
     * @return \KsefApi\Model\TKol[]|null
     */
    public function getNaglowek()
    {
        return $this->container['naglowek'];
    }

    /**
     * Sets naglowek
     *
     * @param \KsefApi\Model\TKol[]|null $naglowek naglowek
     *
     * @return self
     */
    public function setNaglowek($naglowek)
    {
        if (is_null($naglowek)) {
            throw new \InvalidArgumentException('non-nullable naglowek cannot be null');
        }

        if ((count($naglowek) > 20)) {
            throw new \InvalidArgumentException('invalid value for $naglowek when calling TTabela., number of items must be less than or equal to 20.');
        }
        $this->container['naglowek'] = $naglowek;

        return $this;
    }

    /**
     * Gets wiersz
     *
     * @return array[]|null
     */
    public function getWiersz()
    {
        return $this->container['wiersz'];
    }

    /**
     * Sets wiersz
     *
     * @param array[]|null $wiersz wiersz
     *
     * @return self
     */
    public function setWiersz($wiersz)
    {
        if (is_null($wiersz)) {
            throw new \InvalidArgumentException('non-nullable wiersz cannot be null');
        }

        if ((count($wiersz) > 1000)) {
            throw new \InvalidArgumentException('invalid value for $wiersz when calling TTabela., number of items must be less than or equal to 1000.');
        }
        $this->container['wiersz'] = $wiersz;

        return $this;
    }

    /**
     * Gets suma
     *
     * @return string[]|null
     */
    public function getSuma()
    {
        return $this->container['suma'];
    }

    /**
     * Sets suma
     *
     * @param string[]|null $suma suma
     *
     * @return self
     */
    public function setSuma($suma)
    {
        if (is_null($suma)) {
            throw new \InvalidArgumentException('non-nullable suma cannot be null');
        }

        if ((count($suma) > 20)) {
            throw new \InvalidArgumentException('invalid value for $suma when calling TTabela., number of items must be less than or equal to 20.');
        }
        $this->container['suma'] = $suma;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


