<?php
/**
 * WarunkiTransakcji
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * WarunkiTransakcji Class Doc Comment
 *
 * @category Class
 * @description Warunki transakcji, o ile występują
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WarunkiTransakcji implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WarunkiTransakcji';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'umowy' => '\KsefApi\Model\Umowy[]',
        'zamowienia' => '\KsefApi\Model\Zamowienia[]',
        'nr_partii_towaru' => 'string[]',
        'warunki_dostawy' => 'string',
        'kurs_umowny' => 'float',
        'waluta_umowna' => '\KsefApi\Model\TKodWaluty',
        'transport' => '\KsefApi\Model\Transport[]',
        'podmiot_posredniczacy' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'umowy' => null,
        'zamowienia' => null,
        'nr_partii_towaru' => null,
        'warunki_dostawy' => null,
        'kurs_umowny' => 'double',
        'waluta_umowna' => null,
        'transport' => null,
        'podmiot_posredniczacy' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'umowy' => false,
        'zamowienia' => false,
        'nr_partii_towaru' => false,
        'warunki_dostawy' => false,
        'kurs_umowny' => false,
        'waluta_umowna' => false,
        'transport' => false,
        'podmiot_posredniczacy' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'umowy' => 'Umowy',
        'zamowienia' => 'Zamowienia',
        'nr_partii_towaru' => 'NrPartiiTowaru',
        'warunki_dostawy' => 'WarunkiDostawy',
        'kurs_umowny' => 'KursUmowny',
        'waluta_umowna' => 'WalutaUmowna',
        'transport' => 'Transport',
        'podmiot_posredniczacy' => 'PodmiotPosredniczacy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'umowy' => 'setUmowy',
        'zamowienia' => 'setZamowienia',
        'nr_partii_towaru' => 'setNrPartiiTowaru',
        'warunki_dostawy' => 'setWarunkiDostawy',
        'kurs_umowny' => 'setKursUmowny',
        'waluta_umowna' => 'setWalutaUmowna',
        'transport' => 'setTransport',
        'podmiot_posredniczacy' => 'setPodmiotPosredniczacy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'umowy' => 'getUmowy',
        'zamowienia' => 'getZamowienia',
        'nr_partii_towaru' => 'getNrPartiiTowaru',
        'warunki_dostawy' => 'getWarunkiDostawy',
        'kurs_umowny' => 'getKursUmowny',
        'waluta_umowna' => 'getWalutaUmowna',
        'transport' => 'getTransport',
        'podmiot_posredniczacy' => 'getPodmiotPosredniczacy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('umowy', $data ?? [], null);
        $this->setIfExists('zamowienia', $data ?? [], null);
        $this->setIfExists('nr_partii_towaru', $data ?? [], null);
        $this->setIfExists('warunki_dostawy', $data ?? [], null);
        $this->setIfExists('kurs_umowny', $data ?? [], null);
        $this->setIfExists('waluta_umowna', $data ?? [], null);
        $this->setIfExists('transport', $data ?? [], null);
        $this->setIfExists('podmiot_posredniczacy', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['umowy']) && (count($this->container['umowy']) > 100)) {
            $invalidProperties[] = "invalid value for 'umowy', number of items must be less than or equal to 100.";
        }

        if (!is_null($this->container['zamowienia']) && (count($this->container['zamowienia']) > 100)) {
            $invalidProperties[] = "invalid value for 'zamowienia', number of items must be less than or equal to 100.";
        }

        if (!is_null($this->container['nr_partii_towaru']) && (count($this->container['nr_partii_towaru']) > 1000)) {
            $invalidProperties[] = "invalid value for 'nr_partii_towaru', number of items must be less than or equal to 1000.";
        }

        if (!is_null($this->container['warunki_dostawy']) && (mb_strlen($this->container['warunki_dostawy']) > 256)) {
            $invalidProperties[] = "invalid value for 'warunki_dostawy', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['warunki_dostawy']) && (mb_strlen($this->container['warunki_dostawy']) < 1)) {
            $invalidProperties[] = "invalid value for 'warunki_dostawy', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['transport']) && (count($this->container['transport']) > 20)) {
            $invalidProperties[] = "invalid value for 'transport', number of items must be less than or equal to 20.";
        }

        if (!is_null($this->container['podmiot_posredniczacy']) && ($this->container['podmiot_posredniczacy'] > 1)) {
            $invalidProperties[] = "invalid value for 'podmiot_posredniczacy', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['podmiot_posredniczacy']) && ($this->container['podmiot_posredniczacy'] < 1)) {
            $invalidProperties[] = "invalid value for 'podmiot_posredniczacy', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets umowy
     *
     * @return \KsefApi\Model\Umowy[]|null
     */
    public function getUmowy()
    {
        return $this->container['umowy'];
    }

    /**
     * Sets umowy
     *
     * @param \KsefApi\Model\Umowy[]|null $umowy umowy
     *
     * @return self
     */
    public function setUmowy($umowy)
    {
        if (is_null($umowy)) {
            throw new \InvalidArgumentException('non-nullable umowy cannot be null');
        }

        if ((count($umowy) > 100)) {
            throw new \InvalidArgumentException('invalid value for $umowy when calling WarunkiTransakcji., number of items must be less than or equal to 100.');
        }
        $this->container['umowy'] = $umowy;

        return $this;
    }

    /**
     * Gets zamowienia
     *
     * @return \KsefApi\Model\Zamowienia[]|null
     */
    public function getZamowienia()
    {
        return $this->container['zamowienia'];
    }

    /**
     * Sets zamowienia
     *
     * @param \KsefApi\Model\Zamowienia[]|null $zamowienia zamowienia
     *
     * @return self
     */
    public function setZamowienia($zamowienia)
    {
        if (is_null($zamowienia)) {
            throw new \InvalidArgumentException('non-nullable zamowienia cannot be null');
        }

        if ((count($zamowienia) > 100)) {
            throw new \InvalidArgumentException('invalid value for $zamowienia when calling WarunkiTransakcji., number of items must be less than or equal to 100.');
        }
        $this->container['zamowienia'] = $zamowienia;

        return $this;
    }

    /**
     * Gets nr_partii_towaru
     *
     * @return string[]|null
     */
    public function getNrPartiiTowaru()
    {
        return $this->container['nr_partii_towaru'];
    }

    /**
     * Sets nr_partii_towaru
     *
     * @param string[]|null $nr_partii_towaru nr_partii_towaru
     *
     * @return self
     */
    public function setNrPartiiTowaru($nr_partii_towaru)
    {
        if (is_null($nr_partii_towaru)) {
            throw new \InvalidArgumentException('non-nullable nr_partii_towaru cannot be null');
        }

        if ((count($nr_partii_towaru) > 1000)) {
            throw new \InvalidArgumentException('invalid value for $nr_partii_towaru when calling WarunkiTransakcji., number of items must be less than or equal to 1000.');
        }
        $this->container['nr_partii_towaru'] = $nr_partii_towaru;

        return $this;
    }

    /**
     * Gets warunki_dostawy
     *
     * @return string|null
     */
    public function getWarunkiDostawy()
    {
        return $this->container['warunki_dostawy'];
    }

    /**
     * Sets warunki_dostawy
     *
     * @param string|null $warunki_dostawy Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setWarunkiDostawy($warunki_dostawy)
    {
        if (is_null($warunki_dostawy)) {
            throw new \InvalidArgumentException('non-nullable warunki_dostawy cannot be null');
        }
        if ((mb_strlen($warunki_dostawy) > 256)) {
            throw new \InvalidArgumentException('invalid length for $warunki_dostawy when calling WarunkiTransakcji., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($warunki_dostawy) < 1)) {
            throw new \InvalidArgumentException('invalid length for $warunki_dostawy when calling WarunkiTransakcji., must be bigger than or equal to 1.');
        }

        $this->container['warunki_dostawy'] = $warunki_dostawy;

        return $this;
    }

    /**
     * Gets kurs_umowny
     *
     * @return float|null
     */
    public function getKursUmowny()
    {
        return $this->container['kurs_umowny'];
    }

    /**
     * Sets kurs_umowny
     *
     * @param float|null $kurs_umowny Typ wykorzystywany do określenia ilości. Wartość numeryczna 22 znaki max, w tym 6 po przecinku
     *
     * @return self
     */
    public function setKursUmowny($kurs_umowny)
    {
        if (is_null($kurs_umowny)) {
            throw new \InvalidArgumentException('non-nullable kurs_umowny cannot be null');
        }
        $this->container['kurs_umowny'] = $kurs_umowny;

        return $this;
    }

    /**
     * Gets waluta_umowna
     *
     * @return \KsefApi\Model\TKodWaluty|null
     */
    public function getWalutaUmowna()
    {
        return $this->container['waluta_umowna'];
    }

    /**
     * Sets waluta_umowna
     *
     * @param \KsefApi\Model\TKodWaluty|null $waluta_umowna waluta_umowna
     *
     * @return self
     */
    public function setWalutaUmowna($waluta_umowna)
    {
        if (is_null($waluta_umowna)) {
            throw new \InvalidArgumentException('non-nullable waluta_umowna cannot be null');
        }
        $this->container['waluta_umowna'] = $waluta_umowna;

        return $this;
    }

    /**
     * Gets transport
     *
     * @return \KsefApi\Model\Transport[]|null
     */
    public function getTransport()
    {
        return $this->container['transport'];
    }

    /**
     * Sets transport
     *
     * @param \KsefApi\Model\Transport[]|null $transport transport
     *
     * @return self
     */
    public function setTransport($transport)
    {
        if (is_null($transport)) {
            throw new \InvalidArgumentException('non-nullable transport cannot be null');
        }

        if ((count($transport) > 20)) {
            throw new \InvalidArgumentException('invalid value for $transport when calling WarunkiTransakcji., number of items must be less than or equal to 20.');
        }
        $this->container['transport'] = $transport;

        return $this;
    }

    /**
     * Gets podmiot_posredniczacy
     *
     * @return int|null
     */
    public function getPodmiotPosredniczacy()
    {
        return $this->container['podmiot_posredniczacy'];
    }

    /**
     * Sets podmiot_posredniczacy
     *
     * @param int|null $podmiot_posredniczacy Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setPodmiotPosredniczacy($podmiot_posredniczacy)
    {
        if (is_null($podmiot_posredniczacy)) {
            throw new \InvalidArgumentException('non-nullable podmiot_posredniczacy cannot be null');
        }

        if (($podmiot_posredniczacy > 1)) {
            throw new \InvalidArgumentException('invalid value for $podmiot_posredniczacy when calling WarunkiTransakcji., must be smaller than or equal to 1.');
        }
        if (($podmiot_posredniczacy < 1)) {
            throw new \InvalidArgumentException('invalid value for $podmiot_posredniczacy when calling WarunkiTransakcji., must be bigger than or equal to 1.');
        }

        $this->container['podmiot_posredniczacy'] = $podmiot_posredniczacy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


