<?php
/**
 * ZamowienieWiersz
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * ZamowienieWiersz Class Doc Comment
 *
 * @category Class
 * @description Szczegółowe pozycje zamówienia lub umowy w walucie, w której wystawiono fakturę zaliczkową
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ZamowienieWiersz implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ZamowienieWiersz';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'nr_wiersza_zam' => 'int',
        'uu_idz' => 'string',
        'p_7_z' => 'string',
        'indeks_z' => 'string',
        'gtinz' => 'string',
        'pkwi_uz' => 'string',
        'cnz' => 'string',
        'pkobz' => 'string',
        'p_8_az' => 'string',
        'p_8_bz' => 'float',
        'p_9_az' => 'float',
        'p_11_netto_z' => 'float',
        'p_11_vat_z' => 'float',
        'p_12_z' => '\KsefApi\Model\TStawkaPodatku',
        'p_12_z_xii' => 'float',
        'p_12_z_zal_15' => 'int',
        'gtuz' => '\KsefApi\Model\TGTU',
        'procedura_z' => '\KsefApi\Model\TOznaczenieProceduryZ',
        'kwota_akcyzy_z' => 'float',
        'stan_przed_z' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'nr_wiersza_zam' => 'int32',
        'uu_idz' => null,
        'p_7_z' => null,
        'indeks_z' => null,
        'gtinz' => null,
        'pkwi_uz' => null,
        'cnz' => null,
        'pkobz' => null,
        'p_8_az' => null,
        'p_8_bz' => 'double',
        'p_9_az' => 'double',
        'p_11_netto_z' => 'double',
        'p_11_vat_z' => 'double',
        'p_12_z' => null,
        'p_12_z_xii' => 'double',
        'p_12_z_zal_15' => 'int32',
        'gtuz' => null,
        'procedura_z' => null,
        'kwota_akcyzy_z' => 'double',
        'stan_przed_z' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'nr_wiersza_zam' => false,
        'uu_idz' => false,
        'p_7_z' => false,
        'indeks_z' => false,
        'gtinz' => false,
        'pkwi_uz' => false,
        'cnz' => false,
        'pkobz' => false,
        'p_8_az' => false,
        'p_8_bz' => false,
        'p_9_az' => false,
        'p_11_netto_z' => false,
        'p_11_vat_z' => false,
        'p_12_z' => false,
        'p_12_z_xii' => false,
        'p_12_z_zal_15' => false,
        'gtuz' => false,
        'procedura_z' => false,
        'kwota_akcyzy_z' => false,
        'stan_przed_z' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nr_wiersza_zam' => 'NrWierszaZam',
        'uu_idz' => 'UU_IDZ',
        'p_7_z' => 'P_7Z',
        'indeks_z' => 'IndeksZ',
        'gtinz' => 'GTINZ',
        'pkwi_uz' => 'PKWiUZ',
        'cnz' => 'CNZ',
        'pkobz' => 'PKOBZ',
        'p_8_az' => 'P_8AZ',
        'p_8_bz' => 'P_8BZ',
        'p_9_az' => 'P_9AZ',
        'p_11_netto_z' => 'P_11NettoZ',
        'p_11_vat_z' => 'P_11VatZ',
        'p_12_z' => 'P_12Z',
        'p_12_z_xii' => 'P_12Z_XII',
        'p_12_z_zal_15' => 'P_12Z_Zal_15',
        'gtuz' => 'GTUZ',
        'procedura_z' => 'ProceduraZ',
        'kwota_akcyzy_z' => 'KwotaAkcyzyZ',
        'stan_przed_z' => 'StanPrzedZ'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nr_wiersza_zam' => 'setNrWierszaZam',
        'uu_idz' => 'setUuIdz',
        'p_7_z' => 'setP7Z',
        'indeks_z' => 'setIndeksZ',
        'gtinz' => 'setGtinz',
        'pkwi_uz' => 'setPkwiUz',
        'cnz' => 'setCnz',
        'pkobz' => 'setPkobz',
        'p_8_az' => 'setP8Az',
        'p_8_bz' => 'setP8Bz',
        'p_9_az' => 'setP9Az',
        'p_11_netto_z' => 'setP11NettoZ',
        'p_11_vat_z' => 'setP11VatZ',
        'p_12_z' => 'setP12Z',
        'p_12_z_xii' => 'setP12ZXii',
        'p_12_z_zal_15' => 'setP12ZZal15',
        'gtuz' => 'setGtuz',
        'procedura_z' => 'setProceduraZ',
        'kwota_akcyzy_z' => 'setKwotaAkcyzyZ',
        'stan_przed_z' => 'setStanPrzedZ'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nr_wiersza_zam' => 'getNrWierszaZam',
        'uu_idz' => 'getUuIdz',
        'p_7_z' => 'getP7Z',
        'indeks_z' => 'getIndeksZ',
        'gtinz' => 'getGtinz',
        'pkwi_uz' => 'getPkwiUz',
        'cnz' => 'getCnz',
        'pkobz' => 'getPkobz',
        'p_8_az' => 'getP8Az',
        'p_8_bz' => 'getP8Bz',
        'p_9_az' => 'getP9Az',
        'p_11_netto_z' => 'getP11NettoZ',
        'p_11_vat_z' => 'getP11VatZ',
        'p_12_z' => 'getP12Z',
        'p_12_z_xii' => 'getP12ZXii',
        'p_12_z_zal_15' => 'getP12ZZal15',
        'gtuz' => 'getGtuz',
        'procedura_z' => 'getProceduraZ',
        'kwota_akcyzy_z' => 'getKwotaAkcyzyZ',
        'stan_przed_z' => 'getStanPrzedZ'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('nr_wiersza_zam', $data ?? [], null);
        $this->setIfExists('uu_idz', $data ?? [], null);
        $this->setIfExists('p_7_z', $data ?? [], null);
        $this->setIfExists('indeks_z', $data ?? [], null);
        $this->setIfExists('gtinz', $data ?? [], null);
        $this->setIfExists('pkwi_uz', $data ?? [], null);
        $this->setIfExists('cnz', $data ?? [], null);
        $this->setIfExists('pkobz', $data ?? [], null);
        $this->setIfExists('p_8_az', $data ?? [], null);
        $this->setIfExists('p_8_bz', $data ?? [], null);
        $this->setIfExists('p_9_az', $data ?? [], null);
        $this->setIfExists('p_11_netto_z', $data ?? [], null);
        $this->setIfExists('p_11_vat_z', $data ?? [], null);
        $this->setIfExists('p_12_z', $data ?? [], null);
        $this->setIfExists('p_12_z_xii', $data ?? [], null);
        $this->setIfExists('p_12_z_zal_15', $data ?? [], null);
        $this->setIfExists('gtuz', $data ?? [], null);
        $this->setIfExists('procedura_z', $data ?? [], null);
        $this->setIfExists('kwota_akcyzy_z', $data ?? [], null);
        $this->setIfExists('stan_przed_z', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['nr_wiersza_zam']) && ($this->container['nr_wiersza_zam'] <= 0)) {
            $invalidProperties[] = "invalid value for 'nr_wiersza_zam', must be bigger than 0.";
        }

        if (!is_null($this->container['uu_idz']) && (mb_strlen($this->container['uu_idz']) > 50)) {
            $invalidProperties[] = "invalid value for 'uu_idz', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['uu_idz']) && (mb_strlen($this->container['uu_idz']) < 1)) {
            $invalidProperties[] = "invalid value for 'uu_idz', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_7_z']) && (mb_strlen($this->container['p_7_z']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_7_z', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_7_z']) && (mb_strlen($this->container['p_7_z']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_7_z', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['indeks_z']) && (mb_strlen($this->container['indeks_z']) > 50)) {
            $invalidProperties[] = "invalid value for 'indeks_z', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['indeks_z']) && (mb_strlen($this->container['indeks_z']) < 1)) {
            $invalidProperties[] = "invalid value for 'indeks_z', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['gtinz']) && (mb_strlen($this->container['gtinz']) > 20)) {
            $invalidProperties[] = "invalid value for 'gtinz', the character length must be smaller than or equal to 20.";
        }

        if (!is_null($this->container['gtinz']) && (mb_strlen($this->container['gtinz']) < 1)) {
            $invalidProperties[] = "invalid value for 'gtinz', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['pkwi_uz']) && (mb_strlen($this->container['pkwi_uz']) > 50)) {
            $invalidProperties[] = "invalid value for 'pkwi_uz', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['pkwi_uz']) && (mb_strlen($this->container['pkwi_uz']) < 1)) {
            $invalidProperties[] = "invalid value for 'pkwi_uz', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['cnz']) && (mb_strlen($this->container['cnz']) > 50)) {
            $invalidProperties[] = "invalid value for 'cnz', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['cnz']) && (mb_strlen($this->container['cnz']) < 1)) {
            $invalidProperties[] = "invalid value for 'cnz', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['pkobz']) && (mb_strlen($this->container['pkobz']) > 50)) {
            $invalidProperties[] = "invalid value for 'pkobz', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['pkobz']) && (mb_strlen($this->container['pkobz']) < 1)) {
            $invalidProperties[] = "invalid value for 'pkobz', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_8_az']) && (mb_strlen($this->container['p_8_az']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_8_az', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_8_az']) && (mb_strlen($this->container['p_8_az']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_8_az', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_12_z_xii']) && ($this->container['p_12_z_xii'] > 100)) {
            $invalidProperties[] = "invalid value for 'p_12_z_xii', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['p_12_z_xii']) && ($this->container['p_12_z_xii'] < 0)) {
            $invalidProperties[] = "invalid value for 'p_12_z_xii', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['p_12_z_zal_15']) && ($this->container['p_12_z_zal_15'] > 1)) {
            $invalidProperties[] = "invalid value for 'p_12_z_zal_15', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['p_12_z_zal_15']) && ($this->container['p_12_z_zal_15'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_12_z_zal_15', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['stan_przed_z']) && ($this->container['stan_przed_z'] > 1)) {
            $invalidProperties[] = "invalid value for 'stan_przed_z', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['stan_przed_z']) && ($this->container['stan_przed_z'] < 1)) {
            $invalidProperties[] = "invalid value for 'stan_przed_z', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nr_wiersza_zam
     *
     * @return int|null
     */
    public function getNrWierszaZam()
    {
        return $this->container['nr_wiersza_zam'];
    }

    /**
     * Sets nr_wiersza_zam
     *
     * @param int|null $nr_wiersza_zam Liczby naturalne większe od zera
     *
     * @return self
     */
    public function setNrWierszaZam($nr_wiersza_zam)
    {
        if (is_null($nr_wiersza_zam)) {
            throw new \InvalidArgumentException('non-nullable nr_wiersza_zam cannot be null');
        }

        if (($nr_wiersza_zam <= 0)) {
            throw new \InvalidArgumentException('invalid value for $nr_wiersza_zam when calling ZamowienieWiersz., must be bigger than 0.');
        }

        $this->container['nr_wiersza_zam'] = $nr_wiersza_zam;

        return $this;
    }

    /**
     * Gets uu_idz
     *
     * @return string|null
     */
    public function getUuIdz()
    {
        return $this->container['uu_idz'];
    }

    /**
     * Sets uu_idz
     *
     * @param string|null $uu_idz Typ znakowy ograniczony do 50 znaków
     *
     * @return self
     */
    public function setUuIdz($uu_idz)
    {
        if (is_null($uu_idz)) {
            throw new \InvalidArgumentException('non-nullable uu_idz cannot be null');
        }
        if ((mb_strlen($uu_idz) > 50)) {
            throw new \InvalidArgumentException('invalid length for $uu_idz when calling ZamowienieWiersz., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($uu_idz) < 1)) {
            throw new \InvalidArgumentException('invalid length for $uu_idz when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['uu_idz'] = $uu_idz;

        return $this;
    }

    /**
     * Gets p_7_z
     *
     * @return string|null
     */
    public function getP7Z()
    {
        return $this->container['p_7_z'];
    }

    /**
     * Sets p_7_z
     *
     * @param string|null $p_7_z Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP7Z($p_7_z)
    {
        if (is_null($p_7_z)) {
            throw new \InvalidArgumentException('non-nullable p_7_z cannot be null');
        }
        if ((mb_strlen($p_7_z) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_7_z when calling ZamowienieWiersz., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_7_z) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_7_z when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['p_7_z'] = $p_7_z;

        return $this;
    }

    /**
     * Gets indeks_z
     *
     * @return string|null
     */
    public function getIndeksZ()
    {
        return $this->container['indeks_z'];
    }

    /**
     * Sets indeks_z
     *
     * @param string|null $indeks_z Typ znakowy ograniczony do 50 znaków
     *
     * @return self
     */
    public function setIndeksZ($indeks_z)
    {
        if (is_null($indeks_z)) {
            throw new \InvalidArgumentException('non-nullable indeks_z cannot be null');
        }
        if ((mb_strlen($indeks_z) > 50)) {
            throw new \InvalidArgumentException('invalid length for $indeks_z when calling ZamowienieWiersz., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($indeks_z) < 1)) {
            throw new \InvalidArgumentException('invalid length for $indeks_z when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['indeks_z'] = $indeks_z;

        return $this;
    }

    /**
     * Gets gtinz
     *
     * @return string|null
     */
    public function getGtinz()
    {
        return $this->container['gtinz'];
    }

    /**
     * Sets gtinz
     *
     * @param string|null $gtinz Typ znakowy ograniczony do 20 znaków
     *
     * @return self
     */
    public function setGtinz($gtinz)
    {
        if (is_null($gtinz)) {
            throw new \InvalidArgumentException('non-nullable gtinz cannot be null');
        }
        if ((mb_strlen($gtinz) > 20)) {
            throw new \InvalidArgumentException('invalid length for $gtinz when calling ZamowienieWiersz., must be smaller than or equal to 20.');
        }
        if ((mb_strlen($gtinz) < 1)) {
            throw new \InvalidArgumentException('invalid length for $gtinz when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['gtinz'] = $gtinz;

        return $this;
    }

    /**
     * Gets pkwi_uz
     *
     * @return string|null
     */
    public function getPkwiUz()
    {
        return $this->container['pkwi_uz'];
    }

    /**
     * Sets pkwi_uz
     *
     * @param string|null $pkwi_uz Typ znakowy ograniczony do 50 znaków
     *
     * @return self
     */
    public function setPkwiUz($pkwi_uz)
    {
        if (is_null($pkwi_uz)) {
            throw new \InvalidArgumentException('non-nullable pkwi_uz cannot be null');
        }
        if ((mb_strlen($pkwi_uz) > 50)) {
            throw new \InvalidArgumentException('invalid length for $pkwi_uz when calling ZamowienieWiersz., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($pkwi_uz) < 1)) {
            throw new \InvalidArgumentException('invalid length for $pkwi_uz when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['pkwi_uz'] = $pkwi_uz;

        return $this;
    }

    /**
     * Gets cnz
     *
     * @return string|null
     */
    public function getCnz()
    {
        return $this->container['cnz'];
    }

    /**
     * Sets cnz
     *
     * @param string|null $cnz Typ znakowy ograniczony do 50 znaków
     *
     * @return self
     */
    public function setCnz($cnz)
    {
        if (is_null($cnz)) {
            throw new \InvalidArgumentException('non-nullable cnz cannot be null');
        }
        if ((mb_strlen($cnz) > 50)) {
            throw new \InvalidArgumentException('invalid length for $cnz when calling ZamowienieWiersz., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($cnz) < 1)) {
            throw new \InvalidArgumentException('invalid length for $cnz when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['cnz'] = $cnz;

        return $this;
    }

    /**
     * Gets pkobz
     *
     * @return string|null
     */
    public function getPkobz()
    {
        return $this->container['pkobz'];
    }

    /**
     * Sets pkobz
     *
     * @param string|null $pkobz Typ znakowy ograniczony do 50 znaków
     *
     * @return self
     */
    public function setPkobz($pkobz)
    {
        if (is_null($pkobz)) {
            throw new \InvalidArgumentException('non-nullable pkobz cannot be null');
        }
        if ((mb_strlen($pkobz) > 50)) {
            throw new \InvalidArgumentException('invalid length for $pkobz when calling ZamowienieWiersz., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($pkobz) < 1)) {
            throw new \InvalidArgumentException('invalid length for $pkobz when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['pkobz'] = $pkobz;

        return $this;
    }

    /**
     * Gets p_8_az
     *
     * @return string|null
     */
    public function getP8Az()
    {
        return $this->container['p_8_az'];
    }

    /**
     * Sets p_8_az
     *
     * @param string|null $p_8_az Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP8Az($p_8_az)
    {
        if (is_null($p_8_az)) {
            throw new \InvalidArgumentException('non-nullable p_8_az cannot be null');
        }
        if ((mb_strlen($p_8_az) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_8_az when calling ZamowienieWiersz., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_8_az) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_8_az when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['p_8_az'] = $p_8_az;

        return $this;
    }

    /**
     * Gets p_8_bz
     *
     * @return float|null
     */
    public function getP8Bz()
    {
        return $this->container['p_8_bz'];
    }

    /**
     * Sets p_8_bz
     *
     * @param float|null $p_8_bz Typ wykorzystywany do określenia ilości. Wartość numeryczna 22 znaki max, w tym 6 po przecinku
     *
     * @return self
     */
    public function setP8Bz($p_8_bz)
    {
        if (is_null($p_8_bz)) {
            throw new \InvalidArgumentException('non-nullable p_8_bz cannot be null');
        }
        $this->container['p_8_bz'] = $p_8_bz;

        return $this;
    }

    /**
     * Gets p_9_az
     *
     * @return float|null
     */
    public function getP9Az()
    {
        return $this->container['p_9_az'];
    }

    /**
     * Sets p_9_az
     *
     * @param float|null $p_9_az Wartość numeryczna 22 znaki max, w tym 8 znaków po przecinku
     *
     * @return self
     */
    public function setP9Az($p_9_az)
    {
        if (is_null($p_9_az)) {
            throw new \InvalidArgumentException('non-nullable p_9_az cannot be null');
        }
        $this->container['p_9_az'] = $p_9_az;

        return $this;
    }

    /**
     * Gets p_11_netto_z
     *
     * @return float|null
     */
    public function getP11NettoZ()
    {
        return $this->container['p_11_netto_z'];
    }

    /**
     * Sets p_11_netto_z
     *
     * @param float|null $p_11_netto_z Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP11NettoZ($p_11_netto_z)
    {
        if (is_null($p_11_netto_z)) {
            throw new \InvalidArgumentException('non-nullable p_11_netto_z cannot be null');
        }
        $this->container['p_11_netto_z'] = $p_11_netto_z;

        return $this;
    }

    /**
     * Gets p_11_vat_z
     *
     * @return float|null
     */
    public function getP11VatZ()
    {
        return $this->container['p_11_vat_z'];
    }

    /**
     * Sets p_11_vat_z
     *
     * @param float|null $p_11_vat_z Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setP11VatZ($p_11_vat_z)
    {
        if (is_null($p_11_vat_z)) {
            throw new \InvalidArgumentException('non-nullable p_11_vat_z cannot be null');
        }
        $this->container['p_11_vat_z'] = $p_11_vat_z;

        return $this;
    }

    /**
     * Gets p_12_z
     *
     * @return \KsefApi\Model\TStawkaPodatku|null
     */
    public function getP12Z()
    {
        return $this->container['p_12_z'];
    }

    /**
     * Sets p_12_z
     *
     * @param \KsefApi\Model\TStawkaPodatku|null $p_12_z p_12_z
     *
     * @return self
     */
    public function setP12Z($p_12_z)
    {
        if (is_null($p_12_z)) {
            throw new \InvalidArgumentException('non-nullable p_12_z cannot be null');
        }
        $this->container['p_12_z'] = $p_12_z;

        return $this;
    }

    /**
     * Gets p_12_z_xii
     *
     * @return float|null
     */
    public function getP12ZXii()
    {
        return $this->container['p_12_z_xii'];
    }

    /**
     * Sets p_12_z_xii
     *
     * @param float|null $p_12_z_xii Wartość procentowa z dokładnością do 6 miejsc po przecinku
     *
     * @return self
     */
    public function setP12ZXii($p_12_z_xii)
    {
        if (is_null($p_12_z_xii)) {
            throw new \InvalidArgumentException('non-nullable p_12_z_xii cannot be null');
        }

        if (($p_12_z_xii > 100)) {
            throw new \InvalidArgumentException('invalid value for $p_12_z_xii when calling ZamowienieWiersz., must be smaller than or equal to 100.');
        }
        if (($p_12_z_xii < 0)) {
            throw new \InvalidArgumentException('invalid value for $p_12_z_xii when calling ZamowienieWiersz., must be bigger than or equal to 0.');
        }

        $this->container['p_12_z_xii'] = $p_12_z_xii;

        return $this;
    }

    /**
     * Gets p_12_z_zal_15
     *
     * @return int|null
     */
    public function getP12ZZal15()
    {
        return $this->container['p_12_z_zal_15'];
    }

    /**
     * Sets p_12_z_zal_15
     *
     * @param int|null $p_12_z_zal_15 Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setP12ZZal15($p_12_z_zal_15)
    {
        if (is_null($p_12_z_zal_15)) {
            throw new \InvalidArgumentException('non-nullable p_12_z_zal_15 cannot be null');
        }

        if (($p_12_z_zal_15 > 1)) {
            throw new \InvalidArgumentException('invalid value for $p_12_z_zal_15 when calling ZamowienieWiersz., must be smaller than or equal to 1.');
        }
        if (($p_12_z_zal_15 < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_12_z_zal_15 when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['p_12_z_zal_15'] = $p_12_z_zal_15;

        return $this;
    }

    /**
     * Gets gtuz
     *
     * @return \KsefApi\Model\TGTU|null
     */
    public function getGtuz()
    {
        return $this->container['gtuz'];
    }

    /**
     * Sets gtuz
     *
     * @param \KsefApi\Model\TGTU|null $gtuz gtuz
     *
     * @return self
     */
    public function setGtuz($gtuz)
    {
        if (is_null($gtuz)) {
            throw new \InvalidArgumentException('non-nullable gtuz cannot be null');
        }
        $this->container['gtuz'] = $gtuz;

        return $this;
    }

    /**
     * Gets procedura_z
     *
     * @return \KsefApi\Model\TOznaczenieProceduryZ|null
     */
    public function getProceduraZ()
    {
        return $this->container['procedura_z'];
    }

    /**
     * Sets procedura_z
     *
     * @param \KsefApi\Model\TOznaczenieProceduryZ|null $procedura_z procedura_z
     *
     * @return self
     */
    public function setProceduraZ($procedura_z)
    {
        if (is_null($procedura_z)) {
            throw new \InvalidArgumentException('non-nullable procedura_z cannot be null');
        }
        $this->container['procedura_z'] = $procedura_z;

        return $this;
    }

    /**
     * Gets kwota_akcyzy_z
     *
     * @return float|null
     */
    public function getKwotaAkcyzyZ()
    {
        return $this->container['kwota_akcyzy_z'];
    }

    /**
     * Sets kwota_akcyzy_z
     *
     * @param float|null $kwota_akcyzy_z Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku
     *
     * @return self
     */
    public function setKwotaAkcyzyZ($kwota_akcyzy_z)
    {
        if (is_null($kwota_akcyzy_z)) {
            throw new \InvalidArgumentException('non-nullable kwota_akcyzy_z cannot be null');
        }
        $this->container['kwota_akcyzy_z'] = $kwota_akcyzy_z;

        return $this;
    }

    /**
     * Gets stan_przed_z
     *
     * @return int|null
     */
    public function getStanPrzedZ()
    {
        return $this->container['stan_przed_z'];
    }

    /**
     * Sets stan_przed_z
     *
     * @param int|null $stan_przed_z Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setStanPrzedZ($stan_przed_z)
    {
        if (is_null($stan_przed_z)) {
            throw new \InvalidArgumentException('non-nullable stan_przed_z cannot be null');
        }

        if (($stan_przed_z > 1)) {
            throw new \InvalidArgumentException('invalid value for $stan_przed_z when calling ZamowienieWiersz., must be smaller than or equal to 1.');
        }
        if (($stan_przed_z < 1)) {
            throw new \InvalidArgumentException('invalid value for $stan_przed_z when calling ZamowienieWiersz., must be bigger than or equal to 1.');
        }

        $this->container['stan_przed_z'] = $stan_przed_z;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


