<?php
/**
 * Zwolnienie
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KsefApi\Model;

use \ArrayAccess;
use \KsefApi\ObjectSerializer;

/**
 * Zwolnienie Class Doc Comment
 *
 * @category Class
 * @package  KsefApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Zwolnienie implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Zwolnienie';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'p_19' => 'int',
        'p_19_a' => 'string',
        'p_19_b' => 'string',
        'p_19_c' => 'string',
        'p_19_n' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'p_19' => 'int32',
        'p_19_a' => null,
        'p_19_b' => null,
        'p_19_c' => null,
        'p_19_n' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'p_19' => false,
        'p_19_a' => false,
        'p_19_b' => false,
        'p_19_c' => false,
        'p_19_n' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'p_19' => 'P_19',
        'p_19_a' => 'P_19A',
        'p_19_b' => 'P_19B',
        'p_19_c' => 'P_19C',
        'p_19_n' => 'P_19N'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'p_19' => 'setP19',
        'p_19_a' => 'setP19A',
        'p_19_b' => 'setP19B',
        'p_19_c' => 'setP19C',
        'p_19_n' => 'setP19N'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'p_19' => 'getP19',
        'p_19_a' => 'getP19A',
        'p_19_b' => 'getP19B',
        'p_19_c' => 'getP19C',
        'p_19_n' => 'getP19N'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('p_19', $data ?? [], null);
        $this->setIfExists('p_19_a', $data ?? [], null);
        $this->setIfExists('p_19_b', $data ?? [], null);
        $this->setIfExists('p_19_c', $data ?? [], null);
        $this->setIfExists('p_19_n', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['p_19']) && ($this->container['p_19'] > 1)) {
            $invalidProperties[] = "invalid value for 'p_19', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['p_19']) && ($this->container['p_19'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_19', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_19_a']) && (mb_strlen($this->container['p_19_a']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_19_a', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_19_a']) && (mb_strlen($this->container['p_19_a']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_19_a', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_19_b']) && (mb_strlen($this->container['p_19_b']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_19_b', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_19_b']) && (mb_strlen($this->container['p_19_b']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_19_b', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_19_c']) && (mb_strlen($this->container['p_19_c']) > 256)) {
            $invalidProperties[] = "invalid value for 'p_19_c', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['p_19_c']) && (mb_strlen($this->container['p_19_c']) < 1)) {
            $invalidProperties[] = "invalid value for 'p_19_c', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['p_19_n']) && ($this->container['p_19_n'] > 1)) {
            $invalidProperties[] = "invalid value for 'p_19_n', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['p_19_n']) && ($this->container['p_19_n'] < 1)) {
            $invalidProperties[] = "invalid value for 'p_19_n', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets p_19
     *
     * @return int|null
     */
    public function getP19()
    {
        return $this->container['p_19'];
    }

    /**
     * Sets p_19
     *
     * @param int|null $p_19 Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setP19($p_19)
    {
        if (is_null($p_19)) {
            throw new \InvalidArgumentException('non-nullable p_19 cannot be null');
        }

        if (($p_19 > 1)) {
            throw new \InvalidArgumentException('invalid value for $p_19 when calling Zwolnienie., must be smaller than or equal to 1.');
        }
        if (($p_19 < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_19 when calling Zwolnienie., must be bigger than or equal to 1.');
        }

        $this->container['p_19'] = $p_19;

        return $this;
    }

    /**
     * Gets p_19_a
     *
     * @return string|null
     */
    public function getP19A()
    {
        return $this->container['p_19_a'];
    }

    /**
     * Sets p_19_a
     *
     * @param string|null $p_19_a Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP19A($p_19_a)
    {
        if (is_null($p_19_a)) {
            throw new \InvalidArgumentException('non-nullable p_19_a cannot be null');
        }
        if ((mb_strlen($p_19_a) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_19_a when calling Zwolnienie., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_19_a) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_19_a when calling Zwolnienie., must be bigger than or equal to 1.');
        }

        $this->container['p_19_a'] = $p_19_a;

        return $this;
    }

    /**
     * Gets p_19_b
     *
     * @return string|null
     */
    public function getP19B()
    {
        return $this->container['p_19_b'];
    }

    /**
     * Sets p_19_b
     *
     * @param string|null $p_19_b Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP19B($p_19_b)
    {
        if (is_null($p_19_b)) {
            throw new \InvalidArgumentException('non-nullable p_19_b cannot be null');
        }
        if ((mb_strlen($p_19_b) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_19_b when calling Zwolnienie., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_19_b) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_19_b when calling Zwolnienie., must be bigger than or equal to 1.');
        }

        $this->container['p_19_b'] = $p_19_b;

        return $this;
    }

    /**
     * Gets p_19_c
     *
     * @return string|null
     */
    public function getP19C()
    {
        return $this->container['p_19_c'];
    }

    /**
     * Sets p_19_c
     *
     * @param string|null $p_19_c Typ znakowy ograniczony do 256 znaków
     *
     * @return self
     */
    public function setP19C($p_19_c)
    {
        if (is_null($p_19_c)) {
            throw new \InvalidArgumentException('non-nullable p_19_c cannot be null');
        }
        if ((mb_strlen($p_19_c) > 256)) {
            throw new \InvalidArgumentException('invalid length for $p_19_c when calling Zwolnienie., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($p_19_c) < 1)) {
            throw new \InvalidArgumentException('invalid length for $p_19_c when calling Zwolnienie., must be bigger than or equal to 1.');
        }

        $this->container['p_19_c'] = $p_19_c;

        return $this;
    }

    /**
     * Gets p_19_n
     *
     * @return int|null
     */
    public function getP19N()
    {
        return $this->container['p_19_n'];
    }

    /**
     * Sets p_19_n
     *
     * @param int|null $p_19_n Pojedyncze pole wyboru
     *
     * @return self
     */
    public function setP19N($p_19_n)
    {
        if (is_null($p_19_n)) {
            throw new \InvalidArgumentException('non-nullable p_19_n cannot be null');
        }

        if (($p_19_n > 1)) {
            throw new \InvalidArgumentException('invalid value for $p_19_n when calling Zwolnienie., must be smaller than or equal to 1.');
        }
        if (($p_19_n < 1)) {
            throw new \InvalidArgumentException('invalid value for $p_19_n when calling Zwolnienie., must be bigger than or equal to 1.');
        }

        $this->container['p_19_n'] = $p_19_n;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


